-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    canonical_line_word_out_TREADY : IN STD_LOGIC;
    profile_cell_word_count_val : IN STD_LOGIC_VECTOR (2 downto 0);
    add_ln134 : IN STD_LOGIC_VECTOR (8 downto 0);
    zext_ln134 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln132 : IN STD_LOGIC_VECTOR (7 downto 0);
    zext_ln130 : IN STD_LOGIC_VECTOR (6 downto 0);
    empty_60 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_61 : IN STD_LOGIC_VECTOR (351 downto 0);
    profile_serialized_return_slots_val2 : IN STD_LOGIC_VECTOR (2 downto 0);
    empty : IN STD_LOGIC_VECTOR (0 downto 0);
    ordered_cell_val : IN STD_LOGIC_VECTOR (334 downto 0);
    profile_raw_line_words_val : IN STD_LOGIC_VECTOR (8 downto 0);
    canonical_line_word_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    canonical_line_word_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_14D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001101";
    constant ap_const_lv32_14E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001110";
    constant ap_const_lv9_4 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state8_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln640_fu_217_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal canonical_line_word_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal profile_cell_word_count_val_read_read_fu_158_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal zext_ln130_cast_fu_197_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln132_cast_fu_201_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln134_cast_fu_205_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal local_word_index_1_reg_361 : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter5_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_1_reg_361_pp0_iter6_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln640_reg_367 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_fu_247_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_371_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_reg_376 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter1_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter2_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter3_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter5_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_48_reg_376_pp0_iter6_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_return : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_ce : STD_LOGIC;
    signal ap_block_state8_pp0_stage0_iter7_ignore_call4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp45 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter1_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter2_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter3_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter4_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter5_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter6_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter7_phi_ln647_reg_171 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp45 : BOOLEAN;
    signal local_word_index_fu_94 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    signal add_ln650_fu_223_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_local_word_index_1 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln650_fu_241_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln32_1_fu_271_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln645_fu_268_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln32_fu_277_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal result_fu_283_p11 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_254 : BOOLEAN;
    signal ap_condition_208 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ordered_cell_val : IN STD_LOGIC_VECTOR (351 downto 0);
        profile_serialized_return_slots_val : IN STD_LOGIC_VECTOR (2 downto 0);
        profile_cell_word_count_val : IN STD_LOGIC_VECTOR (2 downto 0);
        local_word_index : IN STD_LOGIC_VECTOR (2 downto 0);
        line_faulted : IN STD_LOGIC_VECTOR (0 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component gpx_lane_word_formatter_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    grp_p_anonymous_namespace_make_packed17_cell_word_fu_188 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ordered_cell_val => empty_61,
        profile_serialized_return_slots_val => profile_serialized_return_slots_val2,
        profile_cell_word_count_val => profile_cell_word_count_val,
        local_word_index => local_word_index_1_reg_361,
        line_faulted => empty,
        ap_return => grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_return,
        ap_ce => grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_ce);

    flow_control_loop_pipe_sequential_init_U : component gpx_lane_word_formatter_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter1_phi_ln647_reg_171_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_208)) then
                if ((ap_const_boolean_1 = ap_condition_254)) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= ap_const_lv9_0;
                elsif (((icmp_ln640_fu_217_p2 = ap_const_lv1_0) and (profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_2))) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= zext_ln130_cast_fu_197_p1;
                elsif (((icmp_ln640_fu_217_p2 = ap_const_lv1_0) and (profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_3))) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= zext_ln132_cast_fu_201_p1;
                elsif (((icmp_ln640_fu_217_p2 = ap_const_lv1_0) and (profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_4))) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= zext_ln134_cast_fu_205_p1;
                elsif (((icmp_ln640_fu_217_p2 = ap_const_lv1_0) and (profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_5))) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= add_ln134;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter0_phi_ln647_reg_171;
                end if;
            end if; 
        end if;
    end process;

    local_word_index_fu_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln640_fu_217_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    local_word_index_fu_94 <= add_ln650_fu_223_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    local_word_index_fu_94 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln640_reg_367 <= icmp_ln640_fu_217_p2;
                line_end_reg_371 <= line_end_fu_247_p2;
                line_end_reg_371_pp0_iter1_reg <= line_end_reg_371;
                local_word_index_1_reg_361 <= ap_sig_allocacmp_local_word_index_1;
                local_word_index_1_reg_361_pp0_iter1_reg <= local_word_index_1_reg_361;
                tmp_48_reg_376 <= ordered_cell_val(334 downto 333);
                tmp_48_reg_376_pp0_iter1_reg <= tmp_48_reg_376;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                line_end_reg_371_pp0_iter2_reg <= line_end_reg_371_pp0_iter1_reg;
                line_end_reg_371_pp0_iter3_reg <= line_end_reg_371_pp0_iter2_reg;
                line_end_reg_371_pp0_iter4_reg <= line_end_reg_371_pp0_iter3_reg;
                line_end_reg_371_pp0_iter5_reg <= line_end_reg_371_pp0_iter4_reg;
                line_end_reg_371_pp0_iter6_reg <= line_end_reg_371_pp0_iter5_reg;
                local_word_index_1_reg_361_pp0_iter2_reg <= local_word_index_1_reg_361_pp0_iter1_reg;
                local_word_index_1_reg_361_pp0_iter3_reg <= local_word_index_1_reg_361_pp0_iter2_reg;
                local_word_index_1_reg_361_pp0_iter4_reg <= local_word_index_1_reg_361_pp0_iter3_reg;
                local_word_index_1_reg_361_pp0_iter5_reg <= local_word_index_1_reg_361_pp0_iter4_reg;
                local_word_index_1_reg_361_pp0_iter6_reg <= local_word_index_1_reg_361_pp0_iter5_reg;
                tmp_48_reg_376_pp0_iter2_reg <= tmp_48_reg_376_pp0_iter1_reg;
                tmp_48_reg_376_pp0_iter3_reg <= tmp_48_reg_376_pp0_iter2_reg;
                tmp_48_reg_376_pp0_iter4_reg <= tmp_48_reg_376_pp0_iter3_reg;
                tmp_48_reg_376_pp0_iter5_reg <= tmp_48_reg_376_pp0_iter4_reg;
                tmp_48_reg_376_pp0_iter6_reg <= tmp_48_reg_376_pp0_iter5_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_phi_reg_pp0_iter2_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter1_phi_ln647_reg_171;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter3_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter2_phi_ln647_reg_171;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter4_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter3_phi_ln647_reg_171;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter5_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter4_phi_ln647_reg_171;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter5 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter6_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter5_phi_ln647_reg_171;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then
                ap_phi_reg_pp0_iter7_phi_ln647_reg_171 <= ap_phi_reg_pp0_iter6_phi_ln647_reg_171;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln32_1_fu_271_p2 <= std_logic_vector(unsigned(ap_phi_reg_pp0_iter7_phi_ln647_reg_171) + unsigned(ap_const_lv9_4));
    add_ln32_fu_277_p2 <= std_logic_vector(unsigned(add_ln32_1_fu_271_p2) + unsigned(zext_ln645_fu_268_p1));
    add_ln650_fu_223_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_local_word_index_1) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp45_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7_ignore_call4)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp45 <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7_ignore_call4));
    end process;

        ap_block_pp0_stage0_ignoreCallOp45 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_state8_pp0_stage0_iter7)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter7 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter7));
    end process;


    ap_block_state8_pp0_stage0_iter7_assign_proc : process(canonical_line_word_out_TREADY)
    begin
                ap_block_state8_pp0_stage0_iter7 <= (canonical_line_word_out_TREADY = ap_const_logic_0);
    end process;


    ap_block_state8_pp0_stage0_iter7_ignore_call4_assign_proc : process(canonical_line_word_out_TREADY)
    begin
                ap_block_state8_pp0_stage0_iter7_ignore_call4 <= (canonical_line_word_out_TREADY = ap_const_logic_0);
    end process;


    ap_condition_208_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_208 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_254_assign_proc : process(icmp_ln640_fu_217_p2, profile_cell_word_count_val_read_read_fu_158_p2)
    begin
                ap_condition_254 <= (not((profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_2)) and not((profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_3)) and not((profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_4)) and not((profile_cell_word_count_val_read_read_fu_158_p2 = ap_const_lv3_5)) and (icmp_ln640_fu_217_p2 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln640_fu_217_p2)
    begin
        if (((icmp_ln640_fu_217_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter6_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter6_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7)
    begin
        if (((ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_phi_reg_pp0_iter0_phi_ln647_reg_171 <= "XXXXXXXXX";
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_local_word_index_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, local_word_index_fu_94, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_local_word_index_1 <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_local_word_index_1 <= local_word_index_fu_94;
        end if; 
    end process;

    canonical_line_word_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_fu_283_p11),64));

    canonical_line_word_out_TDATA_blk_n_assign_proc : process(ap_enable_reg_pp0_iter7, canonical_line_word_out_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            canonical_line_word_out_TDATA_blk_n <= canonical_line_word_out_TREADY;
        else 
            canonical_line_word_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    canonical_line_word_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter7, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter7 = ap_const_logic_1))) then 
            canonical_line_word_out_TVALID <= ap_const_logic_1;
        else 
            canonical_line_word_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;


    grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp45)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp45) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_ce <= ap_const_logic_1;
        else 
            grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln640_fu_217_p2 <= "1" when (ap_sig_allocacmp_local_word_index_1 = profile_cell_word_count_val) else "0";
    icmp_ln650_fu_241_p2 <= "1" when (add_ln650_fu_223_p2 = profile_cell_word_count_val) else "0";
    line_end_fu_247_p2 <= (icmp_ln650_fu_241_p2 and empty_60);
    profile_cell_word_count_val_read_read_fu_158_p2 <= profile_cell_word_count_val;
    result_fu_283_p11 <= (((((((((empty & ap_const_lv1_0) & tmp_48_reg_376_pp0_iter6_reg) & ap_const_lv1_0) & line_end_reg_371_pp0_iter6_reg) & ap_const_lv1_0) & profile_raw_line_words_val) & add_ln32_fu_277_p2) & ap_const_lv2_1) & grp_p_anonymous_namespace_make_packed17_cell_word_fu_188_ap_return);
    zext_ln130_cast_fu_197_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln130),9));
    zext_ln132_cast_fu_201_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln132),9));
    zext_ln134_cast_fu_205_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln134),9));
    zext_ln645_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_word_index_1_reg_361_pp0_iter6_reg),9));
end behav;
