-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ordered_cell_val : IN STD_LOGIC_VECTOR (351 downto 0);
    profile_serialized_return_slots_val : IN STD_LOGIC_VECTOR (2 downto 0);
    profile_cell_word_count_val : IN STD_LOGIC_VECTOR (2 downto 0);
    local_word_index : IN STD_LOGIC_VECTOR (2 downto 0);
    line_faulted : IN STD_LOGIC_VECTOR (0 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv8_81 : STD_LOGIC_VECTOR (7 downto 0) := "10000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000110";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_89 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001001";
    constant ap_const_lv32_8A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001010";
    constant ap_const_lv32_8C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001100";

attribute shreg_extract : string;
    signal result_6_reg_205 : STD_LOGIC_VECTOR (8 downto 0);
    signal result_12_reg_224 : STD_LOGIC_VECTOR (10 downto 0);
    signal result_16_reg_243 : STD_LOGIC_VECTOR (12 downto 0);
    signal line_faulted_read_reg_1265 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal line_faulted_read_reg_1265_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_faulted_read_reg_1265_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_faulted_read_reg_1265_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal line_faulted_read_reg_1265_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ordered_cell_val_read_reg_1270 : STD_LOGIC_VECTOR (351 downto 0);
    signal ordered_cell_val_read_reg_1270_pp0_iter1_reg : STD_LOGIC_VECTOR (351 downto 0);
    signal ordered_cell_val_read_reg_1270_pp0_iter2_reg : STD_LOGIC_VECTOR (351 downto 0);
    signal ordered_cell_val_read_reg_1270_pp0_iter3_reg : STD_LOGIC_VECTOR (351 downto 0);
    signal ordered_cell_val_read_reg_1270_pp0_iter4_reg : STD_LOGIC_VECTOR (351 downto 0);
    signal blank_fu_356_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal blank_reg_1282 : STD_LOGIC_VECTOR (0 downto 0);
    signal blank_reg_1282_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal blank_reg_1282_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal blank_reg_1282_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal valid_return_count_fu_364_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal valid_return_count_reg_1287 : STD_LOGIC_VECTOR (2 downto 0);
    signal valid_return_count_reg_1287_pp0_iter1_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal valid_return_count_reg_1287_pp0_iter2_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal valid_return_count_reg_1287_pp0_iter3_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln534_fu_384_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1293 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1293_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1293_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1293_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln534_reg_1293_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_1_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_1_reg_1297 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_2_fu_428_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_2_reg_1301 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln556_3_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_3_reg_1306 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_52_reg_1310 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_5_fu_506_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_5_reg_1315 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_5_reg_1315_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_reg_1319 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_7_fu_542_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_7_reg_1324 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_7_reg_1324_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_reg_1328 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_57_reg_1328_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_9_fu_574_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_9_reg_1333 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_9_reg_1333_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_9_reg_1333_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_reg_1337 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_59_reg_1337_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_11_fu_606_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_11_reg_1342 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_11_reg_1342_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_11_reg_1342_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_reg_1346 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_reg_1346_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_61_reg_1346_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_13_fu_638_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_13_reg_1351 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_13_reg_1351_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_13_reg_1351_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_13_reg_1351_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_reg_1355 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_reg_1355_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_63_reg_1355_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_2_fu_701_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_2_reg_1360 : STD_LOGIC_VECTOR (0 downto 0);
    signal low16_1_fu_707_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_1_reg_1364 : STD_LOGIC_VECTOR (15 downto 0);
    signal and_ln541_5_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_5_reg_1369 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_5_reg_1369_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_5_reg_1369_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_5_reg_1369_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_5_reg_1369_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal low16_fu_764_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_reg_1373 : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_reg_1373_pp0_iter1_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_reg_1373_pp0_iter2_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_reg_1373_pp0_iter3_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal low16_reg_1373_pp0_iter4_reg : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln561_1_fu_837_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln561_1_reg_1378 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln561_3_fu_926_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln561_3_reg_1383 : STD_LOGIC_VECTOR (10 downto 0);
    signal select_ln561_5_fu_1015_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal select_ln561_5_reg_1388 : STD_LOGIC_VECTOR (12 downto 0);
    signal result_24_fu_1140_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal result_24_reg_1393 : STD_LOGIC_VECTOR (24 downto 0);
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_ready : STD_LOGIC;
    signal tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_ready : STD_LOGIC;
    signal tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_ready : STD_LOGIC;
    signal tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_ready : STD_LOGIC;
    signal tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_ready : STD_LOGIC;
    signal tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_phi_mux_result_3_phi_fu_198_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter1_result_3_reg_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_reg_pp0_iter0_result_3_reg_194 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_result_6_phi_fu_208_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal result_5_fu_804_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_reg_pp0_iter1_result_6_reg_205 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln533_1_fu_768_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_phi_mux_result_8_phi_fu_218_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal result_7_fu_849_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_reg_pp0_iter2_result_8_reg_215 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln533_2_fu_844_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_phi_mux_result_12_phi_fu_227_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal result_9_fu_893_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_reg_pp0_iter2_result_12_reg_224 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln533_3_fu_857_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_phi_mux_result_14_phi_fu_237_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal result_13_fu_938_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_reg_pp0_iter3_result_14_reg_234 : STD_LOGIC_VECTOR (11 downto 0);
    signal zext_ln533_4_fu_933_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_phi_mux_result_16_phi_fu_246_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal result_15_fu_982_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_reg_pp0_iter3_result_16_reg_243 : STD_LOGIC_VECTOR (12 downto 0);
    signal zext_ln533_5_fu_946_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_phi_mux_result_18_phi_fu_256_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal result_17_fu_1027_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_reg_pp0_iter4_result_18_reg_253 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln533_6_fu_1022_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_phi_reg_pp0_iter0_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter1_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter2_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter3_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter4_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_reg_pp0_iter5_result_1_reg_262 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_result_11_phi_fu_276_p6 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_29_fu_1241_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp0_iter5_result_11_reg_273 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_4_fu_1257_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln533_fu_1252_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln521_fu_345_p1 : STD_LOGIC_VECTOR (133 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp28 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp79 : BOOLEAN;
    signal shl_ln535_fu_664_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp37 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp89 : BOOLEAN;
    signal or_ln_fu_719_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0_ignoreCallOp43 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp49 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp55 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp61 : BOOLEAN;
    signal ap_block_pp0_stage0_ignoreCallOp67 : BOOLEAN;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln519_1_fu_337_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal hit_word_count_fu_378_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln519_fu_333_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln558_fu_402_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln556_fu_390_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_fu_408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_fu_396_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_436_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_51_fu_452_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln558_1_fu_462_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_2_fu_468_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_1_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln558_2_fu_494_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_4_fu_500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_2_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_56_fu_528_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_6_fu_536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_55_fu_520_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln558_3_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_8_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_3_fu_556_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln558_4_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_10_fu_600_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_4_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln558_5_fu_626_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln556_12_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln557_5_fu_620_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_return_fu_652_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln527_fu_374_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln519_2_fu_341_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln543_fu_683_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln542_fu_677_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln541_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_1_fu_695_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_fu_689_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln535_fu_660_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal return_index_1_fu_711_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln543_1_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln542_1_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln541_1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_4_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln541_3_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_49_fu_773_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_fu_783_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_fu_787_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln561_fu_797_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_54_fu_813_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_1_fu_823_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal or_ln563_1_fu_827_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_58_fu_862_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_2_fu_872_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln563_2_fu_876_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal select_ln561_2_fu_886_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_60_fu_902_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_3_fu_912_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal or_ln563_3_fu_916_p4 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_62_fu_951_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_4_fu_961_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal or_ln563_4_fu_965_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal select_ln561_4_fu_975_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_64_fu_991_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln563_5_fu_1001_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln563_5_fu_1005_p4 : STD_LOGIC_VECTOR (12 downto 0);
    signal result_19_fu_1035_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_65_fu_1046_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln2_fu_1053_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln533_7_fu_1042_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_1_fu_1070_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_2_fu_1079_p4 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_20_fu_1062_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal result_21_fu_1088_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal result_22_fu_1102_p5 : STD_LOGIC_VECTOR (23 downto 0);
    signal zext_ln533_8_fu_1098_p1 : STD_LOGIC_VECTOR (23 downto 0);
    signal result_23_fu_1114_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal tmp_66_fu_1125_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln3_fu_1132_p3 : STD_LOGIC_VECTOR (24 downto 0);
    signal zext_ln533_9_fu_1121_p1 : STD_LOGIC_VECTOR (24 downto 0);
    signal tmp_67_fu_1151_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_25_fu_1158_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal zext_ln533_10_fu_1148_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal result_26_fu_1165_p3 : STD_LOGIC_VECTOR (25 downto 0);
    signal tmp_68_fu_1177_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln4_fu_1184_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal zext_ln533_11_fu_1173_p1 : STD_LOGIC_VECTOR (26 downto 0);
    signal result_27_fu_1192_p3 : STD_LOGIC_VECTOR (26 downto 0);
    signal tmp_69_fu_1204_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_fu_1219_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_28_fu_1211_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal zext_ln533_12_fu_1200_p1 : STD_LOGIC_VECTOR (27 downto 0);
    signal tmp_3_fu_1232_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal result_10_fu_1224_p3 : STD_LOGIC_VECTOR (27 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ordered_cell_val_int_reg : STD_LOGIC_VECTOR (351 downto 0);
    signal profile_serialized_return_slots_val_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal profile_cell_word_count_val_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal local_word_index_int_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal line_faulted_int_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_return_int_reg : STD_LOGIC_VECTOR (31 downto 0);

    component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit IS
    port (
        ap_ready : OUT STD_LOGIC;
        cell_val : IN STD_LOGIC_VECTOR (133 downto 0);
        return_index : IN STD_LOGIC_VECTOR (2 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (16 downto 0);
        ap_rst : IN STD_LOGIC );
    end component;



begin
    grp_p_anonymous_namespace_read_packed_distance_hit_fu_284 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index,
        ap_return => grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return,
        ap_rst => ap_rst);

    grp_p_anonymous_namespace_read_packed_distance_hit_fu_291 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index,
        ap_return => grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return,
        ap_rst => ap_rst);

    tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => ap_const_lv3_2,
        ap_return => tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return,
        ap_rst => ap_rst);

    tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => ap_const_lv3_3,
        ap_return => tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return,
        ap_rst => ap_rst);

    tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => ap_const_lv3_4,
        ap_return => tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return,
        ap_rst => ap_rst);

    tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => ap_const_lv3_5,
        ap_return => tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return,
        ap_rst => ap_rst);

    tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
    port map (
        ap_ready => tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_ready,
        cell_val => trunc_ln521_fu_345_p1,
        return_index => ap_const_lv3_6,
        ap_return => tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return,
        ap_rst => ap_rst);





    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;

    ap_phi_reg_pp0_iter1_result_1_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_fu_384_p2 = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln541_2_fu_701_p2))) then 
                    ap_phi_reg_pp0_iter1_result_1_reg_262 <= ap_const_lv16_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_result_1_reg_262 <= ap_phi_reg_pp0_iter0_result_1_reg_262;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter1_result_3_reg_194_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_fu_384_p2 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln556_1_fu_414_p2))) then 
                    ap_phi_reg_pp0_iter1_result_3_reg_194 <= ap_const_lv8_0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter1_result_3_reg_194 <= ap_phi_reg_pp0_iter0_result_3_reg_194;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter2_result_1_reg_262_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_reg_1293 = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln541_2_reg_1360))) then 
                    ap_phi_reg_pp0_iter2_result_1_reg_262 <= low16_1_reg_1364;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter2_result_1_reg_262 <= ap_phi_reg_pp0_iter1_result_1_reg_262;
                end if;
            end if; 
        end if;
    end process;

    result_12_reg_224_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_reg_1293_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln556_7_reg_1324_pp0_iter1_reg))) then 
                    result_12_reg_224 <= zext_ln533_3_fu_857_p1;
                elsif (((icmp_ln534_reg_1293_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln556_7_reg_1324_pp0_iter1_reg))) then 
                    result_12_reg_224 <= result_9_fu_893_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    result_12_reg_224 <= ap_phi_reg_pp0_iter2_result_12_reg_224;
                end if;
            end if; 
        end if;
    end process;

    result_16_reg_243_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_reg_1293_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln556_11_reg_1342_pp0_iter2_reg))) then 
                    result_16_reg_243 <= zext_ln533_5_fu_946_p1;
                elsif (((icmp_ln534_reg_1293_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln556_11_reg_1342_pp0_iter2_reg))) then 
                    result_16_reg_243 <= result_15_fu_982_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    result_16_reg_243 <= ap_phi_reg_pp0_iter3_result_16_reg_243;
                end if;
            end if; 
        end if;
    end process;

    result_6_reg_205_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                if (((icmp_ln534_reg_1293 = ap_const_lv1_0) and (ap_const_lv1_0 = and_ln556_3_reg_1306))) then 
                    result_6_reg_205 <= zext_ln533_1_fu_768_p1;
                elsif (((icmp_ln534_reg_1293 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln556_3_reg_1306))) then 
                    result_6_reg_205 <= result_5_fu_804_p3;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    result_6_reg_205 <= ap_phi_reg_pp0_iter1_result_6_reg_205;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce_reg))) then
                and_ln541_2_reg_1360 <= and_ln541_2_fu_701_p2;
                and_ln541_5_reg_1369 <= and_ln541_5_fu_758_p2;
                and_ln541_5_reg_1369_pp0_iter1_reg <= and_ln541_5_reg_1369;
                and_ln541_5_reg_1369_pp0_iter2_reg <= and_ln541_5_reg_1369_pp0_iter1_reg;
                and_ln541_5_reg_1369_pp0_iter3_reg <= and_ln541_5_reg_1369_pp0_iter2_reg;
                and_ln541_5_reg_1369_pp0_iter4_reg <= and_ln541_5_reg_1369_pp0_iter3_reg;
                and_ln556_11_reg_1342 <= and_ln556_11_fu_606_p2;
                and_ln556_11_reg_1342_pp0_iter1_reg <= and_ln556_11_reg_1342;
                and_ln556_11_reg_1342_pp0_iter2_reg <= and_ln556_11_reg_1342_pp0_iter1_reg;
                and_ln556_13_reg_1351 <= and_ln556_13_fu_638_p2;
                and_ln556_13_reg_1351_pp0_iter1_reg <= and_ln556_13_reg_1351;
                and_ln556_13_reg_1351_pp0_iter2_reg <= and_ln556_13_reg_1351_pp0_iter1_reg;
                and_ln556_13_reg_1351_pp0_iter3_reg <= and_ln556_13_reg_1351_pp0_iter2_reg;
                and_ln556_1_reg_1297 <= and_ln556_1_fu_414_p2;
                and_ln556_3_reg_1306 <= and_ln556_3_fu_474_p2;
                and_ln556_5_reg_1315 <= and_ln556_5_fu_506_p2;
                and_ln556_5_reg_1315_pp0_iter1_reg <= and_ln556_5_reg_1315;
                and_ln556_7_reg_1324 <= and_ln556_7_fu_542_p2;
                and_ln556_7_reg_1324_pp0_iter1_reg <= and_ln556_7_reg_1324;
                and_ln556_9_reg_1333 <= and_ln556_9_fu_574_p2;
                and_ln556_9_reg_1333_pp0_iter1_reg <= and_ln556_9_reg_1333;
                and_ln556_9_reg_1333_pp0_iter2_reg <= and_ln556_9_reg_1333_pp0_iter1_reg;
                ap_phi_reg_pp0_iter3_result_1_reg_262 <= ap_phi_reg_pp0_iter2_result_1_reg_262;
                ap_phi_reg_pp0_iter4_result_1_reg_262 <= ap_phi_reg_pp0_iter3_result_1_reg_262;
                ap_phi_reg_pp0_iter5_result_1_reg_262 <= ap_phi_reg_pp0_iter4_result_1_reg_262;
                blank_reg_1282 <= ordered_cell_val_int_reg(351 downto 351);
                blank_reg_1282_pp0_iter1_reg <= blank_reg_1282;
                blank_reg_1282_pp0_iter2_reg <= blank_reg_1282_pp0_iter1_reg;
                blank_reg_1282_pp0_iter3_reg <= blank_reg_1282_pp0_iter2_reg;
                icmp_ln534_reg_1293 <= icmp_ln534_fu_384_p2;
                icmp_ln534_reg_1293_pp0_iter1_reg <= icmp_ln534_reg_1293;
                icmp_ln534_reg_1293_pp0_iter2_reg <= icmp_ln534_reg_1293_pp0_iter1_reg;
                icmp_ln534_reg_1293_pp0_iter3_reg <= icmp_ln534_reg_1293_pp0_iter2_reg;
                icmp_ln534_reg_1293_pp0_iter4_reg <= icmp_ln534_reg_1293_pp0_iter3_reg;
                line_faulted_read_reg_1265 <= line_faulted_int_reg;
                line_faulted_read_reg_1265_pp0_iter1_reg <= line_faulted_read_reg_1265;
                line_faulted_read_reg_1265_pp0_iter2_reg <= line_faulted_read_reg_1265_pp0_iter1_reg;
                line_faulted_read_reg_1265_pp0_iter3_reg <= line_faulted_read_reg_1265_pp0_iter2_reg;
                line_faulted_read_reg_1265_pp0_iter4_reg <= line_faulted_read_reg_1265_pp0_iter3_reg;
                low16_1_reg_1364 <= low16_1_fu_707_p1;
                low16_reg_1373 <= low16_fu_764_p1;
                low16_reg_1373_pp0_iter1_reg <= low16_reg_1373;
                low16_reg_1373_pp0_iter2_reg <= low16_reg_1373_pp0_iter1_reg;
                low16_reg_1373_pp0_iter3_reg <= low16_reg_1373_pp0_iter2_reg;
                low16_reg_1373_pp0_iter4_reg <= low16_reg_1373_pp0_iter3_reg;
                ordered_cell_val_read_reg_1270 <= ordered_cell_val_int_reg;
                ordered_cell_val_read_reg_1270_pp0_iter1_reg <= ordered_cell_val_read_reg_1270;
                ordered_cell_val_read_reg_1270_pp0_iter2_reg <= ordered_cell_val_read_reg_1270_pp0_iter1_reg;
                ordered_cell_val_read_reg_1270_pp0_iter3_reg <= ordered_cell_val_read_reg_1270_pp0_iter2_reg;
                ordered_cell_val_read_reg_1270_pp0_iter4_reg <= ordered_cell_val_read_reg_1270_pp0_iter3_reg;
                result_24_reg_1393 <= result_24_fu_1140_p3;
                    result_2_reg_1301(0) <= result_2_fu_428_p3(0);
                select_ln561_1_reg_1378 <= select_ln561_1_fu_837_p3;
                select_ln561_3_reg_1383 <= select_ln561_3_fu_926_p3;
                select_ln561_5_reg_1388 <= select_ln561_5_fu_1015_p3;
                tmp_52_reg_1310 <= grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return(16 downto 16);
                tmp_53_reg_1319 <= tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return(16 downto 16);
                tmp_57_reg_1328 <= tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return(16 downto 16);
                tmp_57_reg_1328_pp0_iter1_reg <= tmp_57_reg_1328;
                tmp_59_reg_1337 <= tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return(16 downto 16);
                tmp_59_reg_1337_pp0_iter1_reg <= tmp_59_reg_1337;
                tmp_61_reg_1346 <= tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return(16 downto 16);
                tmp_61_reg_1346_pp0_iter1_reg <= tmp_61_reg_1346;
                tmp_61_reg_1346_pp0_iter2_reg <= tmp_61_reg_1346_pp0_iter1_reg;
                tmp_63_reg_1355 <= tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return(16 downto 16);
                tmp_63_reg_1355_pp0_iter1_reg <= tmp_63_reg_1355;
                tmp_63_reg_1355_pp0_iter2_reg <= tmp_63_reg_1355_pp0_iter1_reg;
                valid_return_count_reg_1287 <= ordered_cell_val_int_reg(11 downto 9);
                valid_return_count_reg_1287_pp0_iter1_reg <= valid_return_count_reg_1287;
                valid_return_count_reg_1287_pp0_iter2_reg <= valid_return_count_reg_1287_pp0_iter1_reg;
                valid_return_count_reg_1287_pp0_iter3_reg <= valid_return_count_reg_1287_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_int_reg <= ap_phi_mux_result_11_phi_fu_276_p6;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce)) then
                line_faulted_int_reg <= line_faulted;
                local_word_index_int_reg <= local_word_index;
                ordered_cell_val_int_reg <= ordered_cell_val;
                profile_cell_word_count_val_int_reg <= profile_cell_word_count_val;
                profile_serialized_return_slots_val_int_reg <= profile_serialized_return_slots_val;
            end if;
        end if;
    end process;
    result_2_reg_1301(7 downto 1) <= "1000000";
    and_ln541_1_fu_695_p2 <= (xor_ln556_fu_390_p2 and icmp_ln541_fu_671_p2);
    and_ln541_2_fu_701_p2 <= (and_ln541_fu_689_p2 and and_ln541_1_fu_695_p2);
    and_ln541_3_fu_746_p2 <= (icmp_ln543_1_fu_740_p2 and icmp_ln542_1_fu_734_p2);
    and_ln541_4_fu_752_p2 <= (xor_ln556_fu_390_p2 and icmp_ln541_1_fu_728_p2);
    and_ln541_5_fu_758_p2 <= (and_ln541_4_fu_752_p2 and and_ln541_3_fu_746_p2);
    and_ln541_fu_689_p2 <= (icmp_ln543_fu_683_p2 and icmp_ln542_fu_677_p2);
    and_ln556_10_fu_600_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_4_fu_594_p2);
    and_ln556_11_fu_606_p2 <= (icmp_ln557_4_fu_588_p2 and and_ln556_10_fu_600_p2);
    and_ln556_12_fu_632_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_5_fu_626_p2);
    and_ln556_13_fu_638_p2 <= (icmp_ln557_5_fu_620_p2 and and_ln556_12_fu_632_p2);
    and_ln556_1_fu_414_p2 <= (icmp_ln557_fu_396_p2 and and_ln556_fu_408_p2);
    and_ln556_2_fu_468_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_1_fu_462_p2);
    and_ln556_3_fu_474_p2 <= (icmp_ln557_1_fu_446_p2 and and_ln556_2_fu_468_p2);
    and_ln556_4_fu_500_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_2_fu_494_p2);
    and_ln556_5_fu_506_p2 <= (icmp_ln557_2_fu_488_p2 and and_ln556_4_fu_500_p2);
    and_ln556_6_fu_536_p2 <= (xor_ln556_fu_390_p2 and tmp_56_fu_528_p3);
    and_ln556_7_fu_542_p2 <= (tmp_55_fu_520_p3 and and_ln556_6_fu_536_p2);
    and_ln556_8_fu_568_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_3_fu_562_p2);
    and_ln556_9_fu_574_p2 <= (icmp_ln557_3_fu_556_p2 and and_ln556_8_fu_568_p2);
    and_ln556_fu_408_p2 <= (xor_ln556_fu_390_p2 and icmp_ln558_fu_402_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp28 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp37 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp43 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp49 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp55 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp61 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp67 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp79 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_ignoreCallOp89 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_phi_mux_result_11_phi_fu_276_p6_assign_proc : process(icmp_ln534_reg_1293_pp0_iter4_reg, and_ln541_5_reg_1369_pp0_iter4_reg, result_29_fu_1241_p4, ap_phi_reg_pp0_iter5_result_11_reg_273, result_4_fu_1257_p3, zext_ln533_fu_1252_p1)
    begin
        if (((icmp_ln534_reg_1293_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_lv1_0 = and_ln541_5_reg_1369_pp0_iter4_reg))) then 
            ap_phi_mux_result_11_phi_fu_276_p6 <= zext_ln533_fu_1252_p1;
        elsif (((icmp_ln534_reg_1293_pp0_iter4_reg = ap_const_lv1_1) and (ap_const_lv1_1 = and_ln541_5_reg_1369_pp0_iter4_reg))) then 
            ap_phi_mux_result_11_phi_fu_276_p6 <= result_4_fu_1257_p3;
        elsif ((icmp_ln534_reg_1293_pp0_iter4_reg = ap_const_lv1_0)) then 
            ap_phi_mux_result_11_phi_fu_276_p6 <= result_29_fu_1241_p4;
        else 
            ap_phi_mux_result_11_phi_fu_276_p6 <= ap_phi_reg_pp0_iter5_result_11_reg_273;
        end if; 
    end process;


    ap_phi_mux_result_12_phi_fu_227_p4_assign_proc : process(icmp_ln534_reg_1293_pp0_iter1_reg, and_ln556_7_reg_1324_pp0_iter1_reg, result_9_fu_893_p3, ap_phi_reg_pp0_iter2_result_12_reg_224, zext_ln533_3_fu_857_p1)
    begin
        if ((icmp_ln534_reg_1293_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_7_reg_1324_pp0_iter1_reg)) then 
                ap_phi_mux_result_12_phi_fu_227_p4 <= zext_ln533_3_fu_857_p1;
            elsif ((ap_const_lv1_1 = and_ln556_7_reg_1324_pp0_iter1_reg)) then 
                ap_phi_mux_result_12_phi_fu_227_p4 <= result_9_fu_893_p3;
            else 
                ap_phi_mux_result_12_phi_fu_227_p4 <= ap_phi_reg_pp0_iter2_result_12_reg_224;
            end if;
        else 
            ap_phi_mux_result_12_phi_fu_227_p4 <= ap_phi_reg_pp0_iter2_result_12_reg_224;
        end if; 
    end process;


    ap_phi_mux_result_14_phi_fu_237_p4_assign_proc : process(icmp_ln534_reg_1293_pp0_iter2_reg, and_ln556_9_reg_1333_pp0_iter2_reg, result_13_fu_938_p3, ap_phi_reg_pp0_iter3_result_14_reg_234, zext_ln533_4_fu_933_p1)
    begin
        if ((icmp_ln534_reg_1293_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_9_reg_1333_pp0_iter2_reg)) then 
                ap_phi_mux_result_14_phi_fu_237_p4 <= zext_ln533_4_fu_933_p1;
            elsif ((ap_const_lv1_1 = and_ln556_9_reg_1333_pp0_iter2_reg)) then 
                ap_phi_mux_result_14_phi_fu_237_p4 <= result_13_fu_938_p3;
            else 
                ap_phi_mux_result_14_phi_fu_237_p4 <= ap_phi_reg_pp0_iter3_result_14_reg_234;
            end if;
        else 
            ap_phi_mux_result_14_phi_fu_237_p4 <= ap_phi_reg_pp0_iter3_result_14_reg_234;
        end if; 
    end process;


    ap_phi_mux_result_16_phi_fu_246_p4_assign_proc : process(icmp_ln534_reg_1293_pp0_iter2_reg, and_ln556_11_reg_1342_pp0_iter2_reg, result_15_fu_982_p3, ap_phi_reg_pp0_iter3_result_16_reg_243, zext_ln533_5_fu_946_p1)
    begin
        if ((icmp_ln534_reg_1293_pp0_iter2_reg = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_11_reg_1342_pp0_iter2_reg)) then 
                ap_phi_mux_result_16_phi_fu_246_p4 <= zext_ln533_5_fu_946_p1;
            elsif ((ap_const_lv1_1 = and_ln556_11_reg_1342_pp0_iter2_reg)) then 
                ap_phi_mux_result_16_phi_fu_246_p4 <= result_15_fu_982_p3;
            else 
                ap_phi_mux_result_16_phi_fu_246_p4 <= ap_phi_reg_pp0_iter3_result_16_reg_243;
            end if;
        else 
            ap_phi_mux_result_16_phi_fu_246_p4 <= ap_phi_reg_pp0_iter3_result_16_reg_243;
        end if; 
    end process;


    ap_phi_mux_result_18_phi_fu_256_p4_assign_proc : process(icmp_ln534_reg_1293_pp0_iter3_reg, and_ln556_13_reg_1351_pp0_iter3_reg, result_17_fu_1027_p3, ap_phi_reg_pp0_iter4_result_18_reg_253, zext_ln533_6_fu_1022_p1)
    begin
        if ((icmp_ln534_reg_1293_pp0_iter3_reg = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_13_reg_1351_pp0_iter3_reg)) then 
                ap_phi_mux_result_18_phi_fu_256_p4 <= zext_ln533_6_fu_1022_p1;
            elsif ((ap_const_lv1_1 = and_ln556_13_reg_1351_pp0_iter3_reg)) then 
                ap_phi_mux_result_18_phi_fu_256_p4 <= result_17_fu_1027_p3;
            else 
                ap_phi_mux_result_18_phi_fu_256_p4 <= ap_phi_reg_pp0_iter4_result_18_reg_253;
            end if;
        else 
            ap_phi_mux_result_18_phi_fu_256_p4 <= ap_phi_reg_pp0_iter4_result_18_reg_253;
        end if; 
    end process;


    ap_phi_mux_result_3_phi_fu_198_p4_assign_proc : process(icmp_ln534_reg_1293, and_ln556_1_reg_1297, result_2_reg_1301, ap_phi_reg_pp0_iter1_result_3_reg_194)
    begin
        if (((icmp_ln534_reg_1293 = ap_const_lv1_0) and (ap_const_lv1_1 = and_ln556_1_reg_1297))) then 
            ap_phi_mux_result_3_phi_fu_198_p4 <= result_2_reg_1301;
        else 
            ap_phi_mux_result_3_phi_fu_198_p4 <= ap_phi_reg_pp0_iter1_result_3_reg_194;
        end if; 
    end process;


    ap_phi_mux_result_6_phi_fu_208_p4_assign_proc : process(icmp_ln534_reg_1293, and_ln556_3_reg_1306, result_5_fu_804_p3, ap_phi_reg_pp0_iter1_result_6_reg_205, zext_ln533_1_fu_768_p1)
    begin
        if ((icmp_ln534_reg_1293 = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_3_reg_1306)) then 
                ap_phi_mux_result_6_phi_fu_208_p4 <= zext_ln533_1_fu_768_p1;
            elsif ((ap_const_lv1_1 = and_ln556_3_reg_1306)) then 
                ap_phi_mux_result_6_phi_fu_208_p4 <= result_5_fu_804_p3;
            else 
                ap_phi_mux_result_6_phi_fu_208_p4 <= ap_phi_reg_pp0_iter1_result_6_reg_205;
            end if;
        else 
            ap_phi_mux_result_6_phi_fu_208_p4 <= ap_phi_reg_pp0_iter1_result_6_reg_205;
        end if; 
    end process;


    ap_phi_mux_result_8_phi_fu_218_p4_assign_proc : process(icmp_ln534_reg_1293_pp0_iter1_reg, and_ln556_5_reg_1315_pp0_iter1_reg, result_7_fu_849_p3, ap_phi_reg_pp0_iter2_result_8_reg_215, zext_ln533_2_fu_844_p1)
    begin
        if ((icmp_ln534_reg_1293_pp0_iter1_reg = ap_const_lv1_0)) then
            if ((ap_const_lv1_0 = and_ln556_5_reg_1315_pp0_iter1_reg)) then 
                ap_phi_mux_result_8_phi_fu_218_p4 <= zext_ln533_2_fu_844_p1;
            elsif ((ap_const_lv1_1 = and_ln556_5_reg_1315_pp0_iter1_reg)) then 
                ap_phi_mux_result_8_phi_fu_218_p4 <= result_7_fu_849_p3;
            else 
                ap_phi_mux_result_8_phi_fu_218_p4 <= ap_phi_reg_pp0_iter2_result_8_reg_215;
            end if;
        else 
            ap_phi_mux_result_8_phi_fu_218_p4 <= ap_phi_reg_pp0_iter2_result_8_reg_215;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_result_1_reg_262 <= "XXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_result_3_reg_194 <= "XXXXXXXX";
    ap_phi_reg_pp0_iter1_result_6_reg_205 <= "XXXXXXXXX";
    ap_phi_reg_pp0_iter2_result_12_reg_224 <= "XXXXXXXXXXX";
    ap_phi_reg_pp0_iter2_result_8_reg_215 <= "XXXXXXXXXX";
    ap_phi_reg_pp0_iter3_result_14_reg_234 <= "XXXXXXXXXXXX";
    ap_phi_reg_pp0_iter3_result_16_reg_243 <= "XXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter4_result_18_reg_253 <= "XXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter5_result_11_reg_273 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_return_assign_proc : process(ap_phi_mux_result_11_phi_fu_276_p6, ap_ce_reg, ap_return_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return <= ap_return_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return <= ap_phi_mux_result_11_phi_fu_276_p6;
        else 
            ap_return <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    blank_fu_356_p3 <= ordered_cell_val_int_reg(351 downto 351);
    first_return_fu_652_p3 <= (local_word_index_int_reg & ap_const_lv1_0);

    grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index_assign_proc : process(icmp_ln534_fu_384_p2, and_ln556_1_fu_414_p2, and_ln541_2_fu_701_p2, ap_block_pp0_stage0_ignoreCallOp28, ap_block_pp0_stage0_ignoreCallOp79, shl_ln535_fu_664_p2)
    begin
        if (((icmp_ln534_fu_384_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_ignoreCallOp79) and (ap_const_lv1_1 = and_ln541_2_fu_701_p2))) then 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index <= shl_ln535_fu_664_p2;
        elsif (((icmp_ln534_fu_384_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_ignoreCallOp28) and (ap_const_lv1_1 = and_ln556_1_fu_414_p2))) then 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index <= ap_const_lv3_0;
        else 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index <= "XXX";
        end if; 
    end process;


    grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index_assign_proc : process(icmp_ln534_fu_384_p2, and_ln556_3_fu_474_p2, and_ln541_5_fu_758_p2, ap_block_pp0_stage0_ignoreCallOp37, ap_block_pp0_stage0_ignoreCallOp89, or_ln_fu_719_p3)
    begin
        if (((icmp_ln534_fu_384_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_ignoreCallOp89) and (ap_const_lv1_1 = and_ln541_5_fu_758_p2))) then 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index <= or_ln_fu_719_p3;
        elsif (((icmp_ln534_fu_384_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_ignoreCallOp37) and (ap_const_lv1_1 = and_ln556_3_fu_474_p2))) then 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index <= ap_const_lv3_1;
        else 
            grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index <= "XXX";
        end if; 
    end process;

    hit_word_count_fu_378_p2 <= std_logic_vector(unsigned(zext_ln519_1_fu_337_p1) + unsigned(ap_const_lv4_F));
    icmp_ln534_fu_384_p2 <= "1" when (unsigned(hit_word_count_fu_378_p2) > unsigned(zext_ln519_fu_333_p1)) else "0";
    icmp_ln541_1_fu_728_p2 <= "1" when (unsigned(return_index_1_fu_711_p3) < unsigned(zext_ln527_fu_374_p1)) else "0";
    icmp_ln541_fu_671_p2 <= "1" when (unsigned(first_return_fu_652_p3) < unsigned(zext_ln527_fu_374_p1)) else "0";
    icmp_ln542_1_fu_734_p2 <= "1" when (unsigned(return_index_1_fu_711_p3) < unsigned(zext_ln519_2_fu_341_p1)) else "0";
    icmp_ln542_fu_677_p2 <= "1" when (unsigned(first_return_fu_652_p3) < unsigned(zext_ln519_2_fu_341_p1)) else "0";
    icmp_ln543_1_fu_740_p2 <= "1" when (unsigned(return_index_1_fu_711_p3) < unsigned(ap_const_lv4_7)) else "0";
    icmp_ln543_fu_683_p2 <= "1" when (unsigned(first_return_fu_652_p3) < unsigned(ap_const_lv4_7)) else "0";
    icmp_ln557_1_fu_446_p2 <= "0" when (tmp_50_fu_436_p4 = ap_const_lv2_0) else "1";
    icmp_ln557_2_fu_488_p2 <= "1" when (unsigned(valid_return_count_fu_364_p4) > unsigned(ap_const_lv3_2)) else "0";
    icmp_ln557_3_fu_556_p2 <= "1" when (unsigned(valid_return_count_fu_364_p4) > unsigned(ap_const_lv3_4)) else "0";
    icmp_ln557_4_fu_588_p2 <= "1" when (unsigned(valid_return_count_fu_364_p4) > unsigned(ap_const_lv3_5)) else "0";
    icmp_ln557_5_fu_620_p2 <= "1" when (valid_return_count_fu_364_p4 = ap_const_lv3_7) else "0";
    icmp_ln557_fu_396_p2 <= "0" when (valid_return_count_fu_364_p4 = ap_const_lv3_0) else "1";
    icmp_ln558_1_fu_462_p2 <= "0" when (tmp_51_fu_452_p4 = ap_const_lv2_0) else "1";
    icmp_ln558_2_fu_494_p2 <= "1" when (unsigned(profile_serialized_return_slots_val_int_reg) > unsigned(ap_const_lv3_2)) else "0";
    icmp_ln558_3_fu_562_p2 <= "1" when (unsigned(profile_serialized_return_slots_val_int_reg) > unsigned(ap_const_lv3_4)) else "0";
    icmp_ln558_4_fu_594_p2 <= "1" when (unsigned(profile_serialized_return_slots_val_int_reg) > unsigned(ap_const_lv3_5)) else "0";
    icmp_ln558_5_fu_626_p2 <= "1" when (profile_serialized_return_slots_val_int_reg = ap_const_lv3_7) else "0";
    icmp_ln558_fu_402_p2 <= "0" when (profile_serialized_return_slots_val_int_reg = ap_const_lv3_0) else "1";
    low16_1_fu_707_p1 <= grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return(16 - 1 downto 0);
    low16_fu_764_p1 <= grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return(16 - 1 downto 0);
    or_ln1_fu_787_p4 <= ((tmp_49_fu_773_p4 & ap_const_lv1_1) & trunc_ln563_fu_783_p1);
    or_ln2_fu_1053_p4 <= ((ap_const_lv1_1 & valid_return_count_reg_1287_pp0_iter3_reg) & ap_phi_mux_result_18_phi_fu_256_p4);
    or_ln3_fu_1132_p3 <= (ap_const_lv1_1 & result_23_fu_1114_p3);
    or_ln40_fu_1219_p2 <= (tmp_69_fu_1204_p3 or line_faulted_read_reg_1265_pp0_iter4_reg);
    or_ln4_fu_1184_p3 <= (ap_const_lv1_1 & result_26_fu_1165_p3);
    or_ln563_1_fu_827_p4 <= ((tmp_54_fu_813_p4 & ap_const_lv1_1) & trunc_ln563_1_fu_823_p1);
    or_ln563_2_fu_876_p4 <= ((tmp_58_fu_862_p4 & ap_const_lv1_1) & trunc_ln563_2_fu_872_p1);
    or_ln563_3_fu_916_p4 <= ((tmp_60_fu_902_p4 & ap_const_lv1_1) & trunc_ln563_3_fu_912_p1);
    or_ln563_4_fu_965_p4 <= ((tmp_62_fu_951_p4 & ap_const_lv1_1) & trunc_ln563_4_fu_961_p1);
    or_ln563_5_fu_1005_p4 <= ((tmp_64_fu_991_p4 & ap_const_lv1_1) & trunc_ln563_5_fu_1001_p1);
    or_ln_fu_719_p3 <= (trunc_ln535_fu_660_p1 & ap_const_lv1_1);
    result_10_fu_1224_p3 <= 
        result_28_fu_1211_p3 when (or_ln40_fu_1219_p2(0) = '1') else 
        zext_ln533_12_fu_1200_p1;
    result_13_fu_938_p3 <= (ap_const_lv1_1 & select_ln561_3_reg_1383);
    result_15_fu_982_p3 <= (ap_const_lv1_1 & select_ln561_4_fu_975_p3);
    result_17_fu_1027_p3 <= (ap_const_lv1_1 & select_ln561_5_reg_1388);
    result_19_fu_1035_p3 <= (valid_return_count_reg_1287_pp0_iter3_reg & ap_phi_mux_result_18_phi_fu_256_p4);
    result_20_fu_1062_p3 <= 
        or_ln2_fu_1053_p4 when (tmp_65_fu_1046_p3(0) = '1') else 
        zext_ln533_7_fu_1042_p1;
    result_21_fu_1088_p4 <= ((tmp_1_fu_1070_p4 & tmp_2_fu_1079_p4) & result_20_fu_1062_p3);
    result_22_fu_1102_p5 <= (((ap_const_lv1_1 & tmp_1_fu_1070_p4) & tmp_2_fu_1079_p4) & result_20_fu_1062_p3);
    result_23_fu_1114_p3 <= 
        result_22_fu_1102_p5 when (blank_reg_1282_pp0_iter3_reg(0) = '1') else 
        zext_ln533_8_fu_1098_p1;
    result_24_fu_1140_p3 <= 
        or_ln3_fu_1132_p3 when (tmp_66_fu_1125_p3(0) = '1') else 
        zext_ln533_9_fu_1121_p1;
    result_25_fu_1158_p3 <= (ap_const_lv1_1 & result_24_reg_1393);
    result_26_fu_1165_p3 <= 
        result_25_fu_1158_p3 when (tmp_67_fu_1151_p3(0) = '1') else 
        zext_ln533_10_fu_1148_p1;
    result_27_fu_1192_p3 <= 
        or_ln4_fu_1184_p3 when (tmp_68_fu_1177_p3(0) = '1') else 
        zext_ln533_11_fu_1173_p1;
    result_28_fu_1211_p3 <= (ap_const_lv1_1 & result_27_fu_1192_p3);
    result_29_fu_1241_p4 <= ((ap_const_lv1_1 & tmp_3_fu_1232_p4) & result_10_fu_1224_p3);
    result_2_fu_428_p3 <= 
        ap_const_lv8_81 when (tmp_fu_420_p3(0) = '1') else 
        ap_const_lv8_80;
    result_4_fu_1257_p3 <= (low16_reg_1373_pp0_iter4_reg & ap_phi_reg_pp0_iter5_result_1_reg_262);
    result_5_fu_804_p3 <= (ap_const_lv1_1 & select_ln561_fu_797_p3);
    result_7_fu_849_p3 <= (ap_const_lv1_1 & select_ln561_1_reg_1378);
    result_9_fu_893_p3 <= (ap_const_lv1_1 & select_ln561_2_fu_886_p3);
    return_index_1_fu_711_p3 <= (local_word_index_int_reg & ap_const_lv1_1);
    select_ln561_1_fu_837_p3 <= 
        or_ln563_1_fu_827_p4 when (tmp_53_reg_1319(0) = '1') else 
        ap_phi_mux_result_6_phi_fu_208_p4;
    select_ln561_2_fu_886_p3 <= 
        or_ln563_2_fu_876_p4 when (tmp_57_reg_1328_pp0_iter1_reg(0) = '1') else 
        ap_phi_mux_result_8_phi_fu_218_p4;
    select_ln561_3_fu_926_p3 <= 
        or_ln563_3_fu_916_p4 when (tmp_59_reg_1337_pp0_iter1_reg(0) = '1') else 
        ap_phi_mux_result_12_phi_fu_227_p4;
    select_ln561_4_fu_975_p3 <= 
        or_ln563_4_fu_965_p4 when (tmp_61_reg_1346_pp0_iter2_reg(0) = '1') else 
        ap_phi_mux_result_14_phi_fu_237_p4;
    select_ln561_5_fu_1015_p3 <= 
        or_ln563_5_fu_1005_p4 when (tmp_63_reg_1355_pp0_iter2_reg(0) = '1') else 
        ap_phi_mux_result_16_phi_fu_246_p4;
    select_ln561_fu_797_p3 <= 
        or_ln1_fu_787_p4 when (tmp_52_reg_1310(0) = '1') else 
        ap_phi_mux_result_3_phi_fu_198_p4;
    shl_ln535_fu_664_p2 <= std_logic_vector(shift_left(unsigned(local_word_index_int_reg),to_integer(unsigned('0' & ap_const_lv3_1(3-1 downto 0)))));
    tmp_1_fu_1070_p4 <= ordered_cell_val_read_reg_1270_pp0_iter3_reg(7 downto 5);
    tmp_2_fu_1079_p4 <= ordered_cell_val_read_reg_1270_pp0_iter3_reg(3 downto 2);
    tmp_3_fu_1232_p4 <= ordered_cell_val_read_reg_1270_pp0_iter4_reg(140 downto 138);
    tmp_49_fu_773_p4 <= ap_phi_mux_result_3_phi_fu_198_p4(7 downto 2);
    tmp_50_fu_436_p4 <= ordered_cell_val_int_reg(11 downto 10);
    tmp_51_fu_452_p4 <= profile_serialized_return_slots_val_int_reg(2 downto 1);
    tmp_54_fu_813_p4 <= ap_phi_mux_result_6_phi_fu_208_p4(8 downto 3);
    tmp_55_fu_520_p3 <= ordered_cell_val_int_reg(11 downto 11);
    tmp_56_fu_528_p3 <= profile_serialized_return_slots_val_int_reg(2 downto 2);
    tmp_58_fu_862_p4 <= ap_phi_mux_result_8_phi_fu_218_p4(9 downto 4);
    tmp_60_fu_902_p4 <= ap_phi_mux_result_12_phi_fu_227_p4(10 downto 5);
    tmp_62_fu_951_p4 <= ap_phi_mux_result_14_phi_fu_237_p4(11 downto 6);
    tmp_64_fu_991_p4 <= ap_phi_mux_result_16_phi_fu_246_p4(12 downto 7);
    tmp_65_fu_1046_p3 <= ordered_cell_val_read_reg_1270_pp0_iter3_reg(8 downto 8);
    tmp_66_fu_1125_p3 <= ordered_cell_val_read_reg_1270_pp0_iter3_reg(136 downto 136);
    tmp_67_fu_1151_p3 <= ordered_cell_val_read_reg_1270_pp0_iter4_reg(134 downto 134);
    tmp_68_fu_1177_p3 <= ordered_cell_val_read_reg_1270_pp0_iter4_reg(135 downto 135);
    tmp_69_fu_1204_p3 <= ordered_cell_val_read_reg_1270_pp0_iter4_reg(137 downto 137);
    tmp_fu_420_p3 <= grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return(16 downto 16);
    trunc_ln521_fu_345_p1 <= ordered_cell_val_int_reg(134 - 1 downto 0);
    trunc_ln535_fu_660_p1 <= local_word_index_int_reg(2 - 1 downto 0);
    trunc_ln563_1_fu_823_p1 <= ap_phi_mux_result_6_phi_fu_208_p4(2 - 1 downto 0);
    trunc_ln563_2_fu_872_p1 <= ap_phi_mux_result_8_phi_fu_218_p4(3 - 1 downto 0);
    trunc_ln563_3_fu_912_p1 <= ap_phi_mux_result_12_phi_fu_227_p4(4 - 1 downto 0);
    trunc_ln563_4_fu_961_p1 <= ap_phi_mux_result_14_phi_fu_237_p4(5 - 1 downto 0);
    trunc_ln563_5_fu_1001_p1 <= ap_phi_mux_result_16_phi_fu_246_p4(6 - 1 downto 0);
    trunc_ln563_fu_783_p1 <= ap_phi_mux_result_3_phi_fu_198_p4(1 - 1 downto 0);
    valid_return_count_fu_364_p4 <= ordered_cell_val_int_reg(11 downto 9);
    xor_ln556_fu_390_p2 <= (blank_fu_356_p3 xor ap_const_lv1_1);
    zext_ln519_1_fu_337_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(profile_cell_word_count_val_int_reg),4));
    zext_ln519_2_fu_341_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(profile_serialized_return_slots_val_int_reg),4));
    zext_ln519_fu_333_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(local_word_index_int_reg),4));
    zext_ln527_fu_374_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(valid_return_count_fu_364_p4),4));
    zext_ln533_10_fu_1148_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_24_reg_1393),26));
    zext_ln533_11_fu_1173_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_26_fu_1165_p3),27));
    zext_ln533_12_fu_1200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_27_fu_1192_p3),28));
    zext_ln533_1_fu_768_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_result_3_phi_fu_198_p4),9));
    zext_ln533_2_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_6_reg_205),10));
    zext_ln533_3_fu_857_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_result_8_phi_fu_218_p4),11));
    zext_ln533_4_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_12_reg_224),12));
    zext_ln533_5_fu_946_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_result_14_phi_fu_237_p4),13));
    zext_ln533_6_fu_1022_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_16_reg_243),14));
    zext_ln533_7_fu_1042_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_19_fu_1035_p3),18));
    zext_ln533_8_fu_1098_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_21_fu_1088_p4),24));
    zext_ln533_9_fu_1121_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_23_fu_1114_p3),25));
    zext_ln533_fu_1252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter5_result_1_reg_262),32));
end behav;
