-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    canonical_line_word_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    canonical_line_word_out_TVALID : OUT STD_LOGIC;
    canonical_line_word_out_TREADY : IN STD_LOGIC;
    context_val : IN STD_LOGIC_VECTOR (37 downto 0);
    profile_planned_shot_columns_val : IN STD_LOGIC_VECTOR (15 downto 0);
    profile_raw_line_words_val : IN STD_LOGIC_VECTOR (8 downto 0);
    line_faulted : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal shot_column_fu_82_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal shot_column_reg_131 : STD_LOGIC_VECTOR (15 downto 0);
    signal last_column_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal last_column_reg_137 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal first_column_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal first_column_reg_152 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_s_fu_118_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal result_s_reg_157 : STD_LOGIC_VECTOR (16 downto 0);
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_idle : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID : STD_LOGIC;
    signal grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal canonical_line_word_out_TDATA_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln473_fu_92_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal add_ln473_fu_96_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln473_1_fu_102_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        canonical_line_word_out_TREADY : IN STD_LOGIC;
        profile_raw_line_words_val : IN STD_LOGIC_VECTOR (8 downto 0);
        context_val : IN STD_LOGIC_VECTOR (37 downto 0);
        line_faulted : IN STD_LOGIC_VECTOR (0 downto 0);
        result_42 : IN STD_LOGIC_VECTOR (16 downto 0);
        last_column : IN STD_LOGIC_VECTOR (0 downto 0);
        first_column : IN STD_LOGIC_VECTOR (0 downto 0);
        canonical_line_word_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        canonical_line_word_out_TVALID : OUT STD_LOGIC );
    end component;



begin
    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68 : component gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start,
        ap_done => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done,
        ap_idle => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_idle,
        ap_ready => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready,
        canonical_line_word_out_TREADY => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY,
        profile_raw_line_words_val => profile_raw_line_words_val,
        context_val => context_val,
        line_faulted => line_faulted,
        result_42 => result_s_reg_157,
        last_column => last_column_reg_137,
        first_column => first_column_reg_152,
        canonical_line_word_out_TDATA => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA,
        canonical_line_word_out_TVALID => grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
                    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready = ap_const_logic_1)) then 
                    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                canonical_line_word_out_TDATA_reg <= grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                first_column_reg_152 <= first_column_fu_112_p2;
                    result_s_reg_157(15 downto 0) <= result_s_fu_118_p3(15 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                last_column_reg_137 <= last_column_fu_106_p2;
                shot_column_reg_131 <= context_val(35 downto 20);
            end if;
        end if;
    end process;
    result_s_reg_157(16) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln473_fu_96_p2 <= std_logic_vector(unsigned(zext_ln473_fu_92_p1) + unsigned(ap_const_lv17_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done)
    begin
        if ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done, ap_CS_fsm_state3)
    begin
        if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    canonical_line_word_out_TDATA_assign_proc : process(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA, grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID, ap_CS_fsm_state3, canonical_line_word_out_TDATA_reg)
    begin
        if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            canonical_line_word_out_TDATA <= grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA;
        else 
            canonical_line_word_out_TDATA <= canonical_line_word_out_TDATA_reg;
        end if; 
    end process;

    canonical_line_word_out_TVALID <= grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID;
    first_column_fu_112_p2 <= "1" when (shot_column_reg_131 = ap_const_lv16_0) else "0";
    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start <= grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg;
    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY <= (canonical_line_word_out_TREADY and ap_CS_fsm_state3);
    last_column_fu_106_p2 <= "1" when (add_ln473_fu_96_p2 = zext_ln473_1_fu_102_p1) else "0";
    result_s_fu_118_p3 <= (ap_const_lv1_1 & shot_column_reg_131);
    shot_column_fu_82_p4 <= context_val(35 downto 20);
    zext_ln473_1_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(profile_planned_shot_columns_val),17));
    zext_ln473_fu_92_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shot_column_fu_82_p4),17));
end behav;
