-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    canonical_line_word_out_TREADY : IN STD_LOGIC;
    profile_raw_line_words_val : IN STD_LOGIC_VECTOR (8 downto 0);
    context_val : IN STD_LOGIC_VECTOR (37 downto 0);
    line_faulted : IN STD_LOGIC_VECTOR (0 downto 0);
    result_42 : IN STD_LOGIC_VECTOR (16 downto 0);
    last_column : IN STD_LOGIC_VECTOR (0 downto 0);
    first_column : IN STD_LOGIC_VECTOR (0 downto 0);
    canonical_line_word_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    canonical_line_word_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_13 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010011";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln475_fu_161_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal canonical_line_word_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal word_index_3_reg_425 : STD_LOGIC_VECTOR (8 downto 0);
    signal line_end_fu_173_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_434 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln481_fu_189_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln481_reg_439 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_47_fu_331_p9 : STD_LOGIC_VECTOR (16 downto 0);
    signal result_47_reg_444 : STD_LOGIC_VECTOR (16 downto 0);
    signal word_index_fu_106 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln479_fu_167_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_word_index_3 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal tmp_fu_179_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_83_fu_199_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_84_fu_215_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_41_fu_223_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln40_fu_207_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal result_43_fu_231_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln406_fu_243_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal or_ln_fu_247_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln360_fu_239_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal result_44_fu_255_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal zext_ln423_fu_275_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_85_fu_267_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln8_fu_279_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln360_6_fu_263_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal result_45_fu_287_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal word_index_4_fu_195_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln377_fu_299_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln377_1_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln377_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln377_1_fu_317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_47_fu_331_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal result_47_fu_331_p7 : STD_LOGIC_VECTOR (16 downto 0);
    signal result_47_fu_331_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal xor_ln32_fu_364_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_start_fu_359_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln32_fu_369_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal sext_ln360_fu_356_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_fu_373_p12 : STD_LOGIC_VECTOR (58 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal result_47_fu_331_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_47_fu_331_p3 : STD_LOGIC_VECTOR (1 downto 0);
    signal result_47_fu_331_p5 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gpx_lane_word_formatter_hls_sparsemux_7_2_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (1 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (1 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (1 downto 0);
        din2_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        def : IN STD_LOGIC_VECTOR (16 downto 0);
        sel : IN STD_LOGIC_VECTOR (1 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component gpx_lane_word_formatter_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    sparsemux_7_2_17_1_1_U1 : component gpx_lane_word_formatter_hls_sparsemux_7_2_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10",
        din0_WIDTH => 17,
        CASE1 => "01",
        din1_WIDTH => 17,
        CASE2 => "00",
        din2_WIDTH => 17,
        def_WIDTH => 17,
        sel_WIDTH => 2,
        dout_WIDTH => 17)
    port map (
        din0 => result_42,
        din1 => result_47_fu_331_p4,
        din2 => ap_const_lv17_0,
        def => result_47_fu_331_p7,
        sel => result_47_fu_331_p8,
        dout => result_47_fu_331_p9);

    flow_control_loop_pipe_sequential_init_U : component gpx_lane_word_formatter_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    word_index_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln475_fu_161_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    word_index_fu_106 <= add_ln479_fu_167_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    word_index_fu_106 <= ap_const_lv9_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln481_reg_439 <= icmp_ln481_fu_189_p2;
                line_end_reg_434 <= line_end_fu_173_p2;
                result_47_reg_444 <= result_47_fu_331_p9;
                word_index_3_reg_425 <= ap_sig_allocacmp_word_index_3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln479_fu_167_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_word_index_3) + unsigned(ap_const_lv9_1));
    and_ln377_1_fu_317_p2 <= (icmp_ln481_fu_189_p2 and icmp_ln377_1_fu_311_p2);
    and_ln377_fu_305_p2 <= (icmp_ln481_fu_189_p2 and icmp_ln377_fu_299_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, canonical_line_word_out_TREADY)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((canonical_line_word_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, canonical_line_word_out_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((canonical_line_word_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, canonical_line_word_out_TREADY)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((canonical_line_word_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, canonical_line_word_out_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((canonical_line_word_out_TREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln475_fu_161_p2)
    begin
        if (((icmp_ln475_fu_161_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_word_index_3_assign_proc : process(ap_CS_fsm_pp0_stage0, word_index_fu_106, ap_loop_init, ap_block_pp0_stage0)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_word_index_3 <= ap_const_lv9_0;
        else 
            ap_sig_allocacmp_word_index_3 <= word_index_fu_106;
        end if; 
    end process;

    canonical_line_word_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_fu_373_p12),64));

    canonical_line_word_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, canonical_line_word_out_TREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            canonical_line_word_out_TDATA_blk_n <= canonical_line_word_out_TREADY;
        else 
            canonical_line_word_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    canonical_line_word_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            canonical_line_word_out_TVALID <= ap_const_logic_1;
        else 
            canonical_line_word_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln377_1_fu_311_p2 <= "1" when (word_index_4_fu_195_p1 = ap_const_lv8_3) else "0";
    icmp_ln377_fu_299_p2 <= "1" when (word_index_4_fu_195_p1 = ap_const_lv8_2) else "0";
    icmp_ln475_fu_161_p2 <= "1" when (ap_sig_allocacmp_word_index_3 = profile_raw_line_words_val) else "0";
    icmp_ln481_fu_189_p2 <= "1" when (tmp_fu_179_p4 = ap_const_lv7_0) else "0";
    line_end_fu_173_p2 <= "1" when (add_ln479_fu_167_p2 = profile_raw_line_words_val) else "0";
    line_start_fu_359_p2 <= "1" when (word_index_3_reg_425 = ap_const_lv9_0) else "0";
    or_ln8_fu_279_p3 <= (ap_const_lv1_1 & zext_ln423_fu_275_p1);
    or_ln_fu_247_p3 <= (ap_const_lv1_1 & zext_ln406_fu_243_p1);
    result_41_fu_223_p3 <= 
        ap_const_lv4_E when (tmp_83_fu_199_p3(0) = '1') else 
        ap_const_lv4_A;
    result_43_fu_231_p3 <= 
        result_41_fu_223_p3 when (tmp_84_fu_215_p3(0) = '1') else 
        select_ln40_fu_207_p3;
    result_44_fu_255_p3 <= 
        or_ln_fu_247_p3 when (line_faulted(0) = '1') else 
        zext_ln360_fu_239_p1;
    result_45_fu_287_p3 <= 
        or_ln8_fu_279_p3 when (tmp_85_fu_267_p3(0) = '1') else 
        zext_ln360_6_fu_263_p1;
    result_47_fu_331_p4 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_45_fu_287_p3),17));
    result_47_fu_331_p7 <= "XXXXXXXXXXXXXXXXX";
    result_47_fu_331_p8 <= (and_ln377_fu_305_p2 & and_ln377_1_fu_317_p2);
    result_fu_373_p12 <= ((((((((((line_faulted & ap_const_lv1_1) & last_column) & first_column) & ap_const_lv1_0) & line_end_reg_434) & line_start_fu_359_p2) & profile_raw_line_words_val) & word_index_3_reg_425) & zext_ln32_fu_369_p1) & sext_ln360_fu_356_p1);
    select_ln40_fu_207_p3 <= 
        ap_const_lv4_6 when (tmp_83_fu_199_p3(0) = '1') else 
        ap_const_lv4_2;
        sext_ln360_fu_356_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(result_47_reg_444),32));

    tmp_83_fu_199_p3 <= context_val(19 downto 19);
    tmp_84_fu_215_p3 <= context_val(37 downto 37);
    tmp_85_fu_267_p3 <= context_val(36 downto 36);
    tmp_fu_179_p4 <= ap_sig_allocacmp_word_index_3(8 downto 2);
    word_index_4_fu_195_p1 <= ap_sig_allocacmp_word_index_3(8 - 1 downto 0);
    xor_ln32_fu_364_p2 <= (icmp_ln481_reg_439 xor ap_const_lv1_1);
    zext_ln32_fu_369_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(xor_ln32_fu_364_p2),2));
    zext_ln360_6_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_44_fu_255_p3),10));
    zext_ln360_fu_239_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_43_fu_231_p3),7));
    zext_ln406_fu_243_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_43_fu_231_p3),6));
    zext_ln423_fu_275_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_44_fu_255_p3),9));
end behav;
