-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit is
port (
    ap_ready : OUT STD_LOGIC;
    cell_val : IN STD_LOGIC_VECTOR (133 downto 0);
    return_index : IN STD_LOGIC_VECTOR (2 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (16 downto 0);
    ap_rst : IN STD_LOGIC );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv32_85 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000101";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_31 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110001";
    constant ap_const_lv32_41 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000001";
    constant ap_const_lv32_42 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000010";
    constant ap_const_lv32_52 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010010";
    constant ap_const_lv32_53 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010011";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_64 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100100";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln445_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln445_1_fu_158_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln445_2_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln445_3_fu_170_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln445_4_fu_176_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln445_5_fu_182_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal retval_0_in_fu_204_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p4 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p6 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p8 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p10 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p12 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p14 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p15 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p16 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p17 : STD_LOGIC_VECTOR (16 downto 0);
    signal retval_0_in_fu_204_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p5 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p7 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p9 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p11 : STD_LOGIC_VECTOR (5 downto 0);
    signal retval_0_in_fu_204_p13 : STD_LOGIC_VECTOR (5 downto 0);

    component gpx_lane_word_formatter_hls_sparsemux_15_6_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (5 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (5 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (5 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (5 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (5 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (5 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (5 downto 0);
        din6_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        din3 : IN STD_LOGIC_VECTOR (16 downto 0);
        din4 : IN STD_LOGIC_VECTOR (16 downto 0);
        din5 : IN STD_LOGIC_VECTOR (16 downto 0);
        din6 : IN STD_LOGIC_VECTOR (16 downto 0);
        def : IN STD_LOGIC_VECTOR (16 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;



begin
    sparsemux_15_6_17_1_1_U23 : component gpx_lane_word_formatter_hls_sparsemux_15_6_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100000",
        din0_WIDTH => 17,
        CASE1 => "010000",
        din1_WIDTH => 17,
        CASE2 => "001000",
        din2_WIDTH => 17,
        CASE3 => "000100",
        din3_WIDTH => 17,
        CASE4 => "000010",
        din4_WIDTH => 17,
        CASE5 => "000001",
        din5_WIDTH => 17,
        CASE6 => "000000",
        din6_WIDTH => 17,
        def_WIDTH => 17,
        sel_WIDTH => 6,
        dout_WIDTH => 17)
    port map (
        din0 => retval_0_in_fu_204_p2,
        din1 => retval_0_in_fu_204_p4,
        din2 => retval_0_in_fu_204_p6,
        din3 => retval_0_in_fu_204_p8,
        din4 => retval_0_in_fu_204_p10,
        din5 => retval_0_in_fu_204_p12,
        din6 => retval_0_in_fu_204_p14,
        def => retval_0_in_fu_204_p15,
        sel => retval_0_in_fu_204_p16,
        dout => retval_0_in_fu_204_p17);




    ap_ready <= ap_const_logic_1;
    ap_return <= retval_0_in_fu_204_p17;
    icmp_ln445_1_fu_158_p2 <= "1" when (return_index = ap_const_lv3_5) else "0";
    icmp_ln445_2_fu_164_p2 <= "1" when (return_index = ap_const_lv3_4) else "0";
    icmp_ln445_3_fu_170_p2 <= "1" when (return_index = ap_const_lv3_3) else "0";
    icmp_ln445_4_fu_176_p2 <= "1" when (return_index = ap_const_lv3_2) else "0";
    icmp_ln445_5_fu_182_p2 <= "1" when (return_index = ap_const_lv3_1) else "0";
    icmp_ln445_fu_152_p2 <= "1" when (return_index = ap_const_lv3_6) else "0";
    retval_0_in_fu_204_p10 <= cell_val(65 downto 49);
    retval_0_in_fu_204_p12 <= cell_val(48 downto 32);
    retval_0_in_fu_204_p14 <= cell_val(31 downto 15);
    retval_0_in_fu_204_p15 <= "XXXXXXXXXXXXXXXXX";
    retval_0_in_fu_204_p16 <= (((((icmp_ln445_fu_152_p2 & icmp_ln445_1_fu_158_p2) & icmp_ln445_2_fu_164_p2) & icmp_ln445_3_fu_170_p2) & icmp_ln445_4_fu_176_p2) & icmp_ln445_5_fu_182_p2);
    retval_0_in_fu_204_p2 <= cell_val(133 downto 117);
    retval_0_in_fu_204_p4 <= cell_val(116 downto 100);
    retval_0_in_fu_204_p6 <= cell_val(99 downto 83);
    retval_0_in_fu_204_p8 <= cell_val(82 downto 66);
end behav;
