-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_footer_line is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    canonical_line_word_out_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    canonical_line_word_out_TVALID : OUT STD_LOGIC;
    canonical_line_word_out_TREADY : IN STD_LOGIC;
    close_result_val : IN STD_LOGIC_VECTOR (86 downto 0);
    profile_slope_is_rise_val : IN STD_LOGIC_VECTOR (0 downto 0);
    profile_output_width_code_val : IN STD_LOGIC_VECTOR (1 downto 0);
    profile_cell_slot_count_val : IN STD_LOGIC_VECTOR (5 downto 0);
    profile_serialized_return_slots_val : IN STD_LOGIC_VECTOR (2 downto 0);
    profile_planned_shot_columns_val : IN STD_LOGIC_VECTOR (15 downto 0);
    profile_hsize_words_val : IN STD_LOGIC_VECTOR (8 downto 0);
    profile_hsize_bytes_val : IN STD_LOGIC_VECTOR (15 downto 0);
    profile_vsize_lines_val : IN STD_LOGIC_VECTOR (15 downto 0);
    completed_lines : IN STD_LOGIC_VECTOR (15 downto 0);
    logical_word_offset : IN STD_LOGIC_VECTOR (7 downto 0);
    final_footer_line : IN STD_LOGIC_VECTOR (0 downto 0);
    p_anonymous_namespace_any_shot_line_fault : IN STD_LOGIC_VECTOR (0 downto 0);
    p_anonymous_namespace_any_missing_shot_line : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_footer_line is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv32_56 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010110";
    constant ap_const_lv8_6 : STD_LOGIC_VECTOR (7 downto 0) := "00000110";
    constant ap_const_lv8_5 : STD_LOGIC_VECTOR (7 downto 0) := "00000101";
    constant ap_const_lv8_4 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_const_lv8_3 : STD_LOGIC_VECTOR (7 downto 0) := "00000011";
    constant ap_const_lv8_2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv8_7 : STD_LOGIC_VECTOR (7 downto 0) := "00000111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_25 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100101";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_44 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000100";
    constant ap_const_lv32_55 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010101";
    constant ap_const_lv32_434F4D54 : STD_LOGIC_VECTOR (31 downto 0) := "01000011010011110100110101010100";
    constant ap_const_lv32_47504631 : STD_LOGIC_VECTOR (31 downto 0) := "01000111010100000100011000110001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal canonical_line_word_out_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal count_mismatch_fu_259_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal count_mismatch_reg_807 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln769_fu_265_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln769_reg_812 : STD_LOGIC_VECTOR (9 downto 0);
    signal result_52_fu_269_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_52_reg_817 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln728_fu_277_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal zext_ln728_reg_822 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln_fu_281_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal or_ln_reg_827 : STD_LOGIC_VECTOR (16 downto 0);
    signal line_word_index_1_reg_842 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal line_end_fu_316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_end_reg_851 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln779_fu_340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln779_reg_857 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_53_fu_357_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal result_53_reg_868 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal icmp_ln670_fu_363_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_reg_874 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_1_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_1_reg_879 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_2_fu_375_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_2_reg_884 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_3_fu_381_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_3_reg_889 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_4_fu_387_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_4_reg_894 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_5_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_5_reg_899 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_6_fu_405_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln670_6_reg_904 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln769_fu_305_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal line_word_index_fu_176 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln774_fu_310_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal zext_ln776_fu_321_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal logical_word_index_fu_325_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_fu_330_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_88_fu_350_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal logical_word_index_1_fu_346_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln670_5_fu_393_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_1_fu_419_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal or_ln9_fu_432_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal zext_ln669_fu_428_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal result_48_fu_440_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_86_fu_451_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_3_fu_458_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln669_1_fu_447_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal result_49_fu_466_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_87_fu_478_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln1_fu_485_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln669_2_fu_474_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal result_50_fu_493_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal result_2_fu_501_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_4_fu_512_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_61_fu_525_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal result_51_fu_534_p4 : STD_LOGIC_VECTOR (24 downto 0);
    signal result_54_fu_549_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln669_4_fu_546_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal result_55_fu_556_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal or_ln2_fu_567_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal zext_ln669_5_fu_563_p1 : STD_LOGIC_VECTOR (18 downto 0);
    signal result_56_fu_575_p3 : STD_LOGIC_VECTOR (18 downto 0);
    signal result_57_fu_586_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln669_6_fu_582_p1 : STD_LOGIC_VECTOR (19 downto 0);
    signal result_58_fu_594_p3 : STD_LOGIC_VECTOR (19 downto 0);
    signal zext_ln746_fu_612_p1 : STD_LOGIC_VECTOR (21 downto 0);
    signal tmp_89_fu_605_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln3_fu_616_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal zext_ln669_7_fu_601_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal result_59_fu_624_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal xor_ln779_fu_636_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_fu_641_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_1_fu_645_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_2_fu_649_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_3_fu_653_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_4_fu_657_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln670_6_fu_661_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_62_fu_684_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p8 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p12 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p14 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p19 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_62_fu_684_p20 : STD_LOGIC_VECTOR (7 downto 0);
    signal frame_end_fu_732_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal line_start_fu_727_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal result_62_fu_684_p21 : STD_LOGIC_VECTOR (31 downto 0);
    signal result_61_fu_736_p8 : STD_LOGIC_VECTOR (54 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal result_62_fu_684_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p5 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p7 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p13 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p15 : STD_LOGIC_VECTOR (7 downto 0);
    signal result_62_fu_684_p17 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gpx_lane_word_formatter_hls_sparsemux_19_8_32_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (7 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (7 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (7 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (7 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (7 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (7 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (7 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (7 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (7 downto 0);
        din8_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        din2 : IN STD_LOGIC_VECTOR (31 downto 0);
        din3 : IN STD_LOGIC_VECTOR (31 downto 0);
        din4 : IN STD_LOGIC_VECTOR (31 downto 0);
        din5 : IN STD_LOGIC_VECTOR (31 downto 0);
        din6 : IN STD_LOGIC_VECTOR (31 downto 0);
        din7 : IN STD_LOGIC_VECTOR (31 downto 0);
        din8 : IN STD_LOGIC_VECTOR (31 downto 0);
        def : IN STD_LOGIC_VECTOR (31 downto 0);
        sel : IN STD_LOGIC_VECTOR (7 downto 0);
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    sparsemux_19_8_32_1_1_U49 : component gpx_lane_word_formatter_hls_sparsemux_19_8_32_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "10000000",
        din0_WIDTH => 32,
        CASE1 => "01000000",
        din1_WIDTH => 32,
        CASE2 => "00100000",
        din2_WIDTH => 32,
        CASE3 => "00010000",
        din3_WIDTH => 32,
        CASE4 => "00001000",
        din4_WIDTH => 32,
        CASE5 => "00000100",
        din5_WIDTH => 32,
        CASE6 => "00000010",
        din6_WIDTH => 32,
        CASE7 => "00000001",
        din7_WIDTH => 32,
        CASE8 => "00000000",
        din8_WIDTH => 32,
        def_WIDTH => 32,
        sel_WIDTH => 8,
        dout_WIDTH => 32)
    port map (
        din0 => ap_const_lv32_0,
        din1 => result_62_fu_684_p4,
        din2 => result_52_reg_817,
        din3 => result_62_fu_684_p8,
        din4 => result_62_fu_684_p10,
        din5 => result_62_fu_684_p12,
        din6 => result_62_fu_684_p14,
        din7 => ap_const_lv32_434F4D54,
        din8 => ap_const_lv32_47504631,
        def => result_62_fu_684_p19,
        sel => result_62_fu_684_p20,
        dout => result_62_fu_684_p21);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    line_word_index_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                line_word_index_fu_176 <= ap_const_lv9_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln769_fu_305_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                line_word_index_fu_176 <= add_ln774_fu_310_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                and_ln670_5_reg_899 <= and_ln670_5_fu_399_p2;
                icmp_ln670_1_reg_879 <= icmp_ln670_1_fu_369_p2;
                icmp_ln670_2_reg_884 <= icmp_ln670_2_fu_375_p2;
                icmp_ln670_3_reg_889 <= icmp_ln670_3_fu_381_p2;
                icmp_ln670_4_reg_894 <= icmp_ln670_4_fu_387_p2;
                icmp_ln670_6_reg_904 <= icmp_ln670_6_fu_405_p2;
                icmp_ln670_reg_874 <= icmp_ln670_fu_363_p2;
                icmp_ln779_reg_857 <= icmp_ln779_fu_340_p2;
                line_end_reg_851 <= line_end_fu_316_p2;
                line_word_index_1_reg_842 <= line_word_index_fu_176;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                count_mismatch_reg_807 <= count_mismatch_fu_259_p2;
                    or_ln_reg_827(15 downto 0) <= or_ln_fu_281_p3(15 downto 0);
                result_52_reg_817 <= result_52_fu_269_p3;
                    zext_ln728_reg_822(15 downto 0) <= zext_ln728_fu_277_p1(15 downto 0);
                    zext_ln769_reg_812(7 downto 0) <= zext_ln769_fu_265_p1(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                result_53_reg_868 <= result_53_fu_357_p3;
            end if;
        end if;
    end process;
    zext_ln769_reg_812(9 downto 8) <= "00";
    zext_ln728_reg_822(16) <= '0';
    or_ln_reg_827(16) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln769_fu_305_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln769_fu_305_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (icmp_ln769_fu_305_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    add_ln774_fu_310_p2 <= std_logic_vector(unsigned(line_word_index_fu_176) + unsigned(ap_const_lv9_1));
    and_ln670_1_fu_645_p2 <= (icmp_ln779_reg_857 and icmp_ln670_1_reg_879);
    and_ln670_2_fu_649_p2 <= (icmp_ln779_reg_857 and icmp_ln670_2_reg_884);
    and_ln670_3_fu_653_p2 <= (icmp_ln779_reg_857 and icmp_ln670_3_reg_889);
    and_ln670_4_fu_657_p2 <= (icmp_ln779_reg_857 and icmp_ln670_4_reg_894);
    and_ln670_5_fu_399_p2 <= (icmp_ln779_fu_340_p2 and icmp_ln670_5_fu_393_p2);
    and_ln670_6_fu_661_p2 <= (icmp_ln779_reg_857 and icmp_ln670_6_reg_904);
    and_ln670_fu_641_p2 <= (icmp_ln779_reg_857 and icmp_ln670_reg_874);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(canonical_line_word_out_TREADY, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (canonical_line_word_out_TREADY = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(canonical_line_word_out_TREADY, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (canonical_line_word_out_TREADY = ap_const_logic_0));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(canonical_line_word_out_TREADY, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (canonical_line_word_out_TREADY = ap_const_logic_0));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(canonical_line_word_out_TREADY, ap_enable_reg_pp0_iter1)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (canonical_line_word_out_TREADY = ap_const_logic_0));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln769_fu_305_p2)
    begin
        if ((icmp_ln769_fu_305_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    canonical_line_word_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_61_fu_736_p8),64));

    canonical_line_word_out_TDATA_blk_n_assign_proc : process(canonical_line_word_out_TREADY, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            canonical_line_word_out_TDATA_blk_n <= canonical_line_word_out_TREADY;
        else 
            canonical_line_word_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    canonical_line_word_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            canonical_line_word_out_TVALID <= ap_const_logic_1;
        else 
            canonical_line_word_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    count_mismatch_fu_259_p2 <= "0" when (completed_lines = profile_planned_shot_columns_val) else "1";
    frame_end_fu_732_p2 <= (line_end_reg_851 and final_footer_line);
    icmp_ln670_1_fu_369_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_5) else "0";
    icmp_ln670_2_fu_375_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_4) else "0";
    icmp_ln670_3_fu_381_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_3) else "0";
    icmp_ln670_4_fu_387_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_2) else "0";
    icmp_ln670_5_fu_393_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_1) else "0";
    icmp_ln670_6_fu_405_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_7) else "0";
    icmp_ln670_fu_363_p2 <= "1" when (logical_word_index_1_fu_346_p1 = ap_const_lv8_6) else "0";
    icmp_ln769_fu_305_p2 <= "1" when (line_word_index_fu_176 = profile_hsize_words_val) else "0";
    icmp_ln779_fu_340_p2 <= "1" when (tmp_fu_330_p4 = ap_const_lv7_0) else "0";
    line_end_fu_316_p2 <= "1" when (add_ln774_fu_310_p2 = profile_hsize_words_val) else "0";
    line_start_fu_727_p2 <= "1" when (line_word_index_1_reg_842 = ap_const_lv9_0) else "0";
    logical_word_index_1_fu_346_p1 <= logical_word_index_fu_325_p2(8 - 1 downto 0);
    logical_word_index_fu_325_p2 <= std_logic_vector(unsigned(zext_ln776_fu_321_p1) + unsigned(zext_ln769_reg_812));
    or_ln1_fu_485_p3 <= (ap_const_lv1_1 & result_49_fu_466_p3);
    or_ln2_fu_567_p3 <= (ap_const_lv1_1 & result_55_fu_556_p3);
    or_ln3_fu_616_p3 <= (ap_const_lv1_1 & zext_ln746_fu_612_p1);
    or_ln9_fu_432_p3 <= (ap_const_lv1_1 & result_1_fu_419_p4);
    or_ln_fu_281_p3 <= (ap_const_lv1_1 & completed_lines);
    result_1_fu_419_p4 <= close_result_val(34 downto 32);
    result_2_fu_501_p3 <= (profile_output_width_code_val & result_50_fu_493_p3);
    result_3_fu_458_p3 <= (ap_const_lv1_1 & result_48_fu_440_p3);
    result_48_fu_440_p3 <= 
        or_ln9_fu_432_p3 when (profile_slope_is_rise_val(0) = '1') else 
        zext_ln669_fu_428_p1;
    result_49_fu_466_p3 <= 
        result_3_fu_458_p3 when (tmp_86_fu_451_p3(0) = '1') else 
        zext_ln669_1_fu_447_p1;
    result_4_fu_512_p4 <= close_result_val(52 downto 37);
    result_50_fu_493_p3 <= 
        or_ln1_fu_485_p3 when (tmp_87_fu_478_p3(0) = '1') else 
        zext_ln669_2_fu_474_p1;
    result_51_fu_534_p4 <= ((profile_serialized_return_slots_val & profile_cell_slot_count_val) & tmp_61_fu_525_p4);
    result_52_fu_269_p3 <= (profile_vsize_lines_val & profile_hsize_bytes_val);
    result_53_fu_357_p3 <= 
        or_ln_reg_827 when (tmp_88_fu_350_p3(0) = '1') else 
        zext_ln728_reg_822;
    result_54_fu_549_p3 <= (ap_const_lv1_1 & result_53_reg_868);
    result_55_fu_556_p3 <= 
        result_54_fu_549_p3 when (count_mismatch_reg_807(0) = '1') else 
        zext_ln669_4_fu_546_p1;
    result_56_fu_575_p3 <= 
        or_ln2_fu_567_p3 when (p_anonymous_namespace_any_shot_line_fault(0) = '1') else 
        zext_ln669_5_fu_563_p1;
    result_57_fu_586_p3 <= (ap_const_lv1_1 & result_56_fu_575_p3);
    result_58_fu_594_p3 <= 
        result_57_fu_586_p3 when (p_anonymous_namespace_any_missing_shot_line(0) = '1') else 
        zext_ln669_6_fu_582_p1;
    result_59_fu_624_p3 <= 
        or_ln3_fu_616_p3 when (tmp_89_fu_605_p3(0) = '1') else 
        zext_ln669_7_fu_601_p1;
    result_61_fu_736_p8 <= ((((((frame_end_fu_732_p2 & line_end_reg_851) & line_start_fu_727_p2) & profile_hsize_words_val) & line_word_index_1_reg_842) & ap_const_lv2_2) & result_62_fu_684_p21);
    result_62_fu_684_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_4_fu_512_p4),32));
    result_62_fu_684_p12 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_2_fu_501_p3),32));
    result_62_fu_684_p14 <= close_result_val(32 - 1 downto 0);
    result_62_fu_684_p19 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    result_62_fu_684_p20 <= (((((((xor_ln779_fu_636_p2 & and_ln670_fu_641_p2) & and_ln670_1_fu_645_p2) & and_ln670_2_fu_649_p2) & and_ln670_3_fu_653_p2) & and_ln670_4_fu_657_p2) & and_ln670_5_reg_899) & and_ln670_6_fu_661_p2);
    result_62_fu_684_p4 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_59_fu_624_p3),32));
    result_62_fu_684_p8 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_51_fu_534_p4),32));
    tmp_61_fu_525_p4 <= close_result_val(68 downto 53);
    tmp_86_fu_451_p3 <= close_result_val(35 downto 35);
    tmp_87_fu_478_p3 <= close_result_val(36 downto 36);
    tmp_88_fu_350_p3 <= close_result_val(86 downto 86);
    tmp_89_fu_605_p3 <= close_result_val(85 downto 85);
    tmp_fu_330_p4 <= logical_word_index_fu_325_p2(9 downto 3);
    xor_ln779_fu_636_p2 <= (icmp_ln779_reg_857 xor ap_const_lv1_1);
    zext_ln669_1_fu_447_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_48_fu_440_p3),5));
    zext_ln669_2_fu_474_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_49_fu_466_p3),6));
    zext_ln669_4_fu_546_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_53_reg_868),18));
    zext_ln669_5_fu_563_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_55_fu_556_p3),19));
    zext_ln669_6_fu_582_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_56_fu_575_p3),20));
    zext_ln669_7_fu_601_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_58_fu_594_p3),23));
    zext_ln669_fu_428_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_1_fu_419_p4),4));
    zext_ln728_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(completed_lines),17));
    zext_ln746_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(result_58_fu_594_p3),22));
    zext_ln769_fu_265_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(logical_word_offset),10));
    zext_ln776_fu_321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(line_word_index_fu_176),10));
end behav;
