-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_cell_collector_hls_gpx_cell_collector_hls_Pipeline_VITIS_LOOP_262_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    chip_base_address : IN STD_LOGIC_VECTOR (5 downto 0);
    p_anonymous_namespace_received_return_count_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_anonymous_namespace_received_return_count_ce1 : OUT STD_LOGIC;
    p_anonymous_namespace_received_return_count_we1 : OUT STD_LOGIC;
    p_anonymous_namespace_received_return_count_d1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    p_anonymous_namespace_return_overflow_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_anonymous_namespace_return_overflow_ce1 : OUT STD_LOGIC;
    p_anonymous_namespace_return_overflow_we1 : OUT STD_LOGIC;
    p_anonymous_namespace_return_overflow_d1 : OUT STD_LOGIC_VECTOR (0 downto 0);
    p_anonymous_namespace_cell_error_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    p_anonymous_namespace_cell_error_ce1 : OUT STD_LOGIC;
    p_anonymous_namespace_cell_error_we1 : OUT STD_LOGIC;
    p_anonymous_namespace_cell_error_d1 : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of gpx_cell_collector_hls_gpx_cell_collector_hls_Pipeline_VITIS_LOOP_262_1 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln263_fu_120_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln268_fu_142_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal cell_slot_offset_fu_48 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln264_fu_126_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_cell_slot_offset_1 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_anonymous_namespace_received_return_count_we1_local : STD_LOGIC;
    signal p_anonymous_namespace_received_return_count_ce1_local : STD_LOGIC;
    signal p_anonymous_namespace_return_overflow_we1_local : STD_LOGIC;
    signal p_anonymous_namespace_return_overflow_ce1_local : STD_LOGIC;
    signal p_anonymous_namespace_cell_error_we1_local : STD_LOGIC;
    signal p_anonymous_namespace_cell_error_ce1_local : STD_LOGIC;
    signal zext_ln263_fu_132_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln267_fu_136_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component gpx_cell_collector_hls_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component gpx_cell_collector_hls_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    cell_slot_offset_fu_48_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln263_fu_120_p2 = ap_const_lv1_0)) then 
                    cell_slot_offset_fu_48 <= add_ln264_fu_126_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    cell_slot_offset_fu_48 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln264_fu_126_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_cell_slot_offset_1) + unsigned(ap_const_lv5_1));
    add_ln267_fu_136_p2 <= std_logic_vector(unsigned(zext_ln263_fu_132_p1) + unsigned(chip_base_address));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln263_fu_120_p2)
    begin
        if (((icmp_ln263_fu_120_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_cell_slot_offset_1_assign_proc : process(ap_CS_fsm_state1, cell_slot_offset_fu_48, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_sig_allocacmp_cell_slot_offset_1 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_cell_slot_offset_1 <= cell_slot_offset_fu_48;
        end if; 
    end process;

    icmp_ln263_fu_120_p2 <= "1" when (ap_sig_allocacmp_cell_slot_offset_1 = ap_const_lv5_10) else "0";
    p_anonymous_namespace_cell_error_address1 <= zext_ln268_fu_142_p1(6 - 1 downto 0);
    p_anonymous_namespace_cell_error_ce1 <= p_anonymous_namespace_cell_error_ce1_local;

    p_anonymous_namespace_cell_error_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_cell_error_ce1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_cell_error_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_cell_error_d1 <= ap_const_lv1_0;
    p_anonymous_namespace_cell_error_we1 <= p_anonymous_namespace_cell_error_we1_local;

    p_anonymous_namespace_cell_error_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln263_fu_120_p2)
    begin
        if (((icmp_ln263_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_cell_error_we1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_cell_error_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_received_return_count_address1 <= zext_ln268_fu_142_p1(6 - 1 downto 0);
    p_anonymous_namespace_received_return_count_ce1 <= p_anonymous_namespace_received_return_count_ce1_local;

    p_anonymous_namespace_received_return_count_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_received_return_count_ce1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_received_return_count_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_received_return_count_d1 <= ap_const_lv3_0;
    p_anonymous_namespace_received_return_count_we1 <= p_anonymous_namespace_received_return_count_we1_local;

    p_anonymous_namespace_received_return_count_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln263_fu_120_p2)
    begin
        if (((icmp_ln263_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_received_return_count_we1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_received_return_count_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_return_overflow_address1 <= zext_ln268_fu_142_p1(6 - 1 downto 0);
    p_anonymous_namespace_return_overflow_ce1 <= p_anonymous_namespace_return_overflow_ce1_local;

    p_anonymous_namespace_return_overflow_ce1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_return_overflow_ce1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_return_overflow_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_return_overflow_d1 <= ap_const_lv1_0;
    p_anonymous_namespace_return_overflow_we1 <= p_anonymous_namespace_return_overflow_we1_local;

    p_anonymous_namespace_return_overflow_we1_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln263_fu_120_p2)
    begin
        if (((icmp_ln263_fu_120_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            p_anonymous_namespace_return_overflow_we1_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_return_overflow_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln263_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_cell_slot_offset_1),6));
    zext_ln268_fu_142_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln267_fu_136_p2),64));
end behav;
