// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_cell_collector_hls_gpx_cell_collector_hls_Pipeline_VITIS_LOOP_534_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        collector_result_out_TREADY,
        zext_ln388,
        zext_ln539,
        last_stop_channel_2,
        build_stop_channels_per_chip,
        tdc_chip_index,
        xor_ln52,
        insert_error_fill_3,
        tmp_12,
        emitted_slope_is_rise,
        collector_result_out_TDATA,
        collector_result_out_TVALID,
        p_out,
        p_out_ap_vld,
        p_anonymous_namespace_owner_visible_return_count_address0,
        p_anonymous_namespace_owner_visible_return_count_ce0,
        p_anonymous_namespace_owner_visible_return_count_q0,
        p_anonymous_namespace_owner_shot_is_faulted_address0,
        p_anonymous_namespace_owner_shot_is_faulted_ce0,
        p_anonymous_namespace_owner_shot_is_faulted_q0,
        p_anonymous_namespace_owner_chip_shot_sequence_address0,
        p_anonymous_namespace_owner_chip_shot_sequence_ce0,
        p_anonymous_namespace_owner_chip_shot_sequence_q0,
        p_anonymous_namespace_received_return_count_address0,
        p_anonymous_namespace_received_return_count_ce0,
        p_anonymous_namespace_received_return_count_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_0_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_0_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_1_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_1_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_2_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_2_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_3_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_3_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_4_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_4_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_5_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_5_q0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_6_address0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0,
        p_ZN12_GLOBAL_N_118distance_hit_banksE_6_q0,
        p_anonymous_namespace_return_overflow_address0,
        p_anonymous_namespace_return_overflow_ce0,
        p_anonymous_namespace_return_overflow_q0,
        p_anonymous_namespace_cell_error_address0,
        p_anonymous_namespace_cell_error_ce0,
        p_anonymous_namespace_cell_error_q0,
        p_anonymous_namespace_owner_shot_context_address0,
        p_anonymous_namespace_owner_shot_context_ce0,
        p_anonymous_namespace_owner_shot_context_q0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   collector_result_out_TREADY;
input  [1:0] zext_ln388;
input  [2:0] zext_ln539;
input  [7:0] last_stop_channel_2;
input  [7:0] build_stop_channels_per_chip;
input  [1:0] tdc_chip_index;
input  [0:0] xor_ln52;
input  [0:0] insert_error_fill_3;
input  [2:0] tmp_12;
input  [0:0] emitted_slope_is_rise;
output  [327:0] collector_result_out_TDATA;
output   collector_result_out_TVALID;
output  [15:0] p_out;
output   p_out_ap_vld;
output  [1:0] p_anonymous_namespace_owner_visible_return_count_address0;
output   p_anonymous_namespace_owner_visible_return_count_ce0;
input  [2:0] p_anonymous_namespace_owner_visible_return_count_q0;
output  [1:0] p_anonymous_namespace_owner_shot_is_faulted_address0;
output   p_anonymous_namespace_owner_shot_is_faulted_ce0;
input  [0:0] p_anonymous_namespace_owner_shot_is_faulted_q0;
output  [1:0] p_anonymous_namespace_owner_chip_shot_sequence_address0;
output   p_anonymous_namespace_owner_chip_shot_sequence_ce0;
input  [15:0] p_anonymous_namespace_owner_chip_shot_sequence_q0;
output  [5:0] p_anonymous_namespace_received_return_count_address0;
output   p_anonymous_namespace_received_return_count_ce0;
input  [2:0] p_anonymous_namespace_received_return_count_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_0_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_0_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_1_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_1_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_2_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_2_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_3_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_3_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_4_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_4_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_5_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_5_q0;
output  [5:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_6_address0;
output   p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0;
input  [16:0] p_ZN12_GLOBAL_N_118distance_hit_banksE_6_q0;
output  [5:0] p_anonymous_namespace_return_overflow_address0;
output   p_anonymous_namespace_return_overflow_ce0;
input  [0:0] p_anonymous_namespace_return_overflow_q0;
output  [5:0] p_anonymous_namespace_cell_error_address0;
output   p_anonymous_namespace_cell_error_ce0;
input  [0:0] p_anonymous_namespace_cell_error_q0;
output  [1:0] p_anonymous_namespace_owner_shot_context_address0;
output   p_anonymous_namespace_owner_shot_context_ce0;
input  [161:0] p_anonymous_namespace_owner_shot_context_q0;

reg ap_idle;
reg collector_result_out_TVALID;
reg p_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
reg   [0:0] and_ln538_1_reg_717;
reg   [0:0] and_ln538_1_reg_717_pp0_iter1_reg;
reg    ap_block_state3_pp0_stage0_iter2_grp1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln535_fu_392_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    collector_result_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg    ap_block_pp0_stage0_11001;
reg   [1:0] p_anonymous_namespace_owner_shot_is_faulted_addr_reg_702;
reg   [1:0] p_anonymous_namespace_owner_chip_shot_sequence_addr_reg_707;
reg   [1:0] p_anonymous_namespace_owner_shot_context_addr_reg_712;
wire   [0:0] and_ln538_1_fu_444_p2;
wire   [2:0] trunc_ln545_fu_450_p1;
reg   [2:0] trunc_ln545_reg_721;
reg   [2:0] trunc_ln545_reg_721_pp0_iter1_reg;
wire   [63:0] zext_ln150_fu_464_p1;
reg   [63:0] zext_ln150_reg_726;
reg   [0:0] value_reg_744;
reg   [0:0] value_reg_744_pp0_iter1_reg;
reg   [2:0] p_anonymous_namespace_owner_visible_return_count_load_reg_749;
reg   [2:0] p_anonymous_namespace_received_return_count_load_reg_756;
wire   [63:0] zext_ln388_cast_fu_376_p1;
wire    ap_block_pp0_stage0;
reg   [3:0] emitted_stop_channel_fu_128;
wire   [3:0] emitted_stop_channel_2_fu_398_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_emitted_stop_channel_1;
reg    ap_block_pp0_stage0_01001_grp1;
reg    p_anonymous_namespace_owner_visible_return_count_ce0_local;
reg    p_anonymous_namespace_received_return_count_ce0_local;
reg    p_anonymous_namespace_owner_shot_is_faulted_ce0_local;
reg    p_anonymous_namespace_owner_chip_shot_sequence_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0_local;
reg    p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0_local;
reg    p_anonymous_namespace_return_overflow_ce0_local;
reg    p_anonymous_namespace_cell_error_ce0_local;
reg    p_anonymous_namespace_owner_shot_context_ce0_local;
wire   [3:0] zext_ln539_cast_fu_372_p1;
wire   [0:0] icmp_ln538_fu_408_p2;
wire   [7:0] zext_ln535_fu_404_p1;
wire   [0:0] icmp_ln539_fu_420_p2;
wire   [0:0] xor_ln539_fu_426_p2;
wire   [0:0] icmp_ln540_fu_432_p2;
wire   [0:0] and_ln538_fu_438_p2;
wire   [0:0] xor_ln538_fu_414_p2;
wire   [5:0] cell_slot_address_fu_454_p4;
wire   [0:0] icmp_ln150_fu_482_p2;
wire   [2:0] emitted_return_count_fu_486_p3;
wire   [0:0] icmp_ln177_fu_492_p2;
wire   [1:0] tmp_fu_506_p4;
wire   [0:0] icmp_ln177_1_fu_516_p2;
wire   [0:0] icmp_ln177_2_fu_530_p2;
wire   [0:0] tmp_1_fu_544_p3;
wire   [0:0] icmp_ln177_3_fu_560_p2;
wire   [0:0] icmp_ln177_4_fu_574_p2;
wire   [0:0] icmp_ln177_5_fu_588_p2;
wire   [0:0] or_ln190_fu_602_p2;
wire   [0:0] value_2_fu_607_p2;
wire   [16:0] ref_tmp7_0_6_i_fu_594_p3;
wire   [16:0] ref_tmp7_0_5_i_fu_580_p3;
wire   [16:0] ref_tmp7_0_4_i_fu_566_p3;
wire   [16:0] ref_tmp7_0_3_i_fu_552_p3;
wire   [16:0] ref_tmp7_0_2_i_fu_536_p3;
wire   [16:0] ref_tmp7_0_1_i_fu_522_p3;
wire   [16:0] ref_tmp7_0_i_fu_498_p3;
wire   [319:0] result_fu_613_p23;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 emitted_stop_channel_fu_128 = 4'd0;
#0 ap_done_reg = 1'b0;
end

gpx_cell_collector_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln535_fu_392_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            emitted_stop_channel_fu_128 <= emitted_stop_channel_2_fu_398_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            emitted_stop_channel_fu_128 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln538_1_reg_717 <= and_ln538_1_fu_444_p2;
        and_ln538_1_reg_717_pp0_iter1_reg <= and_ln538_1_reg_717;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        p_anonymous_namespace_received_return_count_load_reg_756 <= p_anonymous_namespace_received_return_count_q0;
        trunc_ln545_reg_721 <= trunc_ln545_fu_450_p1;
        trunc_ln545_reg_721_pp0_iter1_reg <= trunc_ln545_reg_721;
        value_reg_744 <= ap_sig_allocacmp_emitted_stop_channel_1[32'd2];
        value_reg_744_pp0_iter1_reg <= value_reg_744;
        zext_ln150_reg_726[5 : 0] <= zext_ln150_fu_464_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_owner_chip_shot_sequence_addr_reg_707 <= zext_ln388_cast_fu_376_p1;
        p_anonymous_namespace_owner_shot_context_addr_reg_712 <= zext_ln388_cast_fu_376_p1;
        p_anonymous_namespace_owner_shot_is_faulted_addr_reg_702 <= zext_ln388_cast_fu_376_p1;
        p_anonymous_namespace_owner_visible_return_count_load_reg_749 <= p_anonymous_namespace_owner_visible_return_count_q0;
    end
end

always @ (*) begin
    if (((icmp_ln535_fu_392_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_emitted_stop_channel_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_emitted_stop_channel_1 = emitted_stop_channel_fu_128;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (1'd1 == and_ln538_1_reg_717_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        collector_result_out_TDATA_blk_n = collector_result_out_TREADY;
    end else begin
        collector_result_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln538_1_reg_717_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        collector_result_out_TVALID = 1'b1;
    end else begin
        collector_result_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0_local = 1'b1;
    end else begin
        p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_cell_error_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_cell_error_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_owner_chip_shot_sequence_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_owner_chip_shot_sequence_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_owner_shot_context_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_owner_shot_context_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_owner_shot_is_faulted_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_owner_shot_is_faulted_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_owner_visible_return_count_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_owner_visible_return_count_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_received_return_count_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_received_return_count_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        p_anonymous_namespace_return_overflow_ce0_local = 1'b1;
    end else begin
        p_anonymous_namespace_return_overflow_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'd1 == and_ln538_1_reg_717_pp0_iter1_reg) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_out_ap_vld = 1'b1;
    end else begin
        p_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign and_ln538_1_fu_444_p2 = (xor_ln538_fu_414_p2 & and_ln538_fu_438_p2);

assign and_ln538_fu_438_p2 = (xor_ln539_fu_426_p2 & icmp_ln540_fu_432_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2_grp1));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2_grp1 = ((1'd1 == and_ln538_1_reg_717_pp0_iter1_reg) & (collector_result_out_TREADY == 1'b0));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cell_slot_address_fu_454_p4 = {{{tdc_chip_index}, {xor_ln52}}, {trunc_ln545_fu_450_p1}};

assign collector_result_out_TDATA = result_fu_613_p23;

assign emitted_return_count_fu_486_p3 = ((icmp_ln150_fu_482_p2[0:0] == 1'b1) ? p_anonymous_namespace_owner_visible_return_count_load_reg_749 : p_anonymous_namespace_received_return_count_load_reg_756);

assign emitted_stop_channel_2_fu_398_p2 = (ap_sig_allocacmp_emitted_stop_channel_1 + 4'd1);

assign icmp_ln150_fu_482_p2 = ((p_anonymous_namespace_received_return_count_load_reg_756 > p_anonymous_namespace_owner_visible_return_count_load_reg_749) ? 1'b1 : 1'b0);

assign icmp_ln177_1_fu_516_p2 = ((tmp_fu_506_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln177_2_fu_530_p2 = ((emitted_return_count_fu_486_p3 > 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln177_3_fu_560_p2 = ((emitted_return_count_fu_486_p3 > 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln177_4_fu_574_p2 = ((emitted_return_count_fu_486_p3 > 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln177_5_fu_588_p2 = ((emitted_return_count_fu_486_p3 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln177_fu_492_p2 = ((emitted_return_count_fu_486_p3 == 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln535_fu_392_p2 = ((ap_sig_allocacmp_emitted_stop_channel_1 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln538_fu_408_p2 = ((ap_sig_allocacmp_emitted_stop_channel_1 < zext_ln539_cast_fu_372_p1) ? 1'b1 : 1'b0);

assign icmp_ln539_fu_420_p2 = ((last_stop_channel_2 < zext_ln535_fu_404_p1) ? 1'b1 : 1'b0);

assign icmp_ln540_fu_432_p2 = ((zext_ln535_fu_404_p1 < build_stop_channels_per_chip) ? 1'b1 : 1'b0);

assign or_ln190_fu_602_p2 = (p_anonymous_namespace_cell_error_q0 | insert_error_fill_3);

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_0_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_0_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_1_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_1_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_2_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_2_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_3_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_3_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_4_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_4_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_5_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_5_ce0_local;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_6_address0 = zext_ln150_reg_726;

assign p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0 = p_ZN12_GLOBAL_N_118distance_hit_banksE_6_ce0_local;

assign p_anonymous_namespace_cell_error_address0 = zext_ln150_reg_726;

assign p_anonymous_namespace_cell_error_ce0 = p_anonymous_namespace_cell_error_ce0_local;

assign p_anonymous_namespace_owner_chip_shot_sequence_address0 = p_anonymous_namespace_owner_chip_shot_sequence_addr_reg_707;

assign p_anonymous_namespace_owner_chip_shot_sequence_ce0 = p_anonymous_namespace_owner_chip_shot_sequence_ce0_local;

assign p_anonymous_namespace_owner_shot_context_address0 = p_anonymous_namespace_owner_shot_context_addr_reg_712;

assign p_anonymous_namespace_owner_shot_context_ce0 = p_anonymous_namespace_owner_shot_context_ce0_local;

assign p_anonymous_namespace_owner_shot_is_faulted_address0 = p_anonymous_namespace_owner_shot_is_faulted_addr_reg_702;

assign p_anonymous_namespace_owner_shot_is_faulted_ce0 = p_anonymous_namespace_owner_shot_is_faulted_ce0_local;

assign p_anonymous_namespace_owner_visible_return_count_address0 = zext_ln388_cast_fu_376_p1;

assign p_anonymous_namespace_owner_visible_return_count_ce0 = p_anonymous_namespace_owner_visible_return_count_ce0_local;

assign p_anonymous_namespace_received_return_count_address0 = zext_ln150_fu_464_p1;

assign p_anonymous_namespace_received_return_count_ce0 = p_anonymous_namespace_received_return_count_ce0_local;

assign p_anonymous_namespace_return_overflow_address0 = zext_ln150_reg_726;

assign p_anonymous_namespace_return_overflow_ce0 = p_anonymous_namespace_return_overflow_ce0_local;

assign p_out = p_anonymous_namespace_owner_chip_shot_sequence_q0;

assign ref_tmp7_0_1_i_fu_522_p3 = ((icmp_ln177_1_fu_516_p2[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_1_q0 : 17'd0);

assign ref_tmp7_0_2_i_fu_536_p3 = ((icmp_ln177_2_fu_530_p2[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_2_q0 : 17'd0);

assign ref_tmp7_0_3_i_fu_552_p3 = ((tmp_1_fu_544_p3[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_3_q0 : 17'd0);

assign ref_tmp7_0_4_i_fu_566_p3 = ((icmp_ln177_3_fu_560_p2[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_4_q0 : 17'd0);

assign ref_tmp7_0_5_i_fu_580_p3 = ((icmp_ln177_4_fu_574_p2[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_5_q0 : 17'd0);

assign ref_tmp7_0_6_i_fu_594_p3 = ((icmp_ln177_5_fu_588_p2[0:0] == 1'b1) ? p_ZN12_GLOBAL_N_118distance_hit_banksE_6_q0 : 17'd0);

assign ref_tmp7_0_i_fu_498_p3 = ((icmp_ln177_fu_492_p2[0:0] == 1'b1) ? 17'd0 : p_ZN12_GLOBAL_N_118distance_hit_banksE_0_q0);

assign result_fu_613_p23 = {{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{1'd1}, {p_anonymous_namespace_owner_chip_shot_sequence_q0}}}, {p_anonymous_namespace_owner_shot_context_q0}}}, {tmp_12}}}, {value_2_fu_607_p2}}}, {insert_error_fill_3}}}, {p_anonymous_namespace_return_overflow_q0}}}, {1'd0}}}, {ref_tmp7_0_6_i_fu_594_p3}}}, {ref_tmp7_0_5_i_fu_580_p3}}}, {ref_tmp7_0_4_i_fu_566_p3}}}, {ref_tmp7_0_3_i_fu_552_p3}}}, {ref_tmp7_0_2_i_fu_536_p3}}}, {ref_tmp7_0_1_i_fu_522_p3}}}, {ref_tmp7_0_i_fu_498_p3}}}, {p_anonymous_namespace_owner_visible_return_count_load_reg_749}}}, {emitted_return_count_fu_486_p3}}}, {emitted_slope_is_rise}}}, {trunc_ln545_reg_721_pp0_iter1_reg}}}, {value_reg_744_pp0_iter1_reg}}}, {tdc_chip_index}}}, {2'd0}};

assign tmp_1_fu_544_p3 = emitted_return_count_fu_486_p3[32'd2];

assign tmp_fu_506_p4 = {{emitted_return_count_fu_486_p3[2:1]}};

assign trunc_ln545_fu_450_p1 = ap_sig_allocacmp_emitted_stop_channel_1[2:0];

assign value_2_fu_607_p2 = (p_anonymous_namespace_owner_shot_is_faulted_q0 | or_ln190_fu_602_p2);

assign xor_ln538_fu_414_p2 = (icmp_ln538_fu_408_p2 ^ 1'd1);

assign xor_ln539_fu_426_p2 = (icmp_ln539_fu_420_p2 ^ 1'd1);

assign zext_ln150_fu_464_p1 = cell_slot_address_fu_454_p4;

assign zext_ln388_cast_fu_376_p1 = zext_ln388;

assign zext_ln535_fu_404_p1 = ap_sig_allocacmp_emitted_stop_channel_1;

assign zext_ln539_cast_fu_372_p1 = zext_ln539;

always @ (posedge ap_clk) begin
    zext_ln150_reg_726[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //gpx_cell_collector_hls_gpx_cell_collector_hls_Pipeline_VITIS_LOOP_534_2
