// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="gpx_hit_decoder_hls_gpx_hit_decoder_hls,hls_ip_2025_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-2,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=4.365312,HLS_SYN_LAT=2,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=229,HLS_SYN_LUT=321,HLS_VERSION=2025_2}" *)

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_hit_decoder_hls (
        ap_clk,
        ap_rst_n,
        raw_event_in_TDATA,
        raw_event_in_TVALID,
        raw_event_in_TREADY,
        decoder_result_out_TDATA,
        decoder_result_out_TVALID,
        decoder_result_out_TREADY,
        build_tdc_chip_count,
        build_stop_channels_per_chip,
        runtime_enabled_rise_chip_mask,
        runtime_enabled_fall_chip_mask
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input  [215:0] raw_event_in_TDATA;
input   raw_event_in_TVALID;
output   raw_event_in_TREADY;
output  [223:0] decoder_result_out_TDATA;
output   decoder_result_out_TVALID;
input   decoder_result_out_TREADY;
input  [7:0] build_tdc_chip_count;
input  [7:0] build_stop_channels_per_chip;
input  [7:0] runtime_enabled_rise_chip_mask;
input  [7:0] runtime_enabled_fall_chip_mask;

 reg    ap_rst_n_inv;
reg    raw_event_in_TDATA_blk_n;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
wire    ap_CS_iter2_fsm_state3;
reg    decoder_result_out_TDATA_blk_n;
reg   [215:0] raw_event_reg_408;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
wire    regslice_both_decoder_result_out_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
wire   [0:0] ififo_bank_select_fu_151_p3;
reg   [0:0] ififo_bank_select_reg_418;
wire   [0:0] icmp_ln58_fu_159_p2;
reg   [0:0] icmp_ln58_reg_423;
wire   [0:0] icmp_ln61_fu_165_p2;
reg   [0:0] icmp_ln61_reg_430;
wire   [1:0] tmp_3_fu_171_p4;
reg   [1:0] tmp_3_reg_436;
wire   [0:0] edge_slope_is_rise_fu_193_p3;
reg   [0:0] edge_slope_is_rise_reg_442;
wire   [0:0] icmp_ln76_fu_201_p2;
reg   [0:0] icmp_ln76_reg_447;
wire   [0:0] icmp_ln16_fu_239_p2;
reg   [0:0] icmp_ln16_reg_454;
wire   [1:0] tdc_chip_index_fu_139_p3;
wire   [7:0] zext_ln30_fu_147_p1;
wire   [1:0] trunc_ln25_fu_135_p1;
wire   [2:0] logical_stop_channel_index_fu_181_p3;
wire   [7:0] zext_ln71_fu_189_p1;
wire   [3:0] trunc_ln13_fu_207_p1;
wire   [3:0] trunc_ln13_1_fu_211_p1;
wire   [3:0] zext_ln16_fu_223_p1;
wire   [3:0] shl_ln16_fu_227_p2;
wire   [3:0] enabled_chip_mask_fu_215_p3;
wire   [3:0] and_ln16_fu_233_p2;
wire   [4:0] trunc_ln32_fu_254_p1;
wire   [181:0] tmp_2_fu_245_p4;
wire   [35:0] zext_ln32_fu_257_p1;
wire   [181:0] tmp_7_fu_294_p3;
wire   [16:0] tmp_5_fu_278_p4;
wire   [7:0] tmp_4_fu_269_p4;
wire   [2:0] tmp_6_fu_287_p3;
wire   [0:0] and_ln61_fu_319_p2;
wire   [0:0] and_ln76_fu_323_p2;
wire   [0:0] xor_ln16_fu_328_p2;
wire   [0:0] and_ln16_1_fu_333_p2;
wire   [217:0] decoded_hit_event_1_fu_301_p10;
wire   [217:0] decoded_hit_event_fu_261_p3;
wire   [0:0] and_ln16_2_fu_352_p2;
wire   [0:0] xor_ln61_fu_347_p2;
wire   [0:0] or_ln16_fu_357_p2;
wire   [0:0] xor_ln76_fu_373_p2;
wire   [0:0] edge_slope_assignment_fault_fu_384_p2;
wire   [0:0] stop_channel_index_fault_fu_378_p2;
wire   [0:0] tdc_chip_index_fault_fu_368_p2;
wire   [0:0] contains_hit_event_fu_363_p2;
wire   [217:0] decoded_hit_event_2_fu_339_p3;
wire   [221:0] tmp_s_fu_389_p6;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    regslice_both_raw_event_in_U_apdone_blk;
wire   [215:0] raw_event_in_TDATA_int_regslice;
wire    raw_event_in_TVALID_int_regslice;
reg    raw_event_in_TREADY_int_regslice;
wire    regslice_both_raw_event_in_U_ack_in;
wire   [223:0] decoder_result_out_TDATA_int_regslice;
reg    decoder_result_out_TVALID_int_regslice;
wire    decoder_result_out_TREADY_int_regslice;
wire    regslice_both_decoder_result_out_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
end

gpx_hit_decoder_hls_regslice_both #(
    .DataWidth( 216 ))
regslice_both_raw_event_in_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(raw_event_in_TDATA),
    .vld_in(raw_event_in_TVALID),
    .ack_in(regslice_both_raw_event_in_U_ack_in),
    .data_out(raw_event_in_TDATA_int_regslice),
    .vld_out(raw_event_in_TVALID_int_regslice),
    .ack_out(raw_event_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_raw_event_in_U_apdone_blk)
);

gpx_hit_decoder_hls_regslice_both #(
    .DataWidth( 224 ))
regslice_both_decoder_result_out_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(decoder_result_out_TDATA_int_regslice),
    .vld_in(decoder_result_out_TVALID_int_regslice),
    .ack_in(decoder_result_out_TREADY_int_regslice),
    .data_out(decoder_result_out_TDATA),
    .vld_out(regslice_both_decoder_result_out_U_vld_out),
    .ack_out(decoder_result_out_TREADY),
    .apdone_blk(regslice_both_decoder_result_out_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        edge_slope_is_rise_reg_442 <= raw_event_in_TDATA_int_regslice[32'd22];
        icmp_ln16_reg_454 <= icmp_ln16_fu_239_p2;
        icmp_ln58_reg_423 <= icmp_ln58_fu_159_p2;
        icmp_ln61_reg_430 <= icmp_ln61_fu_165_p2;
        icmp_ln76_reg_447 <= icmp_ln76_fu_201_p2;
        ififo_bank_select_reg_418 <= raw_event_in_TDATA_int_regslice[32'd4];
        raw_event_reg_408 <= raw_event_in_TDATA_int_regslice;
        tmp_3_reg_436 <= {{raw_event_in_TDATA_int_regslice[32:31]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state3_pp0_stage0_iter2)) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter2_fsm_state3) | (1'b1 == ap_CS_iter1_fsm_state2))) begin
        decoder_result_out_TDATA_blk_n = decoder_result_out_TREADY_int_regslice;
    end else begin
        decoder_result_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        decoder_result_out_TVALID_int_regslice = 1'b1;
    end else begin
        decoder_result_out_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        raw_event_in_TDATA_blk_n = raw_event_in_TVALID_int_regslice;
    end else begin
        raw_event_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        raw_event_in_TREADY_int_regslice = 1'b1;
    end else begin
        raw_event_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter0_fsm_state1) & (1'b0 == ap_block_state1_pp0_stage0_iter0))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (1'b1 == ap_block_state1_pp0_stage0_iter0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if (((1'b1 == ap_CS_iter1_fsm_state2) & (1'b0 == ap_block_state3_pp0_stage0_iter2) & (1'b0 == ap_block_state2_pp0_stage0_iter1))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if (((1'b0 == ap_block_state3_pp0_stage0_iter2) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & (1'b1 == ap_block_state2_pp0_stage0_iter1))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_pp0_stage0_iter1) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_block_state3_pp0_stage0_iter2))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign and_ln16_1_fu_333_p2 = (xor_ln16_fu_328_p2 & and_ln76_fu_323_p2);

assign and_ln16_2_fu_352_p2 = (xor_ln16_fu_328_p2 & icmp_ln76_reg_447);

assign and_ln16_fu_233_p2 = (shl_ln16_fu_227_p2 & enabled_chip_mask_fu_215_p3);

assign and_ln61_fu_319_p2 = (icmp_ln61_reg_430 & icmp_ln58_reg_423);

assign and_ln76_fu_323_p2 = (icmp_ln76_reg_447 & and_ln61_fu_319_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (raw_event_in_TVALID_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (decoder_result_out_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_decoder_result_out_U_apdone_blk == 1'b1) | (decoder_result_out_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign contains_hit_event_fu_363_p2 = (or_ln16_fu_357_p2 & icmp_ln58_reg_423);

assign decoded_hit_event_1_fu_301_p10 = {{{{{{{{{tmp_7_fu_294_p3}, {tmp_5_fu_278_p4}}, {edge_slope_is_rise_reg_442}}, {tmp_4_fu_269_p4}}, {ififo_bank_select_reg_418}}, {tmp_3_reg_436}}, {tmp_3_reg_436}}, {tmp_6_fu_287_p3}}, {2'd0}};

assign decoded_hit_event_2_fu_339_p3 = ((and_ln16_1_fu_333_p2[0:0] == 1'b1) ? decoded_hit_event_1_fu_301_p10 : decoded_hit_event_fu_261_p3);

assign decoded_hit_event_fu_261_p3 = {{tmp_2_fu_245_p4}, {zext_ln32_fu_257_p1}};

assign decoder_result_out_TDATA_int_regslice = tmp_s_fu_389_p6;

assign decoder_result_out_TVALID = regslice_both_decoder_result_out_U_vld_out;

assign edge_slope_assignment_fault_fu_384_p2 = (icmp_ln16_reg_454 & and_ln76_fu_323_p2);

assign edge_slope_is_rise_fu_193_p3 = raw_event_in_TDATA_int_regslice[32'd22];

assign enabled_chip_mask_fu_215_p3 = ((edge_slope_is_rise_fu_193_p3[0:0] == 1'b1) ? trunc_ln13_fu_207_p1 : trunc_ln13_1_fu_211_p1);

assign icmp_ln16_fu_239_p2 = ((and_ln16_fu_233_p2 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_159_p2 = ((zext_ln30_fu_147_p1 < build_tdc_chip_count) ? 1'b1 : 1'b0);

assign icmp_ln61_fu_165_p2 = ((trunc_ln25_fu_135_p1 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln76_fu_201_p2 = ((zext_ln71_fu_189_p1 < build_stop_channels_per_chip) ? 1'b1 : 1'b0);

assign ififo_bank_select_fu_151_p3 = raw_event_in_TDATA_int_regslice[32'd4];

assign logical_stop_channel_index_fu_181_p3 = {{ififo_bank_select_fu_151_p3}, {tmp_3_fu_171_p4}};

assign or_ln16_fu_357_p2 = (xor_ln61_fu_347_p2 | and_ln16_2_fu_352_p2);

assign raw_event_in_TREADY = regslice_both_raw_event_in_U_ack_in;

assign shl_ln16_fu_227_p2 = 4'd1 << zext_ln16_fu_223_p1;

assign stop_channel_index_fault_fu_378_p2 = (xor_ln76_fu_373_p2 & and_ln61_fu_319_p2);

assign tdc_chip_index_fault_fu_368_p2 = (icmp_ln58_reg_423 ^ 1'd1);

assign tdc_chip_index_fu_139_p3 = {{raw_event_in_TDATA_int_regslice[3:2]}};

assign tmp_2_fu_245_p4 = {{raw_event_reg_408[214:33]}};

assign tmp_3_fu_171_p4 = {{raw_event_in_TDATA_int_regslice[32:31]}};

assign tmp_4_fu_269_p4 = {{raw_event_reg_408[30:23]}};

assign tmp_5_fu_278_p4 = {{raw_event_reg_408[21:5]}};

assign tmp_6_fu_287_p3 = {{raw_event_reg_408[4:2]}};

assign tmp_7_fu_294_p3 = {{raw_event_reg_408[214:33]}};

assign tmp_s_fu_389_p6 = {{{{{edge_slope_assignment_fault_fu_384_p2}, {stop_channel_index_fault_fu_378_p2}}, {tdc_chip_index_fault_fu_368_p2}}, {contains_hit_event_fu_363_p2}}, {decoded_hit_event_2_fu_339_p3}};

assign trunc_ln13_1_fu_211_p1 = runtime_enabled_fall_chip_mask[3:0];

assign trunc_ln13_fu_207_p1 = runtime_enabled_rise_chip_mask[3:0];

assign trunc_ln25_fu_135_p1 = raw_event_in_TDATA_int_regslice[1:0];

assign trunc_ln32_fu_254_p1 = raw_event_reg_408[4:0];

assign xor_ln16_fu_328_p2 = (icmp_ln16_reg_454 ^ 1'd1);

assign xor_ln61_fu_347_p2 = (icmp_ln61_reg_430 ^ 1'd1);

assign xor_ln76_fu_373_p2 = (icmp_ln76_reg_447 ^ 1'd1);

assign zext_ln16_fu_223_p1 = tdc_chip_index_fu_139_p3;

assign zext_ln30_fu_147_p1 = tdc_chip_index_fu_139_p3;

assign zext_ln32_fu_257_p1 = trunc_ln32_fu_254_p1;

assign zext_ln71_fu_189_p1 = logical_stop_channel_index_fu_181_p3;

endmodule //gpx_hit_decoder_hls
