// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1ns / 1ps

(* DowngradeIPIdentifiedWarnings="yes" *) module gpx_cell_collector_hls_bitselect_1ns_32ns_2ns_1_1_1 (sel,din,dout);

parameter ADDRWIDTH = 2;
parameter DATAWIDTH = 32;


input [ADDRWIDTH-1:0] sel;
input [DATAWIDTH-1:0] din;
output dout;

reg out_tmp;



always @ (*) begin
(* parallel_case *) case (sel)

0: out_tmp = din[0];

1: out_tmp = din[1];

2: out_tmp = din[2];

3: out_tmp = din[3];

default: out_tmp = 'bx;
endcase
end




assign dout = out_tmp;




endmodule
