-- ==============================================================
-- Generated by Vitis HLS v2025.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity gpx_frame_assembler_hls_gpx_frame_assembler_hls_Pipeline_VITIS_LOOP_719_3 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    empty_24 : IN STD_LOGIC_VECTOR (161 downto 0);
    max_count : IN STD_LOGIC_VECTOR (7 downto 0);
    fall_count : IN STD_LOGIC_VECTOR (7 downto 0);
    rise_count : IN STD_LOGIC_VECTOR (7 downto 0);
    build_stop_channels_per_chip : IN STD_LOGIC_VECTOR (7 downto 0);
    empty_25 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_26 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_27 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_28 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln732 : IN STD_LOGIC_VECTOR (31 downto 0);
    p_anonymous_namespace_shot_serialized_return_slots_load : IN STD_LOGIC_VECTOR (2 downto 0);
    gap_before : IN STD_LOGIC_VECTOR (15 downto 0);
    line_faulted : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_29 : IN STD_LOGIC_VECTOR (5 downto 0);
    ordered_rise_cell_out_TDATA : OUT STD_LOGIC_VECTOR (359 downto 0);
    ordered_rise_cell_out_TVALID : OUT STD_LOGIC;
    ordered_rise_cell_out_TREADY : IN STD_LOGIC;
    empty_30 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_31 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_32 : IN STD_LOGIC_VECTOR (0 downto 0);
    empty_33 : IN STD_LOGIC_VECTOR (0 downto 0);
    zext_ln751 : IN STD_LOGIC_VECTOR (31 downto 0);
    empty : IN STD_LOGIC_VECTOR (5 downto 0);
    ordered_fall_cell_out_TDATA : OUT STD_LOGIC_VECTOR (359 downto 0);
    ordered_fall_cell_out_TVALID : OUT STD_LOGIC;
    ordered_fall_cell_out_TREADY : IN STD_LOGIC;
    p_out : OUT STD_LOGIC_VECTOR (161 downto 0);
    p_out_ap_vld : OUT STD_LOGIC;
    p_anonymous_namespace_rise_cells_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    p_anonymous_namespace_rise_cells_ce0 : OUT STD_LOGIC;
    p_anonymous_namespace_rise_cells_q0 : IN STD_LOGIC_VECTOR (147 downto 0);
    p_anonymous_namespace_fall_cells_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    p_anonymous_namespace_fall_cells_ce0 : OUT STD_LOGIC;
    p_anonymous_namespace_fall_cells_q0 : IN STD_LOGIC_VECTOR (147 downto 0) );
end;


architecture behav of gpx_frame_assembler_hls_gpx_frame_assembler_hls_Pipeline_VITIS_LOOP_719_3 is 
    attribute DowngradeIPIdentifiedWarnings : STRING;
    attribute DowngradeIPIdentifiedWarnings of behav : architecture is "yes";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_84 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000100";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_83 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000011";
    constant ap_const_lv32_77 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110111";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv126_6000000000000000000000000000000 : STD_LOGIC_VECTOR (125 downto 0) := "000110000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv32_14 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_89 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001001";
    constant ap_const_lv32_88 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ordered_rise_cell_out_TDATA_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal icmp_ln723_reg_1375 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln723_reg_1375_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp1_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ordered_fall_cell_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp2 : BOOLEAN;
    signal icmp_ln743_reg_1401 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln743_reg_1401_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0_subdone_grp2_done_reg : BOOLEAN := false;
    signal ap_block_pp0_stage0_subdone_grp2 : BOOLEAN;
    signal zext_ln751_cast_fu_367_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln751_cast_reg_1362 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln732_cast_fu_371_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln732_cast_reg_1367 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln723_fu_399_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_predicate_op174_write_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6_grp1 : BOOLEAN;
    signal ap_predicate_op185_write_state8 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6_grp2 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln723_reg_1375_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln723_reg_1375_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln723_reg_1375_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln723_reg_1375_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_fu_404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln724_reg_1379_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal slot_5_fu_409_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_5_reg_1383 : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_5_reg_1383_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_5_reg_1383_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_5_reg_1383_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_5_reg_1383_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln728_fu_413_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln728_reg_1389 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln728_reg_1389_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln728_reg_1389_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_1_fu_417_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_1_reg_1396 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln743_fu_422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln743_reg_1401_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln743_reg_1401_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln743_reg_1401_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln743_reg_1401_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal slot_6_fu_427_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_6_reg_1405 : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_6_reg_1405_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_6_reg_1405_pp0_iter2_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_6_reg_1405_pp0_iter3_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal slot_6_reg_1405_pp0_iter4_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln747_fu_431_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln747_reg_1411 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln747_reg_1411_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln747_reg_1411_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_9_fu_435_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_9_reg_1418 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_2_fu_445_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_2_reg_1423 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal remaining_2_reg_1423_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_3_fu_455_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_3_reg_1429 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_3_reg_1429_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_11_fu_462_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_11_reg_1437 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_11001_grp2 : BOOLEAN;
    signal remaining_11_reg_1437_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_8_fu_472_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_8_reg_1443 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_8_reg_1443_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_5_fu_491_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_5_reg_1451 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln73_3_fu_497_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_3_reg_1456 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_reg_1461 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_1_fu_507_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_1_reg_1468 : STD_LOGIC_VECTOR (0 downto 0);
    signal remaining_10_fu_524_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_10_reg_1474 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln73_7_fu_530_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_7_reg_1479 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_5_fu_535_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_5_reg_1484 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_6_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_6_reg_1491 : STD_LOGIC_VECTOR (0 downto 0);
    signal address_chip_fu_629_p11 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_reg_1497 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_reg_1497_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln45_fu_653_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln45_reg_1504 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_11_reg_1509 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln32_fu_667_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln32_reg_1514 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln32_reg_1514_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p11 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_1_reg_1520 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_1_reg_1520_pp0_iter4_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln45_1_fu_779_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln45_1_reg_1527 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_18_reg_1532 : STD_LOGIC_VECTOR (5 downto 0);
    signal trunc_ln32_1_fu_793_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln32_1_reg_1537 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln32_1_reg_1537_pp0_iter4_reg : STD_LOGIC_VECTOR (2 downto 0);
    signal present_fu_818_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_reg_1543 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_reg_1543_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal value_fu_825_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_reg_1554 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_1_fu_851_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_1_reg_1560 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_1_reg_1560_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal value_7_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_7_reg_1571 : STD_LOGIC_VECTOR (0 downto 0);
    signal cell_2_fu_934_p3 : STD_LOGIC_VECTOR (318 downto 0);
    signal cell_2_reg_1577 : STD_LOGIC_VECTOR (318 downto 0);
    signal zext_ln32_fu_941_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln32_reg_1584 : STD_LOGIC_VECTOR (5 downto 0);
    signal value_1_fu_944_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_1_reg_1589 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_2_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_2_reg_1595 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_3_fu_971_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_3_reg_1600 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_4_reg_1605 : STD_LOGIC_VECTOR (0 downto 0);
    signal cell_5_fu_1055_p3 : STD_LOGIC_VECTOR (318 downto 0);
    signal cell_5_reg_1610 : STD_LOGIC_VECTOR (318 downto 0);
    signal zext_ln32_1_fu_1062_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln32_1_reg_1617 : STD_LOGIC_VECTOR (5 downto 0);
    signal value_8_fu_1065_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_8_reg_1622 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_9_fu_1080_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_9_reg_1628 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_10_fu_1092_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_10_reg_1633 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_11_reg_1638 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal icmp_ln720_fu_383_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal zext_ln732_1_fu_813_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln751_1_fu_846_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal slot_fu_196 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal slot_4_fu_389_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_01001_grp2 : BOOLEAN;
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal p_anonymous_namespace_rise_cells_ce0_local : STD_LOGIC;
    signal p_anonymous_namespace_fall_cells_ce0_local : STD_LOGIC;
    signal zext_ln720_fu_395_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_4_fu_450_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_12_fu_467_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal remaining_6_fu_487_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln73_fu_479_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_1_fu_483_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal remaining_13_fu_520_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln73_4_fu_512_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_5_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln72_fu_549_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_fu_578_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_2_fu_545_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_1_fu_582_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_3_fu_588_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_2_fu_573_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_4_fu_594_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal address_stop_fu_608_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal address_stop_fu_608_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp1_fu_599_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_fu_629_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_fu_629_p9 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_stop_fu_608_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal and_ln72_1_fu_675_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_2_fu_694_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln73_1_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln73_6_fu_671_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln73_3_fu_708_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_8_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_7_fu_699_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln73_9_fu_720_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal address_stop_1_fu_734_p8 : STD_LOGIC_VECTOR (7 downto 0);
    signal address_stop_1_fu_734_p9 : STD_LOGIC_VECTOR (7 downto 0);
    signal sel_tmp2_fu_725_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p8 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_chip_1_fu_755_p9 : STD_LOGIC_VECTOR (1 downto 0);
    signal address_stop_1_fu_734_p11 : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln46_cast_fu_797_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln46_fu_804_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal linear_fu_808_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln46_1_cast_fu_830_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln46_1_fu_837_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal linear_1_fu_841_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_s_fu_867_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_12_fu_875_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln25_fu_863_p1 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_13_fu_885_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal cell_1_fu_915_p9 : STD_LOGIC_VECTOR (302 downto 0);
    signal cell_fu_895_p11 : STD_LOGIC_VECTOR (318 downto 0);
    signal zext_ln48_fu_930_p1 : STD_LOGIC_VECTOR (318 downto 0);
    signal add_ln288_fu_949_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln288_fu_955_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_14_fu_964_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_19_fu_988_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_20_fu_996_p4 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln25_1_fu_984_p1 : STD_LOGIC_VECTOR (118 downto 0);
    signal tmp_21_fu_1006_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal cell_4_fu_1036_p9 : STD_LOGIC_VECTOR (302 downto 0);
    signal cell_3_fu_1016_p11 : STD_LOGIC_VECTOR (318 downto 0);
    signal zext_ln48_2_fu_1051_p1 : STD_LOGIC_VECTOR (318 downto 0);
    signal add_ln288_1_fu_1070_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln288_1_fu_1076_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_22_fu_1085_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_16_fu_1116_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_5_fu_1111_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_fu_1130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_1_fu_1136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_1123_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_6_fu_1141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln32_fu_1105_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_15_fu_1147_p11 : STD_LOGIC_VECTOR (352 downto 0);
    signal tmp_24_fu_1180_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_12_fu_1175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_2_fu_1194_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln40_3_fu_1200_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_fu_1187_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal value_13_fu_1205_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln32_1_fu_1169_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_23_fu_1211_p11 : STD_LOGIC_VECTOR (352 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal address_stop_fu_608_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_fu_608_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_fu_608_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_fu_608_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_fu_629_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_fu_629_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_fu_629_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_fu_629_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_1_fu_734_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_1_fu_734_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_1_fu_734_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_stop_1_fu_734_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p5 : STD_LOGIC_VECTOR (2 downto 0);
    signal address_chip_1_fu_755_p7 : STD_LOGIC_VECTOR (2 downto 0);
    signal present_fu_818_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal present_1_fu_851_p0 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component gpx_frame_assembler_hls_sparsemux_9_3_8_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        din3 : IN STD_LOGIC_VECTOR (7 downto 0);
        def : IN STD_LOGIC_VECTOR (7 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component gpx_frame_assembler_hls_sparsemux_9_3_2_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (2 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (2 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (2 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (2 downto 0);
        din3_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (1 downto 0);
        din1 : IN STD_LOGIC_VECTOR (1 downto 0);
        din2 : IN STD_LOGIC_VECTOR (1 downto 0);
        din3 : IN STD_LOGIC_VECTOR (1 downto 0);
        def : IN STD_LOGIC_VECTOR (1 downto 0);
        sel : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component gpx_frame_assembler_hls_bitselect_1ns_64ns_6ns_1_1_1 IS
    generic (
        DATAWIDTH : INTEGER;
        ADDRWIDTH : INTEGER );
    port (
        din : IN STD_LOGIC_VECTOR (63 downto 0);
        sel : IN STD_LOGIC_VECTOR (5 downto 0);
        dout : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;



begin
    sparsemux_9_3_8_1_1_U1 : component gpx_frame_assembler_hls_sparsemux_9_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 8,
        CASE1 => "010",
        din1_WIDTH => 8,
        CASE2 => "001",
        din2_WIDTH => 8,
        CASE3 => "000",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => zext_ln728_reg_1389_pp0_iter2_reg,
        din1 => remaining_2_reg_1423_pp0_iter2_reg,
        din2 => remaining_3_reg_1429_pp0_iter2_reg,
        din3 => address_stop_fu_608_p8,
        def => address_stop_fu_608_p9,
        sel => sel_tmp1_fu_599_p4,
        dout => address_stop_fu_608_p11);

    sparsemux_9_3_2_1_1_U2 : component gpx_frame_assembler_hls_sparsemux_9_3_2_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 2,
        CASE1 => "010",
        din1_WIDTH => 2,
        CASE2 => "001",
        din2_WIDTH => 2,
        CASE3 => "000",
        din3_WIDTH => 2,
        def_WIDTH => 2,
        sel_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        din0 => ap_const_lv2_0,
        din1 => ap_const_lv2_1,
        din2 => ap_const_lv2_2,
        din3 => address_chip_fu_629_p8,
        def => address_chip_fu_629_p9,
        sel => sel_tmp1_fu_599_p4,
        dout => address_chip_fu_629_p11);

    sparsemux_9_3_8_1_1_U3 : component gpx_frame_assembler_hls_sparsemux_9_3_8_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 8,
        CASE1 => "010",
        din1_WIDTH => 8,
        CASE2 => "001",
        din2_WIDTH => 8,
        CASE3 => "000",
        din3_WIDTH => 8,
        def_WIDTH => 8,
        sel_WIDTH => 3,
        dout_WIDTH => 8)
    port map (
        din0 => zext_ln747_reg_1411_pp0_iter2_reg,
        din1 => remaining_11_reg_1437_pp0_iter2_reg,
        din2 => remaining_8_reg_1443_pp0_iter2_reg,
        din3 => address_stop_1_fu_734_p8,
        def => address_stop_1_fu_734_p9,
        sel => sel_tmp2_fu_725_p4,
        dout => address_stop_1_fu_734_p11);

    sparsemux_9_3_2_1_1_U4 : component gpx_frame_assembler_hls_sparsemux_9_3_2_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "100",
        din0_WIDTH => 2,
        CASE1 => "010",
        din1_WIDTH => 2,
        CASE2 => "001",
        din2_WIDTH => 2,
        CASE3 => "000",
        din3_WIDTH => 2,
        def_WIDTH => 2,
        sel_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        din0 => ap_const_lv2_0,
        din1 => ap_const_lv2_1,
        din2 => ap_const_lv2_2,
        din3 => address_chip_1_fu_755_p8,
        def => address_chip_1_fu_755_p9,
        sel => sel_tmp2_fu_725_p4,
        dout => address_chip_1_fu_755_p11);

    bitselect_1ns_64ns_6ns_1_1_1_U5 : component gpx_frame_assembler_hls_bitselect_1ns_64ns_6ns_1_1_1
    generic map (
        DATAWIDTH => 64,
        ADDRWIDTH => 6)
    port map (
        din => zext_ln732_cast_reg_1367,
        sel => linear_fu_808_p2,
        dout => present_fu_818_p3);

    bitselect_1ns_64ns_6ns_1_1_1_U6 : component gpx_frame_assembler_hls_bitselect_1ns_64ns_6ns_1_1_1
    generic map (
        DATAWIDTH => 64,
        ADDRWIDTH => 6)
    port map (
        din => zext_ln751_cast_reg_1362,
        sel => linear_1_fu_841_p2,
        dout => present_1_fu_851_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp1_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1)) then 
                    ap_block_pp0_stage0_subdone_grp1_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_block_pp0_stage0_subdone_grp2_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2)) then 
                    ap_block_pp0_stage0_subdone_grp2_done_reg <= ap_const_boolean_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    slot_fu_196_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                slot_fu_196 <= ap_const_lv6_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln720_fu_383_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                slot_fu_196 <= slot_4_fu_389_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2))) then
                address_chip_1_reg_1520 <= address_chip_1_fu_755_p11;
                address_chip_1_reg_1520_pp0_iter4_reg <= address_chip_1_reg_1520;
                and_ln73_5_reg_1484 <= and_ln73_5_fu_535_p2;
                and_ln73_6_reg_1491 <= and_ln73_6_fu_540_p2;
                    cell_5_reg_1610(7 downto 2) <= cell_5_fu_1055_p3(7 downto 2);    cell_5_reg_1610(318 downto 9) <= cell_5_fu_1055_p3(318 downto 9);
                icmp_ln73_7_reg_1479 <= icmp_ln73_7_fu_530_p2;
                present_1_reg_1560 <= present_1_fu_851_p3;
                present_1_reg_1560_pp0_iter5_reg <= present_1_reg_1560;
                remaining_10_reg_1474 <= remaining_10_fu_524_p3;
                remaining_11_reg_1437_pp0_iter2_reg <= remaining_11_reg_1437;
                remaining_8_reg_1443_pp0_iter2_reg <= remaining_8_reg_1443;
                tmp_18_reg_1532 <= address_stop_1_fu_734_p11(7 downto 2);
                trunc_ln32_1_reg_1537 <= trunc_ln32_1_fu_793_p1;
                trunc_ln32_1_reg_1537_pp0_iter4_reg <= trunc_ln32_1_reg_1537;
                trunc_ln45_1_reg_1527 <= trunc_ln45_1_fu_779_p1;
                value_10_reg_1633 <= value_10_fu_1092_p2;
                value_11_reg_1638 <= empty_24(36 downto 36);
                value_7_reg_1571 <= value_7_fu_858_p2;
                value_8_reg_1622 <= value_8_fu_1065_p2;
                value_9_reg_1628 <= value_9_fu_1080_p2;
                    zext_ln32_1_reg_1617(4 downto 0) <= zext_ln32_1_fu_1062_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                address_chip_reg_1497 <= address_chip_fu_629_p11;
                address_chip_reg_1497_pp0_iter4_reg <= address_chip_reg_1497;
                and_ln73_1_reg_1468 <= and_ln73_1_fu_507_p2;
                and_ln73_reg_1461 <= and_ln73_fu_502_p2;
                    cell_2_reg_1577(7 downto 2) <= cell_2_fu_934_p3(7 downto 2);    cell_2_reg_1577(318 downto 9) <= cell_2_fu_934_p3(318 downto 9);
                icmp_ln73_3_reg_1456 <= icmp_ln73_3_fu_497_p2;
                present_reg_1543 <= present_fu_818_p3;
                present_reg_1543_pp0_iter5_reg <= present_reg_1543;
                remaining_2_reg_1423_pp0_iter2_reg <= remaining_2_reg_1423;
                remaining_3_reg_1429_pp0_iter2_reg <= remaining_3_reg_1429;
                remaining_5_reg_1451 <= remaining_5_fu_491_p3;
                tmp_11_reg_1509 <= address_stop_fu_608_p11(7 downto 2);
                trunc_ln32_reg_1514 <= trunc_ln32_fu_667_p1;
                trunc_ln32_reg_1514_pp0_iter4_reg <= trunc_ln32_reg_1514;
                trunc_ln45_reg_1504 <= trunc_ln45_fu_653_p1;
                value_1_reg_1589 <= value_1_fu_944_p2;
                value_2_reg_1595 <= value_2_fu_959_p2;
                value_3_reg_1600 <= value_3_fu_971_p2;
                value_4_reg_1605 <= empty_24(36 downto 36);
                value_reg_1554 <= value_fu_825_p2;
                    zext_ln32_reg_1584(4 downto 0) <= zext_ln32_fu_941_p1(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln723_reg_1375 <= icmp_ln723_fu_399_p2;
                icmp_ln723_reg_1375_pp0_iter1_reg <= icmp_ln723_reg_1375;
                icmp_ln724_reg_1379 <= icmp_ln724_fu_404_p2;
                icmp_ln724_reg_1379_pp0_iter1_reg <= icmp_ln724_reg_1379;
                icmp_ln743_reg_1401 <= icmp_ln743_fu_422_p2;
                icmp_ln743_reg_1401_pp0_iter1_reg <= icmp_ln743_reg_1401;
                remaining_1_reg_1396 <= remaining_1_fu_417_p2;
                remaining_9_reg_1418 <= remaining_9_fu_435_p2;
                slot_5_reg_1383 <= slot_5_fu_409_p1;
                slot_5_reg_1383_pp0_iter1_reg <= slot_5_reg_1383;
                slot_6_reg_1405 <= slot_6_fu_427_p1;
                slot_6_reg_1405_pp0_iter1_reg <= slot_6_reg_1405;
                    zext_ln728_reg_1389(4 downto 0) <= zext_ln728_fu_413_p1(4 downto 0);
                    zext_ln728_reg_1389_pp0_iter1_reg(4 downto 0) <= zext_ln728_reg_1389(4 downto 0);
                    zext_ln747_reg_1411(4 downto 0) <= zext_ln747_fu_431_p1(4 downto 0);
                    zext_ln747_reg_1411_pp0_iter1_reg(4 downto 0) <= zext_ln747_reg_1411(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                icmp_ln723_reg_1375_pp0_iter2_reg <= icmp_ln723_reg_1375_pp0_iter1_reg;
                icmp_ln723_reg_1375_pp0_iter3_reg <= icmp_ln723_reg_1375_pp0_iter2_reg;
                icmp_ln723_reg_1375_pp0_iter4_reg <= icmp_ln723_reg_1375_pp0_iter3_reg;
                icmp_ln723_reg_1375_pp0_iter5_reg <= icmp_ln723_reg_1375_pp0_iter4_reg;
                icmp_ln724_reg_1379_pp0_iter2_reg <= icmp_ln724_reg_1379_pp0_iter1_reg;
                icmp_ln724_reg_1379_pp0_iter3_reg <= icmp_ln724_reg_1379_pp0_iter2_reg;
                icmp_ln724_reg_1379_pp0_iter4_reg <= icmp_ln724_reg_1379_pp0_iter3_reg;
                icmp_ln724_reg_1379_pp0_iter5_reg <= icmp_ln724_reg_1379_pp0_iter4_reg;
                icmp_ln743_reg_1401_pp0_iter2_reg <= icmp_ln743_reg_1401_pp0_iter1_reg;
                icmp_ln743_reg_1401_pp0_iter3_reg <= icmp_ln743_reg_1401_pp0_iter2_reg;
                icmp_ln743_reg_1401_pp0_iter4_reg <= icmp_ln743_reg_1401_pp0_iter3_reg;
                icmp_ln743_reg_1401_pp0_iter5_reg <= icmp_ln743_reg_1401_pp0_iter4_reg;
                slot_5_reg_1383_pp0_iter2_reg <= slot_5_reg_1383_pp0_iter1_reg;
                slot_5_reg_1383_pp0_iter3_reg <= slot_5_reg_1383_pp0_iter2_reg;
                slot_5_reg_1383_pp0_iter4_reg <= slot_5_reg_1383_pp0_iter3_reg;
                slot_6_reg_1405_pp0_iter2_reg <= slot_6_reg_1405_pp0_iter1_reg;
                slot_6_reg_1405_pp0_iter3_reg <= slot_6_reg_1405_pp0_iter2_reg;
                slot_6_reg_1405_pp0_iter4_reg <= slot_6_reg_1405_pp0_iter3_reg;
                    zext_ln728_reg_1389_pp0_iter2_reg(4 downto 0) <= zext_ln728_reg_1389_pp0_iter1_reg(4 downto 0);
                    zext_ln747_reg_1411_pp0_iter2_reg(4 downto 0) <= zext_ln747_reg_1411_pp0_iter1_reg(4 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                remaining_11_reg_1437 <= remaining_11_fu_462_p3;
                remaining_8_reg_1443 <= remaining_8_fu_472_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                remaining_2_reg_1423 <= remaining_2_fu_445_p3;
                remaining_3_reg_1429 <= remaining_3_fu_455_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                    zext_ln732_cast_reg_1367(31 downto 0) <= zext_ln732_cast_fu_371_p1(31 downto 0);
                    zext_ln751_cast_reg_1362(31 downto 0) <= zext_ln751_cast_fu_367_p1(31 downto 0);
            end if;
        end if;
    end process;
    zext_ln751_cast_reg_1362(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln732_cast_reg_1367(63 downto 32) <= "00000000000000000000000000000000";
    zext_ln728_reg_1389(7 downto 5) <= "000";
    zext_ln728_reg_1389_pp0_iter1_reg(7 downto 5) <= "000";
    zext_ln728_reg_1389_pp0_iter2_reg(7 downto 5) <= "000";
    zext_ln747_reg_1411(7 downto 5) <= "000";
    zext_ln747_reg_1411_pp0_iter1_reg(7 downto 5) <= "000";
    zext_ln747_reg_1411_pp0_iter2_reg(7 downto 5) <= "000";
    cell_2_reg_1577(1 downto 0) <= "00";
    cell_2_reg_1577(8) <= '1';
    zext_ln32_reg_1584(5) <= '0';
    cell_5_reg_1610(1 downto 0) <= "00";
    cell_5_reg_1610(8) <= '0';
    zext_ln32_1_reg_1617(5) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter0, icmp_ln720_fu_383_p2, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter5)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln720_fu_383_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (icmp_ln720_fu_383_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln288_1_fu_1070_p2 <= std_logic_vector(unsigned(zext_ln32_1_fu_1062_p1) + unsigned(ap_const_lv6_1));
    add_ln288_fu_949_p2 <= std_logic_vector(unsigned(zext_ln32_fu_941_p1) + unsigned(ap_const_lv6_1));
    address_chip_1_fu_755_p8 <= 
        ap_const_lv2_3 when (and_ln72_1_fu_675_p2(0) = '1') else 
        ap_const_lv2_0;
    address_chip_1_fu_755_p9 <= "XX";
    address_chip_fu_629_p8 <= 
        ap_const_lv2_3 when (and_ln72_fu_549_p2(0) = '1') else 
        ap_const_lv2_0;
    address_chip_fu_629_p9 <= "XX";
    address_stop_1_fu_734_p8 <= 
        remaining_10_reg_1474 when (and_ln72_1_fu_675_p2(0) = '1') else 
        ap_const_lv8_0;
    address_stop_1_fu_734_p9 <= "XXXXXXXX";
    address_stop_fu_608_p8 <= 
        remaining_5_reg_1451 when (and_ln72_fu_549_p2(0) = '1') else 
        ap_const_lv8_0;
    address_stop_fu_608_p9 <= "XXXXXXXX";
    and_ln72_1_fu_675_p2 <= (icmp_ln73_7_reg_1479 and empty_33);
    and_ln72_fu_549_p2 <= (icmp_ln73_3_reg_1456 and empty_28);
    and_ln73_1_fu_507_p2 <= (icmp_ln73_1_fu_483_p2 and empty_26);
    and_ln73_2_fu_573_p2 <= (xor_ln73_fu_568_p2 and and_ln73_1_reg_1468);
    and_ln73_3_fu_588_p2 <= (xor_ln73_1_fu_582_p2 and icmp_ln73_2_fu_545_p2);
    and_ln73_4_fu_594_p2 <= (empty_27 and and_ln73_3_fu_588_p2);
    and_ln73_5_fu_535_p2 <= (icmp_ln73_4_fu_512_p2 and empty_30);
    and_ln73_6_fu_540_p2 <= (icmp_ln73_5_fu_516_p2 and empty_31);
    and_ln73_7_fu_699_p2 <= (xor_ln73_2_fu_694_p2 and and_ln73_6_reg_1491);
    and_ln73_8_fu_714_p2 <= (xor_ln73_3_fu_708_p2 and icmp_ln73_6_fu_671_p2);
    and_ln73_9_fu_720_p2 <= (empty_32 and and_ln73_8_fu_714_p2);
    and_ln73_fu_502_p2 <= (icmp_ln73_fu_479_p2 and empty_25);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state11 <= ap_CS_fsm(4);
    ap_CS_fsm_state9 <= ap_CS_fsm(2);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state8_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp1));
    end process;


    ap_block_pp0_stage0_01001_grp2_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state8_pp0_stage0_iter6_grp2)
    begin
                ap_block_pp0_stage0_01001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp2));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state8_pp0_stage0_iter6_grp1, ap_block_state8_pp0_stage0_iter6_grp2)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp2))));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state8_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp1));
    end process;


    ap_block_pp0_stage0_11001_grp2_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state8_pp0_stage0_iter6_grp2)
    begin
                ap_block_pp0_stage0_11001_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp2));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_grp2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state8_pp0_stage0_iter6_grp1, ap_block_state8_pp0_stage0_iter6_grp2)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp2))));
    end process;


    ap_block_pp0_stage0_subdone_grp1_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_state8_pp0_stage0_iter6_grp1)
    begin
                ap_block_pp0_stage0_subdone_grp1 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp1));
    end process;


    ap_block_pp0_stage0_subdone_grp2_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_state8_pp0_stage0_iter6_grp2)
    begin
                ap_block_pp0_stage0_subdone_grp2 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state8_pp0_stage0_iter6_grp2));
    end process;


    ap_block_state8_pp0_stage0_iter6_grp1_assign_proc : process(ordered_rise_cell_out_TREADY, ap_predicate_op174_write_state8)
    begin
                ap_block_state8_pp0_stage0_iter6_grp1 <= ((ordered_rise_cell_out_TREADY = ap_const_logic_0) and (ap_predicate_op174_write_state8 = ap_const_boolean_1));
    end process;


    ap_block_state8_pp0_stage0_iter6_grp2_assign_proc : process(ordered_fall_cell_out_TREADY, ap_predicate_op185_write_state8)
    begin
                ap_block_state8_pp0_stage0_iter6_grp2 <= ((ordered_fall_cell_out_TREADY = ap_const_logic_0) and (ap_predicate_op185_write_state8 = ap_const_boolean_1));
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln720_fu_383_p2)
    begin
        if ((icmp_ln720_fu_383_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5)
    begin
        if (((ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op174_write_state8_assign_proc : process(icmp_ln723_reg_1375_pp0_iter5_reg, icmp_ln724_reg_1379_pp0_iter5_reg)
    begin
                ap_predicate_op174_write_state8 <= ((icmp_ln724_reg_1379_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln723_reg_1375_pp0_iter5_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op185_write_state8_assign_proc : process(icmp_ln723_reg_1375_pp0_iter5_reg, icmp_ln743_reg_1401_pp0_iter5_reg)
    begin
                ap_predicate_op185_write_state8 <= ((icmp_ln743_reg_1401_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln723_reg_1375_pp0_iter5_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    cell_1_fu_915_p9 <= (((((((empty_24 & ap_const_lv126_6000000000000000000000000000000) & p_anonymous_namespace_shot_serialized_return_slots_load) & ap_const_lv4_1) & trunc_ln32_reg_1514_pp0_iter4_reg) & value_reg_1554) & address_chip_reg_1497_pp0_iter4_reg) & ap_const_lv2_0);
    cell_2_fu_934_p3 <= 
        cell_fu_895_p11 when (present_reg_1543(0) = '1') else 
        zext_ln48_fu_930_p1;
    cell_3_fu_1016_p11 <= (((((((((tmp_19_fu_988_p3 & empty_24) & tmp_20_fu_996_p4) & trunc_ln25_1_fu_984_p1) & tmp_21_fu_1006_p4) & ap_const_lv1_0) & trunc_ln32_1_reg_1537_pp0_iter4_reg) & value_7_reg_1571) & address_chip_1_reg_1520_pp0_iter4_reg) & ap_const_lv2_0);
    cell_4_fu_1036_p9 <= (((((((empty_24 & ap_const_lv126_6000000000000000000000000000000) & p_anonymous_namespace_shot_serialized_return_slots_load) & ap_const_lv4_0) & trunc_ln32_1_reg_1537_pp0_iter4_reg) & value_7_reg_1571) & address_chip_1_reg_1520_pp0_iter4_reg) & ap_const_lv2_0);
    cell_5_fu_1055_p3 <= 
        cell_3_fu_1016_p11 when (present_1_reg_1560(0) = '1') else 
        zext_ln48_2_fu_1051_p1;
    cell_fu_895_p11 <= (((((((((tmp_s_fu_867_p3 & empty_24) & tmp_12_fu_875_p4) & trunc_ln25_fu_863_p1) & tmp_13_fu_885_p4) & ap_const_lv1_1) & trunc_ln32_reg_1514_pp0_iter4_reg) & value_reg_1554) & address_chip_reg_1497_pp0_iter4_reg) & ap_const_lv2_0);
    icmp_ln720_fu_383_p2 <= "1" when (slot_fu_196 = ap_const_lv6_20) else "0";
    icmp_ln723_fu_399_p2 <= "1" when (unsigned(zext_ln720_fu_395_p1) < unsigned(max_count)) else "0";
    icmp_ln724_fu_404_p2 <= "1" when (unsigned(zext_ln720_fu_395_p1) < unsigned(rise_count)) else "0";
    icmp_ln73_1_fu_483_p2 <= "1" when (unsigned(remaining_2_reg_1423) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_2_fu_545_p2 <= "1" when (unsigned(remaining_3_reg_1429_pp0_iter2_reg) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_3_fu_497_p2 <= "1" when (unsigned(remaining_5_fu_491_p3) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_4_fu_512_p2 <= "1" when (unsigned(zext_ln747_reg_1411_pp0_iter1_reg) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_5_fu_516_p2 <= "1" when (unsigned(remaining_11_reg_1437) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_6_fu_671_p2 <= "1" when (unsigned(remaining_8_reg_1443_pp0_iter2_reg) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_7_fu_530_p2 <= "1" when (unsigned(remaining_10_fu_524_p3) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln73_fu_479_p2 <= "1" when (unsigned(zext_ln728_reg_1389_pp0_iter1_reg) < unsigned(build_stop_channels_per_chip)) else "0";
    icmp_ln743_fu_422_p2 <= "1" when (unsigned(zext_ln720_fu_395_p1) < unsigned(fall_count)) else "0";
    linear_1_fu_841_p2 <= std_logic_vector(unsigned(zext_ln46_1_fu_837_p1) + unsigned(trunc_ln45_1_reg_1527));
    linear_fu_808_p2 <= std_logic_vector(unsigned(zext_ln46_fu_804_p1) + unsigned(trunc_ln45_reg_1504));
    or_ln40_1_fu_1136_p2 <= (or_ln40_fu_1130_p2 or line_faulted);
    or_ln40_2_fu_1194_p2 <= (value_12_fu_1175_p2 or tmp_24_fu_1180_p3);
    or_ln40_3_fu_1200_p2 <= (or_ln40_2_fu_1194_p2 or line_faulted);
    or_ln40_fu_1130_p2 <= (value_5_fu_1111_p2 or tmp_16_fu_1116_p3);
    or_ln73_1_fu_704_p2 <= (and_ln73_6_reg_1491 or and_ln73_5_reg_1484);
    or_ln73_fu_578_p2 <= (and_ln73_reg_1461 or and_ln73_1_reg_1468);
    ordered_fall_cell_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_23_fu_1211_p11),360));

    ordered_fall_cell_out_TDATA_blk_n_assign_proc : process(ordered_fall_cell_out_TREADY, ap_enable_reg_pp0_iter6, icmp_ln723_reg_1375_pp0_iter5_reg, ap_block_pp0_stage0_grp2, icmp_ln743_reg_1401_pp0_iter5_reg, ap_block_pp0_stage0_subdone_grp2_done_reg)
    begin
        if (((icmp_ln743_reg_1401_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln723_reg_1375_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp2) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ordered_fall_cell_out_TDATA_blk_n <= ordered_fall_cell_out_TREADY;
        else 
            ordered_fall_cell_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ordered_fall_cell_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp2_done_reg, ap_predicate_op185_write_state8, ap_block_pp0_stage0_11001_grp2)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_predicate_op185_write_state8 = ap_const_boolean_1))) then 
            ordered_fall_cell_out_TVALID <= ap_const_logic_1;
        else 
            ordered_fall_cell_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    ordered_rise_cell_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_1147_p11),360));

    ordered_rise_cell_out_TDATA_blk_n_assign_proc : process(ordered_rise_cell_out_TREADY, ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_grp1, icmp_ln723_reg_1375_pp0_iter5_reg, icmp_ln724_reg_1379_pp0_iter5_reg, ap_block_pp0_stage0_subdone_grp1_done_reg)
    begin
        if (((icmp_ln724_reg_1379_pp0_iter5_reg = ap_const_lv1_1) and (icmp_ln723_reg_1375_pp0_iter5_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1))) then 
            ordered_rise_cell_out_TDATA_blk_n <= ordered_rise_cell_out_TREADY;
        else 
            ordered_rise_cell_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ordered_rise_cell_out_TVALID_assign_proc : process(ap_enable_reg_pp0_iter6, ap_block_pp0_stage0_subdone_grp1_done_reg, ap_predicate_op174_write_state8, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter6 = ap_const_logic_1) and (ap_predicate_op174_write_state8 = ap_const_boolean_1))) then 
            ordered_rise_cell_out_TVALID <= ap_const_logic_1;
        else 
            ordered_rise_cell_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_fall_cells_address0 <= zext_ln751_1_fu_846_p1(5 - 1 downto 0);
    p_anonymous_namespace_fall_cells_ce0 <= p_anonymous_namespace_fall_cells_ce0_local;

    p_anonymous_namespace_fall_cells_ce0_local_assign_proc : process(ap_block_pp0_stage0_subdone_grp2_done_reg, ap_block_pp0_stage0_11001_grp2, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp2_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp2) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_anonymous_namespace_fall_cells_ce0_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_fall_cells_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_anonymous_namespace_rise_cells_address0 <= zext_ln732_1_fu_813_p1(5 - 1 downto 0);
    p_anonymous_namespace_rise_cells_ce0 <= p_anonymous_namespace_rise_cells_ce0_local;

    p_anonymous_namespace_rise_cells_ce0_local_assign_proc : process(ap_block_pp0_stage0_subdone_grp1_done_reg, ap_block_pp0_stage0_11001_grp1, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone_grp1_done_reg) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))) then 
            p_anonymous_namespace_rise_cells_ce0_local <= ap_const_logic_1;
        else 
            p_anonymous_namespace_rise_cells_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    p_out <= empty_24;

    p_out_ap_vld_assign_proc : process(ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            p_out_ap_vld <= ap_const_logic_1;
        else 
            p_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    remaining_10_fu_524_p3 <= 
        remaining_13_fu_520_p2 when (empty_32(0) = '1') else 
        remaining_8_reg_1443;
    remaining_11_fu_462_p3 <= 
        remaining_9_reg_1418 when (empty_30(0) = '1') else 
        zext_ln747_reg_1411;
    remaining_12_fu_467_p2 <= std_logic_vector(unsigned(remaining_11_fu_462_p3) - unsigned(build_stop_channels_per_chip));
    remaining_13_fu_520_p2 <= std_logic_vector(unsigned(remaining_8_reg_1443) - unsigned(build_stop_channels_per_chip));
    remaining_1_fu_417_p2 <= std_logic_vector(unsigned(zext_ln728_fu_413_p1) - unsigned(build_stop_channels_per_chip));
    remaining_2_fu_445_p3 <= 
        remaining_1_reg_1396 when (empty_25(0) = '1') else 
        zext_ln728_reg_1389;
    remaining_3_fu_455_p3 <= 
        remaining_4_fu_450_p2 when (empty_26(0) = '1') else 
        remaining_2_fu_445_p3;
    remaining_4_fu_450_p2 <= std_logic_vector(unsigned(remaining_2_fu_445_p3) - unsigned(build_stop_channels_per_chip));
    remaining_5_fu_491_p3 <= 
        remaining_6_fu_487_p2 when (empty_27(0) = '1') else 
        remaining_3_reg_1429;
    remaining_6_fu_487_p2 <= std_logic_vector(unsigned(remaining_3_reg_1429) - unsigned(build_stop_channels_per_chip));
    remaining_8_fu_472_p3 <= 
        remaining_12_fu_467_p2 when (empty_31(0) = '1') else 
        remaining_11_fu_462_p3;
    remaining_9_fu_435_p2 <= std_logic_vector(unsigned(zext_ln747_fu_431_p1) - unsigned(build_stop_channels_per_chip));
    sel_tmp1_fu_599_p4 <= ((and_ln73_reg_1461 & and_ln73_2_fu_573_p2) & and_ln73_4_fu_594_p2);
    sel_tmp2_fu_725_p4 <= ((and_ln73_5_reg_1484 & and_ln73_7_fu_699_p2) & and_ln73_9_fu_720_p2);
    select_ln32_1_fu_1169_p3 <= 
        gap_before when (value_8_reg_1622(0) = '1') else 
        ap_const_lv16_0;
    select_ln32_fu_1105_p3 <= 
        gap_before when (value_1_reg_1589(0) = '1') else 
        ap_const_lv16_0;
    slot_4_fu_389_p2 <= std_logic_vector(unsigned(slot_fu_196) + unsigned(ap_const_lv6_1));
    slot_5_fu_409_p1 <= slot_fu_196(5 - 1 downto 0);
    slot_6_fu_427_p1 <= slot_fu_196(5 - 1 downto 0);
    tmp_12_fu_875_p4 <= p_anonymous_namespace_rise_cells_q0(131 downto 125);
    tmp_13_fu_885_p4 <= p_anonymous_namespace_rise_cells_q0(124 downto 119);
    tmp_14_fu_964_p3 <= empty_24(35 downto 20);
    tmp_15_fu_1147_p11 <= (((((((((value_6_fu_1141_p2 & value_5_fu_1111_p2) & select_ln32_fu_1105_p3) & value_4_reg_1605) & value_3_reg_1600) & value_2_reg_1595) & value_1_reg_1589) & empty_29) & zext_ln32_reg_1584) & cell_2_reg_1577);
    tmp_16_fu_1116_p3 <= cell_2_reg_1577(137 downto 137);
    tmp_17_fu_1123_p3 <= cell_2_reg_1577(136 downto 136);
    tmp_19_fu_988_p3 <= p_anonymous_namespace_fall_cells_q0(147 downto 132);
    tmp_20_fu_996_p4 <= p_anonymous_namespace_fall_cells_q0(131 downto 125);
    tmp_21_fu_1006_p4 <= p_anonymous_namespace_fall_cells_q0(124 downto 119);
    tmp_22_fu_1085_p3 <= empty_24(35 downto 20);
    tmp_23_fu_1211_p11 <= (((((((((value_13_fu_1205_p2 & value_12_fu_1175_p2) & select_ln32_1_fu_1169_p3) & value_11_reg_1638) & value_10_reg_1633) & value_9_reg_1628) & value_8_reg_1622) & empty) & zext_ln32_1_reg_1617) & cell_5_reg_1610);
    tmp_24_fu_1180_p3 <= cell_5_reg_1610(137 downto 137);
    tmp_25_fu_1187_p3 <= cell_5_reg_1610(136 downto 136);
    tmp_s_fu_867_p3 <= p_anonymous_namespace_rise_cells_q0(147 downto 132);
    trunc_ln25_1_fu_984_p1 <= p_anonymous_namespace_fall_cells_q0(119 - 1 downto 0);
    trunc_ln25_fu_863_p1 <= p_anonymous_namespace_rise_cells_q0(119 - 1 downto 0);
    trunc_ln32_1_fu_793_p1 <= address_stop_1_fu_734_p11(3 - 1 downto 0);
    trunc_ln32_fu_667_p1 <= address_stop_fu_608_p11(3 - 1 downto 0);
    trunc_ln45_1_fu_779_p1 <= address_stop_1_fu_734_p11(6 - 1 downto 0);
    trunc_ln45_fu_653_p1 <= address_stop_fu_608_p11(6 - 1 downto 0);
    value_10_fu_1092_p2 <= "1" when (tmp_22_fu_1085_p3 = ap_const_lv16_0) else "0";
    value_12_fu_1175_p2 <= (present_1_reg_1560_pp0_iter5_reg xor ap_const_lv1_1);
    value_13_fu_1205_p2 <= (tmp_25_fu_1187_p3 or or_ln40_3_fu_1200_p2);
    value_1_fu_944_p2 <= "1" when (slot_5_reg_1383_pp0_iter4_reg = ap_const_lv5_0) else "0";
    value_2_fu_959_p2 <= "1" when (zext_ln288_fu_955_p1 = rise_count) else "0";
    value_3_fu_971_p2 <= "1" when (tmp_14_fu_964_p3 = ap_const_lv16_0) else "0";
    value_5_fu_1111_p2 <= (present_reg_1543_pp0_iter5_reg xor ap_const_lv1_1);
    value_6_fu_1141_p2 <= (tmp_17_fu_1123_p3 or or_ln40_1_fu_1136_p2);
    value_7_fu_858_p2 <= "0" when (tmp_18_reg_1532 = ap_const_lv6_0) else "1";
    value_8_fu_1065_p2 <= "1" when (slot_6_reg_1405_pp0_iter4_reg = ap_const_lv5_0) else "0";
    value_9_fu_1080_p2 <= "1" when (zext_ln288_1_fu_1076_p1 = fall_count) else "0";
    value_fu_825_p2 <= "0" when (tmp_11_reg_1509 = ap_const_lv6_0) else "1";
    xor_ln73_1_fu_582_p2 <= (or_ln73_fu_578_p2 xor ap_const_lv1_1);
    xor_ln73_2_fu_694_p2 <= (ap_const_lv1_1 xor and_ln73_5_reg_1484);
    xor_ln73_3_fu_708_p2 <= (or_ln73_1_fu_704_p2 xor ap_const_lv1_1);
    xor_ln73_fu_568_p2 <= (ap_const_lv1_1 xor and_ln73_reg_1461);
    zext_ln288_1_fu_1076_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln288_1_fu_1070_p2),8));
    zext_ln288_fu_955_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln288_fu_949_p2),8));
    zext_ln32_1_fu_1062_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_6_reg_1405_pp0_iter4_reg),6));
    zext_ln32_fu_941_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_5_reg_1383_pp0_iter4_reg),6));
    zext_ln46_1_cast_fu_830_p3 <= (address_chip_1_reg_1520 & ap_const_lv3_0);
    zext_ln46_1_fu_837_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln46_1_cast_fu_830_p3),6));
    zext_ln46_cast_fu_797_p3 <= (address_chip_reg_1497 & ap_const_lv3_0);
    zext_ln46_fu_804_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln46_cast_fu_797_p3),6));
    zext_ln48_2_fu_1051_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cell_4_fu_1036_p9),319));
    zext_ln48_fu_930_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(cell_1_fu_915_p9),319));
    zext_ln720_fu_395_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_fu_196),8));
    zext_ln728_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_5_fu_409_p1),8));
    zext_ln732_1_fu_813_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(linear_fu_808_p2),64));
    zext_ln732_cast_fu_371_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln732),64));
    zext_ln747_fu_431_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(slot_6_fu_427_p1),8));
    zext_ln751_1_fu_846_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(linear_1_fu_841_p2),64));
    zext_ln751_cast_fu_367_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(zext_ln751),64));
end behav;
