// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word (
        ap_clk,
        ap_rst,
        ordered_cell_val,
        profile_serialized_return_slots_val,
        profile_cell_word_count_val,
        local_word_index,
        line_faulted,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [351:0] ordered_cell_val;
input  [2:0] profile_serialized_return_slots_val;
input  [2:0] profile_cell_word_count_val;
input  [2:0] local_word_index;
input  [0:0] line_faulted;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

reg   [8:0] result_6_reg_205;
reg   [10:0] result_12_reg_224;
reg   [12:0] result_16_reg_243;
reg   [0:0] line_faulted_read_reg_1265;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] line_faulted_read_reg_1265_pp0_iter1_reg;
reg   [0:0] line_faulted_read_reg_1265_pp0_iter2_reg;
reg   [0:0] line_faulted_read_reg_1265_pp0_iter3_reg;
reg   [0:0] line_faulted_read_reg_1265_pp0_iter4_reg;
reg   [351:0] ordered_cell_val_read_reg_1270;
reg   [351:0] ordered_cell_val_read_reg_1270_pp0_iter1_reg;
reg   [351:0] ordered_cell_val_read_reg_1270_pp0_iter2_reg;
reg   [351:0] ordered_cell_val_read_reg_1270_pp0_iter3_reg;
reg   [351:0] ordered_cell_val_read_reg_1270_pp0_iter4_reg;
wire   [0:0] blank_fu_356_p3;
reg   [0:0] blank_reg_1282;
reg   [0:0] blank_reg_1282_pp0_iter1_reg;
reg   [0:0] blank_reg_1282_pp0_iter2_reg;
reg   [0:0] blank_reg_1282_pp0_iter3_reg;
wire   [2:0] valid_return_count_fu_364_p4;
reg   [2:0] valid_return_count_reg_1287;
reg   [2:0] valid_return_count_reg_1287_pp0_iter1_reg;
reg   [2:0] valid_return_count_reg_1287_pp0_iter2_reg;
reg   [2:0] valid_return_count_reg_1287_pp0_iter3_reg;
wire   [0:0] icmp_ln534_fu_384_p2;
reg   [0:0] icmp_ln534_reg_1293;
reg   [0:0] icmp_ln534_reg_1293_pp0_iter1_reg;
reg   [0:0] icmp_ln534_reg_1293_pp0_iter2_reg;
reg   [0:0] icmp_ln534_reg_1293_pp0_iter3_reg;
reg   [0:0] icmp_ln534_reg_1293_pp0_iter4_reg;
wire   [0:0] and_ln556_1_fu_414_p2;
reg   [0:0] and_ln556_1_reg_1297;
wire   [7:0] result_2_fu_428_p3;
reg   [7:0] result_2_reg_1301;
wire   [0:0] and_ln556_3_fu_474_p2;
reg   [0:0] and_ln556_3_reg_1306;
reg   [0:0] tmp_52_reg_1310;
wire   [0:0] and_ln556_5_fu_506_p2;
reg   [0:0] and_ln556_5_reg_1315;
reg   [0:0] and_ln556_5_reg_1315_pp0_iter1_reg;
reg   [0:0] tmp_53_reg_1319;
wire   [0:0] and_ln556_7_fu_542_p2;
reg   [0:0] and_ln556_7_reg_1324;
reg   [0:0] and_ln556_7_reg_1324_pp0_iter1_reg;
reg   [0:0] tmp_57_reg_1328;
reg   [0:0] tmp_57_reg_1328_pp0_iter1_reg;
wire   [0:0] and_ln556_9_fu_574_p2;
reg   [0:0] and_ln556_9_reg_1333;
reg   [0:0] and_ln556_9_reg_1333_pp0_iter1_reg;
reg   [0:0] and_ln556_9_reg_1333_pp0_iter2_reg;
reg   [0:0] tmp_59_reg_1337;
reg   [0:0] tmp_59_reg_1337_pp0_iter1_reg;
wire   [0:0] and_ln556_11_fu_606_p2;
reg   [0:0] and_ln556_11_reg_1342;
reg   [0:0] and_ln556_11_reg_1342_pp0_iter1_reg;
reg   [0:0] and_ln556_11_reg_1342_pp0_iter2_reg;
reg   [0:0] tmp_61_reg_1346;
reg   [0:0] tmp_61_reg_1346_pp0_iter1_reg;
reg   [0:0] tmp_61_reg_1346_pp0_iter2_reg;
wire   [0:0] and_ln556_13_fu_638_p2;
reg   [0:0] and_ln556_13_reg_1351;
reg   [0:0] and_ln556_13_reg_1351_pp0_iter1_reg;
reg   [0:0] and_ln556_13_reg_1351_pp0_iter2_reg;
reg   [0:0] and_ln556_13_reg_1351_pp0_iter3_reg;
reg   [0:0] tmp_63_reg_1355;
reg   [0:0] tmp_63_reg_1355_pp0_iter1_reg;
reg   [0:0] tmp_63_reg_1355_pp0_iter2_reg;
wire   [0:0] and_ln541_2_fu_701_p2;
reg   [0:0] and_ln541_2_reg_1360;
wire   [15:0] low16_1_fu_707_p1;
reg   [15:0] low16_1_reg_1364;
wire   [0:0] and_ln541_5_fu_758_p2;
reg   [0:0] and_ln541_5_reg_1369;
reg   [0:0] and_ln541_5_reg_1369_pp0_iter1_reg;
reg   [0:0] and_ln541_5_reg_1369_pp0_iter2_reg;
reg   [0:0] and_ln541_5_reg_1369_pp0_iter3_reg;
reg   [0:0] and_ln541_5_reg_1369_pp0_iter4_reg;
wire   [15:0] low16_fu_764_p1;
reg   [15:0] low16_reg_1373;
reg   [15:0] low16_reg_1373_pp0_iter1_reg;
reg   [15:0] low16_reg_1373_pp0_iter2_reg;
reg   [15:0] low16_reg_1373_pp0_iter3_reg;
reg   [15:0] low16_reg_1373_pp0_iter4_reg;
wire   [8:0] select_ln561_1_fu_837_p3;
reg   [8:0] select_ln561_1_reg_1378;
wire   [10:0] select_ln561_3_fu_926_p3;
reg   [10:0] select_ln561_3_reg_1383;
wire   [12:0] select_ln561_5_fu_1015_p3;
reg   [12:0] select_ln561_5_reg_1388;
wire   [24:0] result_24_fu_1140_p3;
reg   [24:0] result_24_reg_1393;
wire    grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_ready;
reg   [2:0] grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index;
wire   [16:0] grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return;
wire    grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_ready;
reg   [2:0] grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index;
wire   [16:0] grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return;
wire    tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_ready;
wire   [16:0] tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return;
wire    tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_ready;
wire   [16:0] tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return;
wire    tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_ready;
wire   [16:0] tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return;
wire    tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_ready;
wire   [16:0] tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return;
wire    tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_ready;
wire   [16:0] tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return;
reg   [7:0] ap_phi_mux_result_3_phi_fu_198_p4;
reg   [7:0] ap_phi_reg_pp0_iter1_result_3_reg_194;
wire   [7:0] ap_phi_reg_pp0_iter0_result_3_reg_194;
reg   [8:0] ap_phi_mux_result_6_phi_fu_208_p4;
wire   [8:0] result_5_fu_804_p3;
wire   [8:0] ap_phi_reg_pp0_iter1_result_6_reg_205;
wire   [8:0] zext_ln533_1_fu_768_p1;
reg   [9:0] ap_phi_mux_result_8_phi_fu_218_p4;
wire   [9:0] result_7_fu_849_p3;
wire   [9:0] ap_phi_reg_pp0_iter2_result_8_reg_215;
wire   [9:0] zext_ln533_2_fu_844_p1;
reg   [10:0] ap_phi_mux_result_12_phi_fu_227_p4;
wire   [10:0] result_9_fu_893_p3;
wire   [10:0] ap_phi_reg_pp0_iter2_result_12_reg_224;
wire   [10:0] zext_ln533_3_fu_857_p1;
reg   [11:0] ap_phi_mux_result_14_phi_fu_237_p4;
wire   [11:0] result_13_fu_938_p3;
wire   [11:0] ap_phi_reg_pp0_iter3_result_14_reg_234;
wire   [11:0] zext_ln533_4_fu_933_p1;
reg   [12:0] ap_phi_mux_result_16_phi_fu_246_p4;
wire   [12:0] result_15_fu_982_p3;
wire   [12:0] ap_phi_reg_pp0_iter3_result_16_reg_243;
wire   [12:0] zext_ln533_5_fu_946_p1;
reg   [13:0] ap_phi_mux_result_18_phi_fu_256_p4;
wire   [13:0] result_17_fu_1027_p3;
wire   [13:0] ap_phi_reg_pp0_iter4_result_18_reg_253;
wire   [13:0] zext_ln533_6_fu_1022_p1;
wire   [15:0] ap_phi_reg_pp0_iter0_result_1_reg_262;
reg   [15:0] ap_phi_reg_pp0_iter1_result_1_reg_262;
reg   [15:0] ap_phi_reg_pp0_iter2_result_1_reg_262;
reg   [15:0] ap_phi_reg_pp0_iter3_result_1_reg_262;
reg   [15:0] ap_phi_reg_pp0_iter4_result_1_reg_262;
reg   [15:0] ap_phi_reg_pp0_iter5_result_1_reg_262;
reg   [31:0] ap_phi_mux_result_11_phi_fu_276_p6;
wire   [31:0] result_29_fu_1241_p4;
wire   [31:0] ap_phi_reg_pp0_iter5_result_11_reg_273;
wire   [31:0] result_4_fu_1257_p3;
wire   [31:0] zext_ln533_fu_1252_p1;
wire   [133:0] trunc_ln521_fu_345_p1;
wire    ap_block_pp0_stage0_ignoreCallOp28;
wire    ap_block_pp0_stage0_ignoreCallOp79;
wire   [2:0] shl_ln535_fu_664_p2;
wire    ap_block_pp0_stage0_ignoreCallOp37;
wire    ap_block_pp0_stage0_ignoreCallOp89;
wire   [2:0] or_ln_fu_719_p3;
wire    ap_block_pp0_stage0_ignoreCallOp43;
wire    ap_block_pp0_stage0_ignoreCallOp49;
wire    ap_block_pp0_stage0_ignoreCallOp55;
wire    ap_block_pp0_stage0_ignoreCallOp61;
wire    ap_block_pp0_stage0_ignoreCallOp67;
wire    ap_block_pp0_stage0;
wire   [3:0] zext_ln519_1_fu_337_p1;
wire   [3:0] hit_word_count_fu_378_p2;
wire   [3:0] zext_ln519_fu_333_p1;
wire   [0:0] icmp_ln558_fu_402_p2;
wire   [0:0] xor_ln556_fu_390_p2;
wire   [0:0] and_ln556_fu_408_p2;
wire   [0:0] icmp_ln557_fu_396_p2;
wire   [0:0] tmp_fu_420_p3;
wire   [1:0] tmp_50_fu_436_p4;
wire   [1:0] tmp_51_fu_452_p4;
wire   [0:0] icmp_ln558_1_fu_462_p2;
wire   [0:0] and_ln556_2_fu_468_p2;
wire   [0:0] icmp_ln557_1_fu_446_p2;
wire   [0:0] icmp_ln558_2_fu_494_p2;
wire   [0:0] and_ln556_4_fu_500_p2;
wire   [0:0] icmp_ln557_2_fu_488_p2;
wire   [0:0] tmp_56_fu_528_p3;
wire   [0:0] and_ln556_6_fu_536_p2;
wire   [0:0] tmp_55_fu_520_p3;
wire   [0:0] icmp_ln558_3_fu_562_p2;
wire   [0:0] and_ln556_8_fu_568_p2;
wire   [0:0] icmp_ln557_3_fu_556_p2;
wire   [0:0] icmp_ln558_4_fu_594_p2;
wire   [0:0] and_ln556_10_fu_600_p2;
wire   [0:0] icmp_ln557_4_fu_588_p2;
wire   [0:0] icmp_ln558_5_fu_626_p2;
wire   [0:0] and_ln556_12_fu_632_p2;
wire   [0:0] icmp_ln557_5_fu_620_p2;
wire   [3:0] first_return_fu_652_p3;
wire   [3:0] zext_ln527_fu_374_p1;
wire   [3:0] zext_ln519_2_fu_341_p1;
wire   [0:0] icmp_ln543_fu_683_p2;
wire   [0:0] icmp_ln542_fu_677_p2;
wire   [0:0] icmp_ln541_fu_671_p2;
wire   [0:0] and_ln541_1_fu_695_p2;
wire   [0:0] and_ln541_fu_689_p2;
wire   [1:0] trunc_ln535_fu_660_p1;
wire   [3:0] return_index_1_fu_711_p3;
wire   [0:0] icmp_ln543_1_fu_740_p2;
wire   [0:0] icmp_ln542_1_fu_734_p2;
wire   [0:0] icmp_ln541_1_fu_728_p2;
wire   [0:0] and_ln541_4_fu_752_p2;
wire   [0:0] and_ln541_3_fu_746_p2;
wire   [5:0] tmp_49_fu_773_p4;
wire   [0:0] trunc_ln563_fu_783_p1;
wire   [7:0] or_ln1_fu_787_p4;
wire   [7:0] select_ln561_fu_797_p3;
wire   [5:0] tmp_54_fu_813_p4;
wire   [1:0] trunc_ln563_1_fu_823_p1;
wire   [8:0] or_ln563_1_fu_827_p4;
wire   [5:0] tmp_58_fu_862_p4;
wire   [2:0] trunc_ln563_2_fu_872_p1;
wire   [9:0] or_ln563_2_fu_876_p4;
wire   [9:0] select_ln561_2_fu_886_p3;
wire   [5:0] tmp_60_fu_902_p4;
wire   [3:0] trunc_ln563_3_fu_912_p1;
wire   [10:0] or_ln563_3_fu_916_p4;
wire   [5:0] tmp_62_fu_951_p4;
wire   [4:0] trunc_ln563_4_fu_961_p1;
wire   [11:0] or_ln563_4_fu_965_p4;
wire   [11:0] select_ln561_4_fu_975_p3;
wire   [5:0] tmp_64_fu_991_p4;
wire   [5:0] trunc_ln563_5_fu_1001_p1;
wire   [12:0] or_ln563_5_fu_1005_p4;
wire   [16:0] result_19_fu_1035_p3;
wire   [0:0] tmp_65_fu_1046_p3;
wire   [17:0] or_ln2_fu_1053_p4;
wire   [17:0] zext_ln533_7_fu_1042_p1;
wire   [2:0] tmp_1_fu_1070_p4;
wire   [1:0] tmp_2_fu_1079_p4;
wire   [17:0] result_20_fu_1062_p3;
wire   [22:0] result_21_fu_1088_p4;
wire   [23:0] result_22_fu_1102_p5;
wire   [23:0] zext_ln533_8_fu_1098_p1;
wire   [23:0] result_23_fu_1114_p3;
wire   [0:0] tmp_66_fu_1125_p3;
wire   [24:0] or_ln3_fu_1132_p3;
wire   [24:0] zext_ln533_9_fu_1121_p1;
wire   [0:0] tmp_67_fu_1151_p3;
wire   [25:0] result_25_fu_1158_p3;
wire   [25:0] zext_ln533_10_fu_1148_p1;
wire   [25:0] result_26_fu_1165_p3;
wire   [0:0] tmp_68_fu_1177_p3;
wire   [26:0] or_ln4_fu_1184_p3;
wire   [26:0] zext_ln533_11_fu_1173_p1;
wire   [26:0] result_27_fu_1192_p3;
wire   [0:0] tmp_69_fu_1204_p3;
wire   [0:0] or_ln40_fu_1219_p2;
wire   [27:0] result_28_fu_1211_p3;
wire   [27:0] zext_ln533_12_fu_1200_p1;
wire   [2:0] tmp_3_fu_1232_p4;
wire   [27:0] result_10_fu_1224_p3;
reg    ap_ce_reg;
reg   [351:0] ordered_cell_val_int_reg;
reg   [2:0] profile_serialized_return_slots_val_int_reg;
reg   [2:0] profile_cell_word_count_val_int_reg;
reg   [2:0] local_word_index_int_reg;
reg   [0:0] line_faulted_int_reg;
reg   [31:0] ap_return_int_reg;

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit grp_p_anonymous_namespace_read_packed_distance_hit_fu_284(
    .ap_ready(grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index),
    .ap_return(grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit grp_p_anonymous_namespace_read_packed_distance_hit_fu_291(
    .ap_ready(grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index),
    .ap_return(grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298(
    .ap_ready(tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(3'd2),
    .ap_return(tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305(
    .ap_ready(tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(3'd3),
    .ap_return(tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312(
    .ap_ready(tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(3'd4),
    .ap_return(tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319(
    .ap_ready(tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(3'd5),
    .ap_return(tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return),
    .ap_rst(ap_rst)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326(
    .ap_ready(tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_ready),
    .cell_val(trunc_ln521_fu_345_p1),
    .return_index(3'd6),
    .ap_return(tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return),
    .ap_rst(ap_rst)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_fu_384_p2 == 1'd1) & (1'd0 == and_ln541_2_fu_701_p2))) begin
            ap_phi_reg_pp0_iter1_result_1_reg_262 <= 16'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_result_1_reg_262 <= ap_phi_reg_pp0_iter0_result_1_reg_262;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_fu_384_p2 == 1'd0) & (1'd0 == and_ln556_1_fu_414_p2))) begin
            ap_phi_reg_pp0_iter1_result_3_reg_194 <= 8'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_result_3_reg_194 <= ap_phi_reg_pp0_iter0_result_3_reg_194;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_reg_1293 == 1'd1) & (1'd1 == and_ln541_2_reg_1360))) begin
            ap_phi_reg_pp0_iter2_result_1_reg_262 <= low16_1_reg_1364;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter2_result_1_reg_262 <= ap_phi_reg_pp0_iter1_result_1_reg_262;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_reg_1293_pp0_iter1_reg == 1'd0) & (1'd0 == and_ln556_7_reg_1324_pp0_iter1_reg))) begin
            result_12_reg_224 <= zext_ln533_3_fu_857_p1;
        end else if (((icmp_ln534_reg_1293_pp0_iter1_reg == 1'd0) & (1'd1 == and_ln556_7_reg_1324_pp0_iter1_reg))) begin
            result_12_reg_224 <= result_9_fu_893_p3;
        end else if ((1'b1 == 1'b1)) begin
            result_12_reg_224 <= ap_phi_reg_pp0_iter2_result_12_reg_224;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_reg_1293_pp0_iter2_reg == 1'd0) & (1'd0 == and_ln556_11_reg_1342_pp0_iter2_reg))) begin
            result_16_reg_243 <= zext_ln533_5_fu_946_p1;
        end else if (((icmp_ln534_reg_1293_pp0_iter2_reg == 1'd0) & (1'd1 == and_ln556_11_reg_1342_pp0_iter2_reg))) begin
            result_16_reg_243 <= result_15_fu_982_p3;
        end else if ((1'b1 == 1'b1)) begin
            result_16_reg_243 <= ap_phi_reg_pp0_iter3_result_16_reg_243;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((icmp_ln534_reg_1293 == 1'd0) & (1'd0 == and_ln556_3_reg_1306))) begin
            result_6_reg_205 <= zext_ln533_1_fu_768_p1;
        end else if (((icmp_ln534_reg_1293 == 1'd0) & (1'd1 == and_ln556_3_reg_1306))) begin
            result_6_reg_205 <= result_5_fu_804_p3;
        end else if ((1'b1 == 1'b1)) begin
            result_6_reg_205 <= ap_phi_reg_pp0_iter1_result_6_reg_205;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        and_ln541_2_reg_1360 <= and_ln541_2_fu_701_p2;
        and_ln541_5_reg_1369 <= and_ln541_5_fu_758_p2;
        and_ln541_5_reg_1369_pp0_iter1_reg <= and_ln541_5_reg_1369;
        and_ln541_5_reg_1369_pp0_iter2_reg <= and_ln541_5_reg_1369_pp0_iter1_reg;
        and_ln541_5_reg_1369_pp0_iter3_reg <= and_ln541_5_reg_1369_pp0_iter2_reg;
        and_ln541_5_reg_1369_pp0_iter4_reg <= and_ln541_5_reg_1369_pp0_iter3_reg;
        and_ln556_11_reg_1342 <= and_ln556_11_fu_606_p2;
        and_ln556_11_reg_1342_pp0_iter1_reg <= and_ln556_11_reg_1342;
        and_ln556_11_reg_1342_pp0_iter2_reg <= and_ln556_11_reg_1342_pp0_iter1_reg;
        and_ln556_13_reg_1351 <= and_ln556_13_fu_638_p2;
        and_ln556_13_reg_1351_pp0_iter1_reg <= and_ln556_13_reg_1351;
        and_ln556_13_reg_1351_pp0_iter2_reg <= and_ln556_13_reg_1351_pp0_iter1_reg;
        and_ln556_13_reg_1351_pp0_iter3_reg <= and_ln556_13_reg_1351_pp0_iter2_reg;
        and_ln556_1_reg_1297 <= and_ln556_1_fu_414_p2;
        and_ln556_3_reg_1306 <= and_ln556_3_fu_474_p2;
        and_ln556_5_reg_1315 <= and_ln556_5_fu_506_p2;
        and_ln556_5_reg_1315_pp0_iter1_reg <= and_ln556_5_reg_1315;
        and_ln556_7_reg_1324 <= and_ln556_7_fu_542_p2;
        and_ln556_7_reg_1324_pp0_iter1_reg <= and_ln556_7_reg_1324;
        and_ln556_9_reg_1333 <= and_ln556_9_fu_574_p2;
        and_ln556_9_reg_1333_pp0_iter1_reg <= and_ln556_9_reg_1333;
        and_ln556_9_reg_1333_pp0_iter2_reg <= and_ln556_9_reg_1333_pp0_iter1_reg;
        ap_phi_reg_pp0_iter3_result_1_reg_262 <= ap_phi_reg_pp0_iter2_result_1_reg_262;
        ap_phi_reg_pp0_iter4_result_1_reg_262 <= ap_phi_reg_pp0_iter3_result_1_reg_262;
        ap_phi_reg_pp0_iter5_result_1_reg_262 <= ap_phi_reg_pp0_iter4_result_1_reg_262;
        blank_reg_1282 <= ordered_cell_val_int_reg[32'd351];
        blank_reg_1282_pp0_iter1_reg <= blank_reg_1282;
        blank_reg_1282_pp0_iter2_reg <= blank_reg_1282_pp0_iter1_reg;
        blank_reg_1282_pp0_iter3_reg <= blank_reg_1282_pp0_iter2_reg;
        icmp_ln534_reg_1293 <= icmp_ln534_fu_384_p2;
        icmp_ln534_reg_1293_pp0_iter1_reg <= icmp_ln534_reg_1293;
        icmp_ln534_reg_1293_pp0_iter2_reg <= icmp_ln534_reg_1293_pp0_iter1_reg;
        icmp_ln534_reg_1293_pp0_iter3_reg <= icmp_ln534_reg_1293_pp0_iter2_reg;
        icmp_ln534_reg_1293_pp0_iter4_reg <= icmp_ln534_reg_1293_pp0_iter3_reg;
        line_faulted_read_reg_1265 <= line_faulted_int_reg;
        line_faulted_read_reg_1265_pp0_iter1_reg <= line_faulted_read_reg_1265;
        line_faulted_read_reg_1265_pp0_iter2_reg <= line_faulted_read_reg_1265_pp0_iter1_reg;
        line_faulted_read_reg_1265_pp0_iter3_reg <= line_faulted_read_reg_1265_pp0_iter2_reg;
        line_faulted_read_reg_1265_pp0_iter4_reg <= line_faulted_read_reg_1265_pp0_iter3_reg;
        low16_1_reg_1364 <= low16_1_fu_707_p1;
        low16_reg_1373 <= low16_fu_764_p1;
        low16_reg_1373_pp0_iter1_reg <= low16_reg_1373;
        low16_reg_1373_pp0_iter2_reg <= low16_reg_1373_pp0_iter1_reg;
        low16_reg_1373_pp0_iter3_reg <= low16_reg_1373_pp0_iter2_reg;
        low16_reg_1373_pp0_iter4_reg <= low16_reg_1373_pp0_iter3_reg;
        ordered_cell_val_read_reg_1270 <= ordered_cell_val_int_reg;
        ordered_cell_val_read_reg_1270_pp0_iter1_reg <= ordered_cell_val_read_reg_1270;
        ordered_cell_val_read_reg_1270_pp0_iter2_reg <= ordered_cell_val_read_reg_1270_pp0_iter1_reg;
        ordered_cell_val_read_reg_1270_pp0_iter3_reg <= ordered_cell_val_read_reg_1270_pp0_iter2_reg;
        ordered_cell_val_read_reg_1270_pp0_iter4_reg <= ordered_cell_val_read_reg_1270_pp0_iter3_reg;
        result_24_reg_1393 <= result_24_fu_1140_p3;
        result_2_reg_1301[0] <= result_2_fu_428_p3[0];
        select_ln561_1_reg_1378 <= select_ln561_1_fu_837_p3;
        select_ln561_3_reg_1383 <= select_ln561_3_fu_926_p3;
        select_ln561_5_reg_1388 <= select_ln561_5_fu_1015_p3;
        tmp_52_reg_1310 <= grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return[32'd16];
        tmp_53_reg_1319 <= tmp_44_p_anonymous_namespace_read_packed_distance_hit_fu_298_ap_return[32'd16];
        tmp_57_reg_1328 <= tmp_45_p_anonymous_namespace_read_packed_distance_hit_fu_305_ap_return[32'd16];
        tmp_57_reg_1328_pp0_iter1_reg <= tmp_57_reg_1328;
        tmp_59_reg_1337 <= tmp_46_p_anonymous_namespace_read_packed_distance_hit_fu_312_ap_return[32'd16];
        tmp_59_reg_1337_pp0_iter1_reg <= tmp_59_reg_1337;
        tmp_61_reg_1346 <= tmp_47_p_anonymous_namespace_read_packed_distance_hit_fu_319_ap_return[32'd16];
        tmp_61_reg_1346_pp0_iter1_reg <= tmp_61_reg_1346;
        tmp_61_reg_1346_pp0_iter2_reg <= tmp_61_reg_1346_pp0_iter1_reg;
        tmp_63_reg_1355 <= tmp_48_p_anonymous_namespace_read_packed_distance_hit_fu_326_ap_return[32'd16];
        tmp_63_reg_1355_pp0_iter1_reg <= tmp_63_reg_1355;
        tmp_63_reg_1355_pp0_iter2_reg <= tmp_63_reg_1355_pp0_iter1_reg;
        valid_return_count_reg_1287 <= {{ordered_cell_val_int_reg[11:9]}};
        valid_return_count_reg_1287_pp0_iter1_reg <= valid_return_count_reg_1287;
        valid_return_count_reg_1287_pp0_iter2_reg <= valid_return_count_reg_1287_pp0_iter1_reg;
        valid_return_count_reg_1287_pp0_iter3_reg <= valid_return_count_reg_1287_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= ap_phi_mux_result_11_phi_fu_276_p6;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        line_faulted_int_reg <= line_faulted;
        local_word_index_int_reg <= local_word_index;
        ordered_cell_val_int_reg <= ordered_cell_val;
        profile_cell_word_count_val_int_reg <= profile_cell_word_count_val;
        profile_serialized_return_slots_val_int_reg <= profile_serialized_return_slots_val;
    end
end

always @ (*) begin
    if (((icmp_ln534_reg_1293_pp0_iter4_reg == 1'd1) & (1'd0 == and_ln541_5_reg_1369_pp0_iter4_reg))) begin
        ap_phi_mux_result_11_phi_fu_276_p6 = zext_ln533_fu_1252_p1;
    end else if (((icmp_ln534_reg_1293_pp0_iter4_reg == 1'd1) & (1'd1 == and_ln541_5_reg_1369_pp0_iter4_reg))) begin
        ap_phi_mux_result_11_phi_fu_276_p6 = result_4_fu_1257_p3;
    end else if ((icmp_ln534_reg_1293_pp0_iter4_reg == 1'd0)) begin
        ap_phi_mux_result_11_phi_fu_276_p6 = result_29_fu_1241_p4;
    end else begin
        ap_phi_mux_result_11_phi_fu_276_p6 = ap_phi_reg_pp0_iter5_result_11_reg_273;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293_pp0_iter1_reg == 1'd0)) begin
        if ((1'd0 == and_ln556_7_reg_1324_pp0_iter1_reg)) begin
            ap_phi_mux_result_12_phi_fu_227_p4 = zext_ln533_3_fu_857_p1;
        end else if ((1'd1 == and_ln556_7_reg_1324_pp0_iter1_reg)) begin
            ap_phi_mux_result_12_phi_fu_227_p4 = result_9_fu_893_p3;
        end else begin
            ap_phi_mux_result_12_phi_fu_227_p4 = ap_phi_reg_pp0_iter2_result_12_reg_224;
        end
    end else begin
        ap_phi_mux_result_12_phi_fu_227_p4 = ap_phi_reg_pp0_iter2_result_12_reg_224;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293_pp0_iter2_reg == 1'd0)) begin
        if ((1'd0 == and_ln556_9_reg_1333_pp0_iter2_reg)) begin
            ap_phi_mux_result_14_phi_fu_237_p4 = zext_ln533_4_fu_933_p1;
        end else if ((1'd1 == and_ln556_9_reg_1333_pp0_iter2_reg)) begin
            ap_phi_mux_result_14_phi_fu_237_p4 = result_13_fu_938_p3;
        end else begin
            ap_phi_mux_result_14_phi_fu_237_p4 = ap_phi_reg_pp0_iter3_result_14_reg_234;
        end
    end else begin
        ap_phi_mux_result_14_phi_fu_237_p4 = ap_phi_reg_pp0_iter3_result_14_reg_234;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293_pp0_iter2_reg == 1'd0)) begin
        if ((1'd0 == and_ln556_11_reg_1342_pp0_iter2_reg)) begin
            ap_phi_mux_result_16_phi_fu_246_p4 = zext_ln533_5_fu_946_p1;
        end else if ((1'd1 == and_ln556_11_reg_1342_pp0_iter2_reg)) begin
            ap_phi_mux_result_16_phi_fu_246_p4 = result_15_fu_982_p3;
        end else begin
            ap_phi_mux_result_16_phi_fu_246_p4 = ap_phi_reg_pp0_iter3_result_16_reg_243;
        end
    end else begin
        ap_phi_mux_result_16_phi_fu_246_p4 = ap_phi_reg_pp0_iter3_result_16_reg_243;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293_pp0_iter3_reg == 1'd0)) begin
        if ((1'd0 == and_ln556_13_reg_1351_pp0_iter3_reg)) begin
            ap_phi_mux_result_18_phi_fu_256_p4 = zext_ln533_6_fu_1022_p1;
        end else if ((1'd1 == and_ln556_13_reg_1351_pp0_iter3_reg)) begin
            ap_phi_mux_result_18_phi_fu_256_p4 = result_17_fu_1027_p3;
        end else begin
            ap_phi_mux_result_18_phi_fu_256_p4 = ap_phi_reg_pp0_iter4_result_18_reg_253;
        end
    end else begin
        ap_phi_mux_result_18_phi_fu_256_p4 = ap_phi_reg_pp0_iter4_result_18_reg_253;
    end
end

always @ (*) begin
    if (((icmp_ln534_reg_1293 == 1'd0) & (1'd1 == and_ln556_1_reg_1297))) begin
        ap_phi_mux_result_3_phi_fu_198_p4 = result_2_reg_1301;
    end else begin
        ap_phi_mux_result_3_phi_fu_198_p4 = ap_phi_reg_pp0_iter1_result_3_reg_194;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293 == 1'd0)) begin
        if ((1'd0 == and_ln556_3_reg_1306)) begin
            ap_phi_mux_result_6_phi_fu_208_p4 = zext_ln533_1_fu_768_p1;
        end else if ((1'd1 == and_ln556_3_reg_1306)) begin
            ap_phi_mux_result_6_phi_fu_208_p4 = result_5_fu_804_p3;
        end else begin
            ap_phi_mux_result_6_phi_fu_208_p4 = ap_phi_reg_pp0_iter1_result_6_reg_205;
        end
    end else begin
        ap_phi_mux_result_6_phi_fu_208_p4 = ap_phi_reg_pp0_iter1_result_6_reg_205;
    end
end

always @ (*) begin
    if ((icmp_ln534_reg_1293_pp0_iter1_reg == 1'd0)) begin
        if ((1'd0 == and_ln556_5_reg_1315_pp0_iter1_reg)) begin
            ap_phi_mux_result_8_phi_fu_218_p4 = zext_ln533_2_fu_844_p1;
        end else if ((1'd1 == and_ln556_5_reg_1315_pp0_iter1_reg)) begin
            ap_phi_mux_result_8_phi_fu_218_p4 = result_7_fu_849_p3;
        end else begin
            ap_phi_mux_result_8_phi_fu_218_p4 = ap_phi_reg_pp0_iter2_result_8_reg_215;
        end
    end else begin
        ap_phi_mux_result_8_phi_fu_218_p4 = ap_phi_reg_pp0_iter2_result_8_reg_215;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = ap_phi_mux_result_11_phi_fu_276_p6;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln534_fu_384_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp79) & (1'd1 == and_ln541_2_fu_701_p2))) begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index = shl_ln535_fu_664_p2;
    end else if (((icmp_ln534_fu_384_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp28) & (1'd1 == and_ln556_1_fu_414_p2))) begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index = 3'd0;
    end else begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_return_index = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln534_fu_384_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp89) & (1'd1 == and_ln541_5_fu_758_p2))) begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index = or_ln_fu_719_p3;
    end else if (((icmp_ln534_fu_384_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_ignoreCallOp37) & (1'd1 == and_ln556_3_fu_474_p2))) begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index = 3'd1;
    end else begin
        grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_return_index = 'bx;
    end
end

assign and_ln541_1_fu_695_p2 = (xor_ln556_fu_390_p2 & icmp_ln541_fu_671_p2);

assign and_ln541_2_fu_701_p2 = (and_ln541_fu_689_p2 & and_ln541_1_fu_695_p2);

assign and_ln541_3_fu_746_p2 = (icmp_ln543_1_fu_740_p2 & icmp_ln542_1_fu_734_p2);

assign and_ln541_4_fu_752_p2 = (xor_ln556_fu_390_p2 & icmp_ln541_1_fu_728_p2);

assign and_ln541_5_fu_758_p2 = (and_ln541_4_fu_752_p2 & and_ln541_3_fu_746_p2);

assign and_ln541_fu_689_p2 = (icmp_ln543_fu_683_p2 & icmp_ln542_fu_677_p2);

assign and_ln556_10_fu_600_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_4_fu_594_p2);

assign and_ln556_11_fu_606_p2 = (icmp_ln557_4_fu_588_p2 & and_ln556_10_fu_600_p2);

assign and_ln556_12_fu_632_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_5_fu_626_p2);

assign and_ln556_13_fu_638_p2 = (icmp_ln557_5_fu_620_p2 & and_ln556_12_fu_632_p2);

assign and_ln556_1_fu_414_p2 = (icmp_ln557_fu_396_p2 & and_ln556_fu_408_p2);

assign and_ln556_2_fu_468_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_1_fu_462_p2);

assign and_ln556_3_fu_474_p2 = (icmp_ln557_1_fu_446_p2 & and_ln556_2_fu_468_p2);

assign and_ln556_4_fu_500_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_2_fu_494_p2);

assign and_ln556_5_fu_506_p2 = (icmp_ln557_2_fu_488_p2 & and_ln556_4_fu_500_p2);

assign and_ln556_6_fu_536_p2 = (xor_ln556_fu_390_p2 & tmp_56_fu_528_p3);

assign and_ln556_7_fu_542_p2 = (tmp_55_fu_520_p3 & and_ln556_6_fu_536_p2);

assign and_ln556_8_fu_568_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_3_fu_562_p2);

assign and_ln556_9_fu_574_p2 = (icmp_ln557_3_fu_556_p2 & and_ln556_8_fu_568_p2);

assign and_ln556_fu_408_p2 = (xor_ln556_fu_390_p2 & icmp_ln558_fu_402_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp28 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp37 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp43 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp49 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp55 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp61 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp67 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp79 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_ignoreCallOp89 = ~(1'b1 == 1'b1);

assign ap_phi_reg_pp0_iter0_result_1_reg_262 = 'bx;

assign ap_phi_reg_pp0_iter0_result_3_reg_194 = 'bx;

assign ap_phi_reg_pp0_iter1_result_6_reg_205 = 'bx;

assign ap_phi_reg_pp0_iter2_result_12_reg_224 = 'bx;

assign ap_phi_reg_pp0_iter2_result_8_reg_215 = 'bx;

assign ap_phi_reg_pp0_iter3_result_14_reg_234 = 'bx;

assign ap_phi_reg_pp0_iter3_result_16_reg_243 = 'bx;

assign ap_phi_reg_pp0_iter4_result_18_reg_253 = 'bx;

assign ap_phi_reg_pp0_iter5_result_11_reg_273 = 'bx;

assign blank_fu_356_p3 = ordered_cell_val_int_reg[32'd351];

assign first_return_fu_652_p3 = {{local_word_index_int_reg}, {1'd0}};

assign hit_word_count_fu_378_p2 = ($signed(zext_ln519_1_fu_337_p1) + $signed(4'd15));

assign icmp_ln534_fu_384_p2 = ((hit_word_count_fu_378_p2 > zext_ln519_fu_333_p1) ? 1'b1 : 1'b0);

assign icmp_ln541_1_fu_728_p2 = ((return_index_1_fu_711_p3 < zext_ln527_fu_374_p1) ? 1'b1 : 1'b0);

assign icmp_ln541_fu_671_p2 = ((first_return_fu_652_p3 < zext_ln527_fu_374_p1) ? 1'b1 : 1'b0);

assign icmp_ln542_1_fu_734_p2 = ((return_index_1_fu_711_p3 < zext_ln519_2_fu_341_p1) ? 1'b1 : 1'b0);

assign icmp_ln542_fu_677_p2 = ((first_return_fu_652_p3 < zext_ln519_2_fu_341_p1) ? 1'b1 : 1'b0);

assign icmp_ln543_1_fu_740_p2 = ((return_index_1_fu_711_p3 < 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln543_fu_683_p2 = ((first_return_fu_652_p3 < 4'd7) ? 1'b1 : 1'b0);

assign icmp_ln557_1_fu_446_p2 = ((tmp_50_fu_436_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln557_2_fu_488_p2 = ((valid_return_count_fu_364_p4 > 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln557_3_fu_556_p2 = ((valid_return_count_fu_364_p4 > 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln557_4_fu_588_p2 = ((valid_return_count_fu_364_p4 > 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln557_5_fu_620_p2 = ((valid_return_count_fu_364_p4 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln557_fu_396_p2 = ((valid_return_count_fu_364_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln558_1_fu_462_p2 = ((tmp_51_fu_452_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln558_2_fu_494_p2 = ((profile_serialized_return_slots_val_int_reg > 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln558_3_fu_562_p2 = ((profile_serialized_return_slots_val_int_reg > 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln558_4_fu_594_p2 = ((profile_serialized_return_slots_val_int_reg > 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln558_5_fu_626_p2 = ((profile_serialized_return_slots_val_int_reg == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln558_fu_402_p2 = ((profile_serialized_return_slots_val_int_reg != 3'd0) ? 1'b1 : 1'b0);

assign low16_1_fu_707_p1 = grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return[15:0];

assign low16_fu_764_p1 = grp_p_anonymous_namespace_read_packed_distance_hit_fu_291_ap_return[15:0];

assign or_ln1_fu_787_p4 = {{{tmp_49_fu_773_p4}, {1'd1}}, {trunc_ln563_fu_783_p1}};

assign or_ln2_fu_1053_p4 = {{{{1'd1}, {valid_return_count_reg_1287_pp0_iter3_reg}}}, {ap_phi_mux_result_18_phi_fu_256_p4}};

assign or_ln3_fu_1132_p3 = {{1'd1}, {result_23_fu_1114_p3}};

assign or_ln40_fu_1219_p2 = (tmp_69_fu_1204_p3 | line_faulted_read_reg_1265_pp0_iter4_reg);

assign or_ln4_fu_1184_p3 = {{1'd1}, {result_26_fu_1165_p3}};

assign or_ln563_1_fu_827_p4 = {{{tmp_54_fu_813_p4}, {1'd1}}, {trunc_ln563_1_fu_823_p1}};

assign or_ln563_2_fu_876_p4 = {{{tmp_58_fu_862_p4}, {1'd1}}, {trunc_ln563_2_fu_872_p1}};

assign or_ln563_3_fu_916_p4 = {{{tmp_60_fu_902_p4}, {1'd1}}, {trunc_ln563_3_fu_912_p1}};

assign or_ln563_4_fu_965_p4 = {{{tmp_62_fu_951_p4}, {1'd1}}, {trunc_ln563_4_fu_961_p1}};

assign or_ln563_5_fu_1005_p4 = {{{tmp_64_fu_991_p4}, {1'd1}}, {trunc_ln563_5_fu_1001_p1}};

assign or_ln_fu_719_p3 = {{trunc_ln535_fu_660_p1}, {1'd1}};

assign result_10_fu_1224_p3 = ((or_ln40_fu_1219_p2[0:0] == 1'b1) ? result_28_fu_1211_p3 : zext_ln533_12_fu_1200_p1);

assign result_13_fu_938_p3 = {{1'd1}, {select_ln561_3_reg_1383}};

assign result_15_fu_982_p3 = {{1'd1}, {select_ln561_4_fu_975_p3}};

assign result_17_fu_1027_p3 = {{1'd1}, {select_ln561_5_reg_1388}};

assign result_19_fu_1035_p3 = {{valid_return_count_reg_1287_pp0_iter3_reg}, {ap_phi_mux_result_18_phi_fu_256_p4}};

assign result_20_fu_1062_p3 = ((tmp_65_fu_1046_p3[0:0] == 1'b1) ? or_ln2_fu_1053_p4 : zext_ln533_7_fu_1042_p1);

assign result_21_fu_1088_p4 = {{{tmp_1_fu_1070_p4}, {tmp_2_fu_1079_p4}}, {result_20_fu_1062_p3}};

assign result_22_fu_1102_p5 = {{{{{{1'd1}, {tmp_1_fu_1070_p4}}}, {tmp_2_fu_1079_p4}}}, {result_20_fu_1062_p3}};

assign result_23_fu_1114_p3 = ((blank_reg_1282_pp0_iter3_reg[0:0] == 1'b1) ? result_22_fu_1102_p5 : zext_ln533_8_fu_1098_p1);

assign result_24_fu_1140_p3 = ((tmp_66_fu_1125_p3[0:0] == 1'b1) ? or_ln3_fu_1132_p3 : zext_ln533_9_fu_1121_p1);

assign result_25_fu_1158_p3 = {{1'd1}, {result_24_reg_1393}};

assign result_26_fu_1165_p3 = ((tmp_67_fu_1151_p3[0:0] == 1'b1) ? result_25_fu_1158_p3 : zext_ln533_10_fu_1148_p1);

assign result_27_fu_1192_p3 = ((tmp_68_fu_1177_p3[0:0] == 1'b1) ? or_ln4_fu_1184_p3 : zext_ln533_11_fu_1173_p1);

assign result_28_fu_1211_p3 = {{1'd1}, {result_27_fu_1192_p3}};

assign result_29_fu_1241_p4 = {{{{1'd1}, {tmp_3_fu_1232_p4}}}, {result_10_fu_1224_p3}};

assign result_2_fu_428_p3 = ((tmp_fu_420_p3[0:0] == 1'b1) ? 8'd129 : 8'd128);

assign result_4_fu_1257_p3 = {{low16_reg_1373_pp0_iter4_reg}, {ap_phi_reg_pp0_iter5_result_1_reg_262}};

assign result_5_fu_804_p3 = {{1'd1}, {select_ln561_fu_797_p3}};

assign result_7_fu_849_p3 = {{1'd1}, {select_ln561_1_reg_1378}};

assign result_9_fu_893_p3 = {{1'd1}, {select_ln561_2_fu_886_p3}};

assign return_index_1_fu_711_p3 = {{local_word_index_int_reg}, {1'd1}};

assign select_ln561_1_fu_837_p3 = ((tmp_53_reg_1319[0:0] == 1'b1) ? or_ln563_1_fu_827_p4 : ap_phi_mux_result_6_phi_fu_208_p4);

assign select_ln561_2_fu_886_p3 = ((tmp_57_reg_1328_pp0_iter1_reg[0:0] == 1'b1) ? or_ln563_2_fu_876_p4 : ap_phi_mux_result_8_phi_fu_218_p4);

assign select_ln561_3_fu_926_p3 = ((tmp_59_reg_1337_pp0_iter1_reg[0:0] == 1'b1) ? or_ln563_3_fu_916_p4 : ap_phi_mux_result_12_phi_fu_227_p4);

assign select_ln561_4_fu_975_p3 = ((tmp_61_reg_1346_pp0_iter2_reg[0:0] == 1'b1) ? or_ln563_4_fu_965_p4 : ap_phi_mux_result_14_phi_fu_237_p4);

assign select_ln561_5_fu_1015_p3 = ((tmp_63_reg_1355_pp0_iter2_reg[0:0] == 1'b1) ? or_ln563_5_fu_1005_p4 : ap_phi_mux_result_16_phi_fu_246_p4);

assign select_ln561_fu_797_p3 = ((tmp_52_reg_1310[0:0] == 1'b1) ? or_ln1_fu_787_p4 : ap_phi_mux_result_3_phi_fu_198_p4);

assign shl_ln535_fu_664_p2 = local_word_index_int_reg << 3'd1;

assign tmp_1_fu_1070_p4 = {{ordered_cell_val_read_reg_1270_pp0_iter3_reg[7:5]}};

assign tmp_2_fu_1079_p4 = {{ordered_cell_val_read_reg_1270_pp0_iter3_reg[3:2]}};

assign tmp_3_fu_1232_p4 = {{ordered_cell_val_read_reg_1270_pp0_iter4_reg[140:138]}};

assign tmp_49_fu_773_p4 = {{ap_phi_mux_result_3_phi_fu_198_p4[7:2]}};

assign tmp_50_fu_436_p4 = {{ordered_cell_val_int_reg[11:10]}};

assign tmp_51_fu_452_p4 = {{profile_serialized_return_slots_val_int_reg[2:1]}};

assign tmp_54_fu_813_p4 = {{ap_phi_mux_result_6_phi_fu_208_p4[8:3]}};

assign tmp_55_fu_520_p3 = ordered_cell_val_int_reg[32'd11];

assign tmp_56_fu_528_p3 = profile_serialized_return_slots_val_int_reg[32'd2];

assign tmp_58_fu_862_p4 = {{ap_phi_mux_result_8_phi_fu_218_p4[9:4]}};

assign tmp_60_fu_902_p4 = {{ap_phi_mux_result_12_phi_fu_227_p4[10:5]}};

assign tmp_62_fu_951_p4 = {{ap_phi_mux_result_14_phi_fu_237_p4[11:6]}};

assign tmp_64_fu_991_p4 = {{ap_phi_mux_result_16_phi_fu_246_p4[12:7]}};

assign tmp_65_fu_1046_p3 = ordered_cell_val_read_reg_1270_pp0_iter3_reg[32'd8];

assign tmp_66_fu_1125_p3 = ordered_cell_val_read_reg_1270_pp0_iter3_reg[32'd136];

assign tmp_67_fu_1151_p3 = ordered_cell_val_read_reg_1270_pp0_iter4_reg[32'd134];

assign tmp_68_fu_1177_p3 = ordered_cell_val_read_reg_1270_pp0_iter4_reg[32'd135];

assign tmp_69_fu_1204_p3 = ordered_cell_val_read_reg_1270_pp0_iter4_reg[32'd137];

assign tmp_fu_420_p3 = grp_p_anonymous_namespace_read_packed_distance_hit_fu_284_ap_return[32'd16];

assign trunc_ln521_fu_345_p1 = ordered_cell_val_int_reg[133:0];

assign trunc_ln535_fu_660_p1 = local_word_index_int_reg[1:0];

assign trunc_ln563_1_fu_823_p1 = ap_phi_mux_result_6_phi_fu_208_p4[1:0];

assign trunc_ln563_2_fu_872_p1 = ap_phi_mux_result_8_phi_fu_218_p4[2:0];

assign trunc_ln563_3_fu_912_p1 = ap_phi_mux_result_12_phi_fu_227_p4[3:0];

assign trunc_ln563_4_fu_961_p1 = ap_phi_mux_result_14_phi_fu_237_p4[4:0];

assign trunc_ln563_5_fu_1001_p1 = ap_phi_mux_result_16_phi_fu_246_p4[5:0];

assign trunc_ln563_fu_783_p1 = ap_phi_mux_result_3_phi_fu_198_p4[0:0];

assign valid_return_count_fu_364_p4 = {{ordered_cell_val_int_reg[11:9]}};

assign xor_ln556_fu_390_p2 = (blank_fu_356_p3 ^ 1'd1);

assign zext_ln519_1_fu_337_p1 = profile_cell_word_count_val_int_reg;

assign zext_ln519_2_fu_341_p1 = profile_serialized_return_slots_val_int_reg;

assign zext_ln519_fu_333_p1 = local_word_index_int_reg;

assign zext_ln527_fu_374_p1 = valid_return_count_fu_364_p4;

assign zext_ln533_10_fu_1148_p1 = result_24_reg_1393;

assign zext_ln533_11_fu_1173_p1 = result_26_fu_1165_p3;

assign zext_ln533_12_fu_1200_p1 = result_27_fu_1192_p3;

assign zext_ln533_1_fu_768_p1 = ap_phi_mux_result_3_phi_fu_198_p4;

assign zext_ln533_2_fu_844_p1 = result_6_reg_205;

assign zext_ln533_3_fu_857_p1 = ap_phi_mux_result_8_phi_fu_218_p4;

assign zext_ln533_4_fu_933_p1 = result_12_reg_224;

assign zext_ln533_5_fu_946_p1 = ap_phi_mux_result_14_phi_fu_237_p4;

assign zext_ln533_6_fu_1022_p1 = result_16_reg_243;

assign zext_ln533_7_fu_1042_p1 = result_19_fu_1035_p3;

assign zext_ln533_8_fu_1098_p1 = result_21_fu_1088_p4;

assign zext_ln533_9_fu_1121_p1 = result_23_fu_1114_p3;

assign zext_ln533_fu_1252_p1 = ap_phi_reg_pp0_iter5_result_1_reg_262;

always @ (posedge ap_clk) begin
    result_2_reg_1301[7:1] <= 7'b1000000;
end

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_make_packed17_cell_word
