// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_real_shot_metadata (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        canonical_line_word_out_TREADY,
        canonical_line_word_out_TDATA,
        canonical_line_word_out_TVALID,
        context_val,
        profile_raw_line_words_val,
        first_column,
        last_column,
        line_faulted
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   canonical_line_word_out_TREADY;
output  [63:0] canonical_line_word_out_TDATA;
output   canonical_line_word_out_TVALID;
input  [160:0] context_val;
input  [8:0] profile_raw_line_words_val;
input  [0:0] first_column;
input  [0:0] last_column;
input  [0:0] line_faulted;

reg ap_idle;
reg canonical_line_word_out_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln505_fu_187_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    canonical_line_word_out_TDATA_blk_n;
wire    ap_block_pp0_stage0_grp1;
reg    ap_block_pp0_stage0_11001_grp1;
reg   [2:0] word_index_1_reg_584;
reg    ap_block_pp0_stage0_11001;
wire   [3:0] result_31_fu_231_p3;
reg   [3:0] result_31_reg_593;
reg   [2:0] word_index_fu_138;
wire   [2:0] add_ln506_fu_193_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_word_index_1;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [0:0] tmp_70_fu_199_p3;
wire   [0:0] tmp_71_fu_215_p3;
wire   [3:0] result_30_fu_223_p3;
wire   [3:0] select_ln40_fu_207_p3;
wire   [5:0] zext_ln406_fu_259_p1;
wire   [6:0] or_ln_fu_262_p3;
wire   [6:0] zext_ln360_fu_256_p1;
wire   [6:0] result_32_fu_270_p3;
wire   [0:0] tmp_72_fu_281_p3;
wire   [7:0] or_ln5_fu_288_p3;
wire   [7:0] zext_ln360_1_fu_277_p1;
wire   [7:0] result_33_fu_296_p3;
wire   [0:0] tmp_73_fu_308_p3;
wire   [8:0] or_ln6_fu_315_p3;
wire   [8:0] zext_ln360_2_fu_304_p1;
wire   [8:0] result_34_fu_323_p3;
wire   [0:0] tmp_74_fu_335_p3;
wire   [9:0] or_ln7_fu_342_p3;
wire   [9:0] zext_ln360_3_fu_331_p1;
wire   [9:0] result_35_fu_350_p3;
wire   [14:0] tmp_45_fu_387_p4;
wire   [15:0] tmp_fu_378_p4;
wire   [30:0] result_37_fu_396_p3;
wire   [7:0] tmp_4_fu_408_p4;
wire   [18:0] result_38_fu_417_p4;
wire   [1:0] word_index_2_fu_244_p1;
wire   [0:0] tmp_75_fu_362_p3;
wire   [0:0] icmp_ln361_2_fu_443_p2;
wire   [0:0] xor_ln40_fu_455_p2;
wire   [0:0] icmp_ln361_fu_431_p2;
wire   [0:0] icmp_ln361_1_fu_437_p2;
wire   [0:0] and_ln361_fu_449_p2;
wire   [0:0] and_ln361_1_fu_461_p2;
wire   [31:0] result_39_fu_479_p2;
wire   [31:0] result_39_fu_479_p4;
wire   [31:0] result_39_fu_479_p6;
wire   [31:0] result_39_fu_479_p8;
wire   [31:0] result_39_fu_479_p10;
wire   [31:0] result_39_fu_479_p11;
wire   [3:0] result_39_fu_479_p12;
wire   [31:0] result_39_fu_479_p13;
wire   [0:0] line_start_fu_507_p2;
wire   [8:0] zext_ln32_1_fu_516_p1;
wire   [33:0] zext_ln32_fu_512_p1;
wire   [58:0] result_40_fu_520_p10;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [3:0] result_39_fu_479_p1;
wire   [3:0] result_39_fu_479_p3;
wire   [3:0] result_39_fu_479_p5;
wire   [3:0] result_39_fu_479_p7;
wire   [3:0] result_39_fu_479_p9;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 word_index_fu_138 = 3'd0;
#0 ap_done_reg = 1'b0;
end

(* dissolve_hierarchy = "yes" *) gpx_lane_word_formatter_hls_sparsemux_11_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h8 ),
    .din0_WIDTH( 32 ),
    .CASE1( 4'h4 ),
    .din1_WIDTH( 32 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 4'h1 ),
    .din3_WIDTH( 32 ),
    .CASE4( 4'h0 ),
    .din4_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
sparsemux_11_4_32_1_1_U15(
    .din0(result_39_fu_479_p2),
    .din1(result_39_fu_479_p4),
    .din2(result_39_fu_479_p6),
    .din3(result_39_fu_479_p8),
    .din4(result_39_fu_479_p10),
    .def(result_39_fu_479_p11),
    .sel(result_39_fu_479_p12),
    .dout(result_39_fu_479_p13)
);

gpx_lane_word_formatter_hls_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln505_fu_187_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            word_index_fu_138 <= add_ln506_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            word_index_fu_138 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_31_reg_593[3 : 2] <= result_31_fu_231_p3[3 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        word_index_1_reg_584 <= ap_sig_allocacmp_word_index_1;
    end
end

always @ (*) begin
    if (((icmp_ln505_fu_187_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_word_index_1 = 3'd0;
    end else begin
        ap_sig_allocacmp_word_index_1 = word_index_fu_138;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        canonical_line_word_out_TDATA_blk_n = canonical_line_word_out_TREADY;
    end else begin
        canonical_line_word_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        canonical_line_word_out_TVALID = 1'b1;
    end else begin
        canonical_line_word_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln506_fu_193_p2 = (ap_sig_allocacmp_word_index_1 + 3'd1);

assign and_ln361_1_fu_461_p2 = (xor_ln40_fu_455_p2 & icmp_ln361_2_fu_443_p2);

assign and_ln361_fu_449_p2 = (tmp_75_fu_362_p3 & icmp_ln361_2_fu_443_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((canonical_line_word_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((canonical_line_word_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((canonical_line_word_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((canonical_line_word_out_TREADY == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign canonical_line_word_out_TDATA = result_40_fu_520_p10;

assign icmp_ln361_1_fu_437_p2 = ((word_index_2_fu_244_p1 == 2'd2) ? 1'b1 : 1'b0);

assign icmp_ln361_2_fu_443_p2 = ((word_index_2_fu_244_p1 == 2'd3) ? 1'b1 : 1'b0);

assign icmp_ln361_fu_431_p2 = ((word_index_2_fu_244_p1 == 2'd1) ? 1'b1 : 1'b0);

assign icmp_ln505_fu_187_p2 = ((ap_sig_allocacmp_word_index_1 == 3'd4) ? 1'b1 : 1'b0);

assign line_start_fu_507_p2 = ((word_index_1_reg_584 == 3'd0) ? 1'b1 : 1'b0);

assign or_ln5_fu_288_p3 = {{1'd1}, {result_32_fu_270_p3}};

assign or_ln6_fu_315_p3 = {{1'd1}, {result_33_fu_296_p3}};

assign or_ln7_fu_342_p3 = {{1'd1}, {result_34_fu_323_p3}};

assign or_ln_fu_262_p3 = {{1'd1}, {zext_ln406_fu_259_p1}};

assign result_30_fu_223_p3 = ((tmp_70_fu_199_p3[0:0] == 1'b1) ? 4'd13 : 4'd9);

assign result_31_fu_231_p3 = ((tmp_71_fu_215_p3[0:0] == 1'b1) ? result_30_fu_223_p3 : select_ln40_fu_207_p3);

assign result_32_fu_270_p3 = ((line_faulted[0:0] == 1'b1) ? or_ln_fu_262_p3 : zext_ln360_fu_256_p1);

assign result_33_fu_296_p3 = ((tmp_72_fu_281_p3[0:0] == 1'b1) ? or_ln5_fu_288_p3 : zext_ln360_1_fu_277_p1);

assign result_34_fu_323_p3 = ((tmp_73_fu_308_p3[0:0] == 1'b1) ? or_ln6_fu_315_p3 : zext_ln360_2_fu_304_p1);

assign result_35_fu_350_p3 = ((tmp_74_fu_335_p3[0:0] == 1'b1) ? or_ln7_fu_342_p3 : zext_ln360_3_fu_331_p1);

assign result_37_fu_396_p3 = {{tmp_45_fu_387_p4}, {tmp_fu_378_p4}};

assign result_38_fu_417_p4 = {{{tmp_4_fu_408_p4}, {1'd1}}, {result_35_fu_350_p3}};

assign result_39_fu_479_p10 = {{context_val[126:95]}};

assign result_39_fu_479_p11 = 'bx;

assign result_39_fu_479_p12 = {{{{icmp_ln361_fu_431_p2}, {icmp_ln361_1_fu_437_p2}}, {and_ln361_fu_449_p2}}, {and_ln361_1_fu_461_p2}};

assign result_39_fu_479_p2 = {{context_val[158:127]}};

assign result_39_fu_479_p4 = result_37_fu_396_p3;

assign result_39_fu_479_p6 = result_38_fu_417_p4;

assign result_39_fu_479_p8 = result_35_fu_350_p3;

assign result_40_fu_520_p10 = {{{{{{{{{line_faulted}, {1'd0}}, {last_column}}, {first_column}}, {2'd0}}, {line_start_fu_507_p2}}, {profile_raw_line_words_val}}, {zext_ln32_1_fu_516_p1}}, {zext_ln32_fu_512_p1}};

assign select_ln40_fu_207_p3 = ((tmp_70_fu_199_p3[0:0] == 1'b1) ? 4'd5 : 4'd1);

assign tmp_45_fu_387_p4 = {{context_val[18:4]}};

assign tmp_4_fu_408_p4 = {{context_val[45:38]}};

assign tmp_70_fu_199_p3 = context_val[32'd19];

assign tmp_71_fu_215_p3 = context_val[32'd37];

assign tmp_72_fu_281_p3 = context_val[32'd159];

assign tmp_73_fu_308_p3 = context_val[32'd160];

assign tmp_74_fu_335_p3 = context_val[32'd36];

assign tmp_75_fu_362_p3 = context_val[32'd46];

assign tmp_fu_378_p4 = {{context_val[35:20]}};

assign word_index_2_fu_244_p1 = word_index_1_reg_584[1:0];

assign xor_ln40_fu_455_p2 = (tmp_75_fu_362_p3 ^ 1'd1);

assign zext_ln32_1_fu_516_p1 = word_index_2_fu_244_p1;

assign zext_ln32_fu_512_p1 = result_39_fu_479_p13;

assign zext_ln360_1_fu_277_p1 = result_32_fu_270_p3;

assign zext_ln360_2_fu_304_p1 = result_33_fu_296_p3;

assign zext_ln360_3_fu_331_p1 = result_34_fu_323_p3;

assign zext_ln360_fu_256_p1 = result_31_reg_593;

assign zext_ln406_fu_259_p1 = result_31_reg_593;

always @ (posedge ap_clk) begin
    result_31_reg_593[1:0] <= 2'b01;
end

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_real_shot_metadata
