// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_ordered_cell (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        canonical_line_word_out_TDATA,
        canonical_line_word_out_TVALID,
        canonical_line_word_out_TREADY,
        ordered_cell_val,
        profile_serialized_return_slots_val2,
        profile_cell_word_count_val,
        profile_raw_line_words_val
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] canonical_line_word_out_TDATA;
output   canonical_line_word_out_TVALID;
input   canonical_line_word_out_TREADY;
input  [352:0] ordered_cell_val;
input  [2:0] profile_serialized_return_slots_val2;
input  [2:0] profile_cell_word_count_val;
input  [8:0] profile_raw_line_words_val;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] canonical_line_word_out_TDATA;
reg canonical_line_word_out_TVALID;

(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [334:0] empty_fu_115_p1;
reg   [334:0] empty_reg_244;
wire   [351:0] empty_607_fu_119_p1;
reg   [351:0] empty_607_reg_249;
reg   [160:0] context_cast_reg_254;
reg   [5:0] tmp_reg_259;
wire   [0:0] first_cell_fu_144_p3;
reg   [0:0] first_cell_reg_266;
reg   [0:0] last_cell_reg_270;
reg   [0:0] first_column_reg_275;
reg   [0:0] last_column_reg_280;
reg   [0:0] line_faulted_reg_285;
wire   [6:0] shl_ln_fu_190_p3;
reg   [6:0] shl_ln_reg_291;
wire    ap_CS_fsm_state2;
wire   [7:0] add_ln130_fu_201_p2;
reg   [7:0] add_ln130_reg_297;
wire   [7:0] shl_ln3_fu_213_p3;
reg   [7:0] shl_ln3_reg_303;
wire    ap_CS_fsm_state3;
wire   [8:0] add_ln134_fu_221_p2;
reg   [8:0] add_ln134_reg_308;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_done;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_idle;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_ready;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TREADY;
wire   [63:0] grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TDATA;
wire    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TVALID;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_idle;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_ready;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TREADY;
wire   [63:0] grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TDATA;
wire    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TVALID;
reg    grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg;
reg   [63:0] canonical_line_word_out_TDATA_reg;
reg    grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [7:0] zext_ln130_2_fu_197_p1;
wire   [7:0] zext_ln128_fu_187_p1;
wire   [8:0] zext_ln132_fu_210_p1;
wire   [8:0] zext_ln130_fu_207_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_block_state2_on_subcall_done;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 4'd1;
#0 grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg = 1'b0;
#0 grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg = 1'b0;
end

gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_real_shot_metadata grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start),
    .ap_done(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_done),
    .ap_idle(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_ready),
    .canonical_line_word_out_TREADY(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TREADY),
    .canonical_line_word_out_TDATA(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TDATA),
    .canonical_line_word_out_TVALID(grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TVALID),
    .context_val(context_cast_reg_254),
    .profile_raw_line_words_val(profile_raw_line_words_val),
    .first_column(first_column_reg_275),
    .last_column(last_column_reg_280),
    .line_faulted(line_faulted_reg_285)
);

gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1 grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start),
    .ap_done(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done),
    .ap_idle(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_ready),
    .canonical_line_word_out_TREADY(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TREADY),
    .profile_cell_word_count_val(profile_cell_word_count_val),
    .add_ln134(add_ln134_reg_308),
    .zext_ln134(shl_ln3_reg_303),
    .zext_ln132(add_ln130_reg_297),
    .zext_ln130(shl_ln_reg_291),
    .empty_60(last_cell_reg_270),
    .empty_61(empty_607_reg_249),
    .profile_serialized_return_slots_val2(profile_serialized_return_slots_val2),
    .empty(line_faulted_reg_285),
    .ordered_cell_val(empty_reg_244),
    .profile_raw_line_words_val(profile_raw_line_words_val),
    .canonical_line_word_out_TDATA(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TDATA),
    .canonical_line_word_out_TVALID(grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TVALID)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (first_cell_fu_144_p3 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TVALID == 1'b1))) begin
        canonical_line_word_out_TDATA_reg <= grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TDATA;
    end else if (((grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TVALID == 1'b1) & (first_cell_reg_266 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        canonical_line_word_out_TDATA_reg <= grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln130_reg_297 <= add_ln130_fu_201_p2;
        shl_ln_reg_291[6 : 1] <= shl_ln_fu_190_p3[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln134_reg_308 <= add_ln134_fu_221_p2;
        shl_ln3_reg_303[7 : 2] <= shl_ln3_fu_213_p3[7 : 2];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        context_cast_reg_254 <= {{ordered_cell_val[301:141]}};
        empty_607_reg_249 <= empty_607_fu_119_p1;
        empty_reg_244 <= empty_fu_115_p1;
        first_cell_reg_266 <= ordered_cell_val[32'd331];
        first_column_reg_275 <= ordered_cell_val[32'd333];
        last_cell_reg_270 <= ordered_cell_val[32'd332];
        last_column_reg_280 <= ordered_cell_val[32'd334];
        line_faulted_reg_285 <= ordered_cell_val[32'd352];
        tmp_reg_259 <= {{ordered_cell_val[324:319]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_on_subcall_done)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TVALID == 1'b1))) begin
        canonical_line_word_out_TDATA = grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TDATA;
    end else if (((grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TVALID == 1'b1) & (first_cell_reg_266 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        canonical_line_word_out_TDATA = grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TDATA;
    end else begin
        canonical_line_word_out_TDATA = canonical_line_word_out_TDATA_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        canonical_line_word_out_TVALID = grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TVALID;
    end else if (((first_cell_reg_266 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        canonical_line_word_out_TVALID = grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TVALID;
    end else begin
        canonical_line_word_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_on_subcall_done) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln130_fu_201_p2 = (zext_ln130_2_fu_197_p1 + zext_ln128_fu_187_p1);

assign add_ln134_fu_221_p2 = (zext_ln132_fu_210_p1 + zext_ln130_fu_207_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state2_on_subcall_done = ((grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_done == 1'b0) & (first_cell_reg_266 == 1'd1));
end

assign empty_607_fu_119_p1 = ordered_cell_val[351:0];

assign empty_fu_115_p1 = ordered_cell_val[334:0];

assign first_cell_fu_144_p3 = ordered_cell_val[32'd331];

assign grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start = grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_ap_start_reg;

assign grp_p_anonymous_namespace_emit_ordered_cell_Pipeline_VITIS_LOOP_639_1_fu_98_canonical_line_word_out_TREADY = (canonical_line_word_out_TREADY & ap_CS_fsm_state4);

assign grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start = grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_ap_start_reg;

assign grp_p_anonymous_namespace_emit_real_shot_metadata_fu_86_canonical_line_word_out_TREADY = (canonical_line_word_out_TREADY & ap_CS_fsm_state2);

assign shl_ln3_fu_213_p3 = {{tmp_reg_259}, {2'd0}};

assign shl_ln_fu_190_p3 = {{tmp_reg_259}, {1'd0}};

assign zext_ln128_fu_187_p1 = tmp_reg_259;

assign zext_ln130_2_fu_197_p1 = shl_ln_fu_190_p3;

assign zext_ln130_fu_207_p1 = shl_ln_reg_291;

assign zext_ln132_fu_210_p1 = add_ln130_reg_297;

always @ (posedge ap_clk) begin
    shl_ln_reg_291[0] <= 1'b0;
    shl_ln3_reg_303[1:0] <= 2'b00;
end

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_ordered_cell
