// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit (
        ap_ready,
        cell_val,
        return_index,
        ap_return,
        ap_rst
);


output   ap_ready;
input  [133:0] cell_val;
input  [2:0] return_index;
output  [16:0] ap_return;
input   ap_rst;

wire   [0:0] icmp_ln445_fu_152_p2;
wire   [0:0] icmp_ln445_1_fu_158_p2;
wire   [0:0] icmp_ln445_2_fu_164_p2;
wire   [0:0] icmp_ln445_3_fu_170_p2;
wire   [0:0] icmp_ln445_4_fu_176_p2;
wire   [0:0] icmp_ln445_5_fu_182_p2;
wire   [16:0] retval_0_in_fu_204_p2;
wire   [16:0] retval_0_in_fu_204_p4;
wire   [16:0] retval_0_in_fu_204_p6;
wire   [16:0] retval_0_in_fu_204_p8;
wire   [16:0] retval_0_in_fu_204_p10;
wire   [16:0] retval_0_in_fu_204_p12;
wire   [16:0] retval_0_in_fu_204_p14;
wire   [16:0] retval_0_in_fu_204_p15;
wire   [5:0] retval_0_in_fu_204_p16;
wire   [16:0] retval_0_in_fu_204_p17;
wire  signed [5:0] retval_0_in_fu_204_p1;
wire   [5:0] retval_0_in_fu_204_p3;
wire   [5:0] retval_0_in_fu_204_p5;
wire   [5:0] retval_0_in_fu_204_p7;
wire   [5:0] retval_0_in_fu_204_p9;
wire   [5:0] retval_0_in_fu_204_p11;
wire   [5:0] retval_0_in_fu_204_p13;

(* dissolve_hierarchy = "yes" *) gpx_lane_word_formatter_hls_sparsemux_15_6_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 6'h20 ),
    .din0_WIDTH( 17 ),
    .CASE1( 6'h10 ),
    .din1_WIDTH( 17 ),
    .CASE2( 6'h8 ),
    .din2_WIDTH( 17 ),
    .CASE3( 6'h4 ),
    .din3_WIDTH( 17 ),
    .CASE4( 6'h2 ),
    .din4_WIDTH( 17 ),
    .CASE5( 6'h1 ),
    .din5_WIDTH( 17 ),
    .CASE6( 6'h0 ),
    .din6_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
sparsemux_15_6_17_1_1_U23(
    .din0(retval_0_in_fu_204_p2),
    .din1(retval_0_in_fu_204_p4),
    .din2(retval_0_in_fu_204_p6),
    .din3(retval_0_in_fu_204_p8),
    .din4(retval_0_in_fu_204_p10),
    .din5(retval_0_in_fu_204_p12),
    .din6(retval_0_in_fu_204_p14),
    .def(retval_0_in_fu_204_p15),
    .sel(retval_0_in_fu_204_p16),
    .dout(retval_0_in_fu_204_p17)
);

assign ap_ready = 1'b1;

assign ap_return = retval_0_in_fu_204_p17;

assign icmp_ln445_1_fu_158_p2 = ((return_index == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln445_2_fu_164_p2 = ((return_index == 3'd4) ? 1'b1 : 1'b0);

assign icmp_ln445_3_fu_170_p2 = ((return_index == 3'd3) ? 1'b1 : 1'b0);

assign icmp_ln445_4_fu_176_p2 = ((return_index == 3'd2) ? 1'b1 : 1'b0);

assign icmp_ln445_5_fu_182_p2 = ((return_index == 3'd1) ? 1'b1 : 1'b0);

assign icmp_ln445_fu_152_p2 = ((return_index == 3'd6) ? 1'b1 : 1'b0);

assign retval_0_in_fu_204_p10 = {{cell_val[65:49]}};

assign retval_0_in_fu_204_p12 = {{cell_val[48:32]}};

assign retval_0_in_fu_204_p14 = {{cell_val[31:15]}};

assign retval_0_in_fu_204_p15 = 'bx;

assign retval_0_in_fu_204_p16 = {{{{{{icmp_ln445_fu_152_p2}, {icmp_ln445_1_fu_158_p2}}, {icmp_ln445_2_fu_164_p2}}, {icmp_ln445_3_fu_170_p2}}, {icmp_ln445_4_fu_176_p2}}, {icmp_ln445_5_fu_182_p2}};

assign retval_0_in_fu_204_p2 = {{cell_val[133:117]}};

assign retval_0_in_fu_204_p4 = {{cell_val[116:100]}};

assign retval_0_in_fu_204_p6 = {{cell_val[99:83]}};

assign retval_0_in_fu_204_p8 = {{cell_val[82:66]}};

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_read_packed_distance_hit
