// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        canonical_line_word_out_TDATA,
        canonical_line_word_out_TVALID,
        canonical_line_word_out_TREADY,
        context_val,
        profile_planned_shot_columns_val,
        profile_raw_line_words_val,
        line_faulted
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] canonical_line_word_out_TDATA;
output   canonical_line_word_out_TVALID;
input   canonical_line_word_out_TREADY;
input  [37:0] context_val;
input  [15:0] profile_planned_shot_columns_val;
input  [8:0] profile_raw_line_words_val;
input  [0:0] line_faulted;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[63:0] canonical_line_word_out_TDATA;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [15:0] shot_column_fu_82_p4;
reg   [15:0] shot_column_reg_131;
wire   [0:0] last_column_fu_106_p2;
reg   [0:0] last_column_reg_137;
wire    ap_CS_fsm_state2;
wire   [0:0] first_column_fu_112_p2;
reg   [0:0] first_column_reg_152;
wire   [16:0] result_s_fu_118_p3;
reg   [16:0] result_s_reg_157;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_idle;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY;
wire   [63:0] grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA;
wire    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID;
reg    grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [63:0] canonical_line_word_out_TDATA_reg;
wire   [16:0] zext_ln473_fu_92_p1;
wire   [16:0] add_ln473_fu_96_p2;
wire   [16:0] zext_ln473_1_fu_102_p1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg = 1'b0;
end

gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1 grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start),
    .ap_done(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done),
    .ap_idle(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_idle),
    .ap_ready(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready),
    .canonical_line_word_out_TREADY(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY),
    .profile_raw_line_words_val(profile_raw_line_words_val),
    .context_val(context_val),
    .line_faulted(line_faulted),
    .result_42(result_s_reg_157),
    .last_column(last_column_reg_137),
    .first_column(first_column_reg_152),
    .canonical_line_word_out_TDATA(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA),
    .canonical_line_word_out_TVALID(grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= 1'b1;
        end else if ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_ready == 1'b1)) begin
            grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        canonical_line_word_out_TDATA_reg <= grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        first_column_reg_152 <= first_column_fu_112_p2;
        result_s_reg_157[15 : 0] <= result_s_fu_118_p3[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        last_column_reg_137 <= last_column_fu_106_p2;
        shot_column_reg_131 <= {{context_val[35:20]}};
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)) | ((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
        canonical_line_word_out_TDATA = grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TDATA;
    end else begin
        canonical_line_word_out_TDATA = canonical_line_word_out_TDATA_reg;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln473_fu_96_p2 = (zext_ln473_fu_92_p1 + 17'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign canonical_line_word_out_TVALID = grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TVALID;

assign first_column_fu_112_p2 = ((shot_column_reg_131 == 16'd0) ? 1'b1 : 1'b0);

assign grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start = grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_ap_start_reg;

assign grp_p_anonymous_namespace_emit_missing_shot_line_Pipeline_VITIS_LOOP_474_1_fu_68_canonical_line_word_out_TREADY = (canonical_line_word_out_TREADY & ap_CS_fsm_state3);

assign last_column_fu_106_p2 = ((add_ln473_fu_96_p2 == zext_ln473_1_fu_102_p1) ? 1'b1 : 1'b0);

assign result_s_fu_118_p3 = {{1'd1}, {shot_column_reg_131}};

assign shot_column_fu_82_p4 = {{context_val[35:20]}};

assign zext_ln473_1_fu_102_p1 = profile_planned_shot_columns_val;

assign zext_ln473_fu_92_p1 = shot_column_fu_82_p4;

always @ (posedge ap_clk) begin
    result_s_reg_157[16] <= 1'b1;
end

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_missing_shot_line
