// ==============================================================
// Generated by Vitis HLS v2025.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* DowngradeIPIdentifiedWarnings="yes" *)
module gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_footer_line (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        canonical_line_word_out_TDATA,
        canonical_line_word_out_TVALID,
        canonical_line_word_out_TREADY,
        close_result_val,
        profile_slope_is_rise_val,
        profile_output_width_code_val,
        profile_cell_slot_count_val,
        profile_serialized_return_slots_val,
        profile_planned_shot_columns_val,
        profile_hsize_words_val,
        profile_hsize_bytes_val,
        profile_vsize_lines_val,
        completed_lines,
        logical_word_offset,
        final_footer_line,
        p_anonymous_namespace_any_shot_line_fault,
        p_anonymous_namespace_any_missing_shot_line
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state4 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [63:0] canonical_line_word_out_TDATA;
output   canonical_line_word_out_TVALID;
input   canonical_line_word_out_TREADY;
input  [86:0] close_result_val;
input  [0:0] profile_slope_is_rise_val;
input  [1:0] profile_output_width_code_val;
input  [5:0] profile_cell_slot_count_val;
input  [2:0] profile_serialized_return_slots_val;
input  [15:0] profile_planned_shot_columns_val;
input  [8:0] profile_hsize_words_val;
input  [15:0] profile_hsize_bytes_val;
input  [15:0] profile_vsize_lines_val;
input  [15:0] completed_lines;
input  [7:0] logical_word_offset;
input  [0:0] final_footer_line;
input  [0:0] p_anonymous_namespace_any_shot_line_fault;
input  [0:0] p_anonymous_namespace_any_missing_shot_line;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg canonical_line_word_out_TVALID;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    canonical_line_word_out_TDATA_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0_grp1;
wire   [0:0] count_mismatch_fu_259_p2;
reg   [0:0] count_mismatch_reg_807;
wire   [9:0] zext_ln769_fu_265_p1;
reg   [9:0] zext_ln769_reg_812;
wire   [31:0] result_52_fu_269_p3;
reg   [31:0] result_52_reg_817;
wire   [16:0] zext_ln728_fu_277_p1;
reg   [16:0] zext_ln728_reg_822;
wire   [16:0] or_ln_fu_281_p3;
reg   [16:0] or_ln_reg_827;
reg   [8:0] line_word_index_1_reg_842;
reg    ap_block_pp0_stage0_11001;
wire   [0:0] line_end_fu_316_p2;
reg   [0:0] line_end_reg_851;
wire   [0:0] icmp_ln779_fu_340_p2;
reg   [0:0] icmp_ln779_reg_857;
wire   [16:0] result_53_fu_357_p3;
reg   [16:0] result_53_reg_868;
reg    ap_block_pp0_stage0_11001_grp1;
wire   [0:0] icmp_ln670_fu_363_p2;
reg   [0:0] icmp_ln670_reg_874;
wire   [0:0] icmp_ln670_1_fu_369_p2;
reg   [0:0] icmp_ln670_1_reg_879;
wire   [0:0] icmp_ln670_2_fu_375_p2;
reg   [0:0] icmp_ln670_2_reg_884;
wire   [0:0] icmp_ln670_3_fu_381_p2;
reg   [0:0] icmp_ln670_3_reg_889;
wire   [0:0] icmp_ln670_4_fu_387_p2;
reg   [0:0] icmp_ln670_4_reg_894;
wire   [0:0] and_ln670_5_fu_399_p2;
reg   [0:0] and_ln670_5_reg_899;
wire   [0:0] icmp_ln670_6_fu_405_p2;
reg   [0:0] icmp_ln670_6_reg_904;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln769_fu_305_p2;
reg    ap_condition_pp0_exit_iter0_state2;
reg   [8:0] line_word_index_fu_176;
wire   [8:0] add_ln774_fu_310_p2;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_01001_grp1;
wire   [9:0] zext_ln776_fu_321_p1;
wire   [9:0] logical_word_index_fu_325_p2;
wire   [6:0] tmp_fu_330_p4;
wire   [0:0] tmp_88_fu_350_p3;
wire   [7:0] logical_word_index_1_fu_346_p1;
wire   [0:0] icmp_ln670_5_fu_393_p2;
wire   [2:0] result_1_fu_419_p4;
wire   [3:0] or_ln9_fu_432_p3;
wire   [3:0] zext_ln669_fu_428_p1;
wire   [3:0] result_48_fu_440_p3;
wire   [0:0] tmp_86_fu_451_p3;
wire   [4:0] result_3_fu_458_p3;
wire   [4:0] zext_ln669_1_fu_447_p1;
wire   [4:0] result_49_fu_466_p3;
wire   [0:0] tmp_87_fu_478_p3;
wire   [5:0] or_ln1_fu_485_p3;
wire   [5:0] zext_ln669_2_fu_474_p1;
wire   [5:0] result_50_fu_493_p3;
wire   [7:0] result_2_fu_501_p3;
wire   [15:0] result_4_fu_512_p4;
wire   [15:0] tmp_61_fu_525_p4;
wire   [24:0] result_51_fu_534_p4;
wire   [17:0] result_54_fu_549_p3;
wire   [17:0] zext_ln669_4_fu_546_p1;
wire   [17:0] result_55_fu_556_p3;
wire   [18:0] or_ln2_fu_567_p3;
wire   [18:0] zext_ln669_5_fu_563_p1;
wire   [18:0] result_56_fu_575_p3;
wire   [19:0] result_57_fu_586_p3;
wire   [19:0] zext_ln669_6_fu_582_p1;
wire   [19:0] result_58_fu_594_p3;
wire   [21:0] zext_ln746_fu_612_p1;
wire   [0:0] tmp_89_fu_605_p3;
wire   [22:0] or_ln3_fu_616_p3;
wire   [22:0] zext_ln669_7_fu_601_p1;
wire   [22:0] result_59_fu_624_p3;
wire   [0:0] xor_ln779_fu_636_p2;
wire   [0:0] and_ln670_fu_641_p2;
wire   [0:0] and_ln670_1_fu_645_p2;
wire   [0:0] and_ln670_2_fu_649_p2;
wire   [0:0] and_ln670_3_fu_653_p2;
wire   [0:0] and_ln670_4_fu_657_p2;
wire   [0:0] and_ln670_6_fu_661_p2;
wire   [31:0] result_62_fu_684_p4;
wire   [31:0] result_62_fu_684_p8;
wire   [31:0] result_62_fu_684_p10;
wire   [31:0] result_62_fu_684_p12;
wire   [31:0] result_62_fu_684_p14;
wire   [31:0] result_62_fu_684_p19;
wire   [7:0] result_62_fu_684_p20;
wire   [0:0] frame_end_fu_732_p2;
wire   [0:0] line_start_fu_727_p2;
wire   [31:0] result_62_fu_684_p21;
wire   [54:0] result_61_fu_736_p8;
wire    ap_CS_fsm_state4;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state4_blk;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire  signed [7:0] result_62_fu_684_p1;
wire   [7:0] result_62_fu_684_p3;
wire   [7:0] result_62_fu_684_p5;
wire   [7:0] result_62_fu_684_p7;
wire   [7:0] result_62_fu_684_p9;
wire   [7:0] result_62_fu_684_p11;
wire   [7:0] result_62_fu_684_p13;
wire   [7:0] result_62_fu_684_p15;
wire   [7:0] result_62_fu_684_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 line_word_index_fu_176 = 9'd0;
end

(* dissolve_hierarchy = "yes" *) gpx_lane_word_formatter_hls_sparsemux_19_8_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 8'h80 ),
    .din0_WIDTH( 32 ),
    .CASE1( 8'h40 ),
    .din1_WIDTH( 32 ),
    .CASE2( 8'h20 ),
    .din2_WIDTH( 32 ),
    .CASE3( 8'h10 ),
    .din3_WIDTH( 32 ),
    .CASE4( 8'h8 ),
    .din4_WIDTH( 32 ),
    .CASE5( 8'h4 ),
    .din5_WIDTH( 32 ),
    .CASE6( 8'h2 ),
    .din6_WIDTH( 32 ),
    .CASE7( 8'h1 ),
    .din7_WIDTH( 32 ),
    .CASE8( 8'h0 ),
    .din8_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
sparsemux_19_8_32_1_1_U49(
    .din0(32'd0),
    .din1(result_62_fu_684_p4),
    .din2(result_52_reg_817),
    .din3(result_62_fu_684_p8),
    .din4(result_62_fu_684_p10),
    .din5(result_62_fu_684_p12),
    .din6(result_62_fu_684_p14),
    .din7(32'd1129270612),
    .din8(32'd1196443185),
    .def(result_62_fu_684_p19),
    .sel(result_62_fu_684_p20),
    .dout(result_62_fu_684_p21)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        line_word_index_fu_176 <= 9'd0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln769_fu_305_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        line_word_index_fu_176 <= add_ln774_fu_310_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln670_5_reg_899 <= and_ln670_5_fu_399_p2;
        icmp_ln670_1_reg_879 <= icmp_ln670_1_fu_369_p2;
        icmp_ln670_2_reg_884 <= icmp_ln670_2_fu_375_p2;
        icmp_ln670_3_reg_889 <= icmp_ln670_3_fu_381_p2;
        icmp_ln670_4_reg_894 <= icmp_ln670_4_fu_387_p2;
        icmp_ln670_6_reg_904 <= icmp_ln670_6_fu_405_p2;
        icmp_ln670_reg_874 <= icmp_ln670_fu_363_p2;
        icmp_ln779_reg_857 <= icmp_ln779_fu_340_p2;
        line_end_reg_851 <= line_end_fu_316_p2;
        line_word_index_1_reg_842 <= line_word_index_fu_176;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        count_mismatch_reg_807 <= count_mismatch_fu_259_p2;
        or_ln_reg_827[15 : 0] <= or_ln_fu_281_p3[15 : 0];
        result_52_reg_817 <= result_52_fu_269_p3;
        zext_ln728_reg_822[15 : 0] <= zext_ln728_fu_277_p1[15 : 0];
        zext_ln769_reg_812[7 : 0] <= zext_ln769_fu_265_p1[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        result_53_reg_868 <= result_53_fu_357_p3;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

always @ (*) begin
    if ((icmp_ln769_fu_305_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        canonical_line_word_out_TDATA_blk_n = canonical_line_word_out_TREADY;
    end else begin
        canonical_line_word_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_grp1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        canonical_line_word_out_TVALID = 1'b1;
    end else begin
        canonical_line_word_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln769_fu_305_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (icmp_ln769_fu_305_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln774_fu_310_p2 = (line_word_index_fu_176 + 9'd1);

assign and_ln670_1_fu_645_p2 = (icmp_ln779_reg_857 & icmp_ln670_1_reg_879);

assign and_ln670_2_fu_649_p2 = (icmp_ln779_reg_857 & icmp_ln670_2_reg_884);

assign and_ln670_3_fu_653_p2 = (icmp_ln779_reg_857 & icmp_ln670_3_reg_889);

assign and_ln670_4_fu_657_p2 = (icmp_ln779_reg_857 & icmp_ln670_4_reg_894);

assign and_ln670_5_fu_399_p2 = (icmp_ln779_fu_340_p2 & icmp_ln670_5_fu_393_p2);

assign and_ln670_6_fu_661_p2 = (icmp_ln779_reg_857 & icmp_ln670_6_reg_904);

assign and_ln670_fu_641_p2 = (icmp_ln779_reg_857 & icmp_ln670_reg_874);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (canonical_line_word_out_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (canonical_line_word_out_TREADY == 1'b0));
end

always @ (*) begin
    ap_block_pp0_stage0_11001_grp1 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (canonical_line_word_out_TREADY == 1'b0));
end

assign ap_block_pp0_stage0_grp1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (canonical_line_word_out_TREADY == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign canonical_line_word_out_TDATA = result_61_fu_736_p8;

assign count_mismatch_fu_259_p2 = ((completed_lines != profile_planned_shot_columns_val) ? 1'b1 : 1'b0);

assign frame_end_fu_732_p2 = (line_end_reg_851 & final_footer_line);

assign icmp_ln670_1_fu_369_p2 = ((logical_word_index_1_fu_346_p1 == 8'd5) ? 1'b1 : 1'b0);

assign icmp_ln670_2_fu_375_p2 = ((logical_word_index_1_fu_346_p1 == 8'd4) ? 1'b1 : 1'b0);

assign icmp_ln670_3_fu_381_p2 = ((logical_word_index_1_fu_346_p1 == 8'd3) ? 1'b1 : 1'b0);

assign icmp_ln670_4_fu_387_p2 = ((logical_word_index_1_fu_346_p1 == 8'd2) ? 1'b1 : 1'b0);

assign icmp_ln670_5_fu_393_p2 = ((logical_word_index_1_fu_346_p1 == 8'd1) ? 1'b1 : 1'b0);

assign icmp_ln670_6_fu_405_p2 = ((logical_word_index_1_fu_346_p1 == 8'd7) ? 1'b1 : 1'b0);

assign icmp_ln670_fu_363_p2 = ((logical_word_index_1_fu_346_p1 == 8'd6) ? 1'b1 : 1'b0);

assign icmp_ln769_fu_305_p2 = ((line_word_index_fu_176 == profile_hsize_words_val) ? 1'b1 : 1'b0);

assign icmp_ln779_fu_340_p2 = ((tmp_fu_330_p4 == 7'd0) ? 1'b1 : 1'b0);

assign line_end_fu_316_p2 = ((add_ln774_fu_310_p2 == profile_hsize_words_val) ? 1'b1 : 1'b0);

assign line_start_fu_727_p2 = ((line_word_index_1_reg_842 == 9'd0) ? 1'b1 : 1'b0);

assign logical_word_index_1_fu_346_p1 = logical_word_index_fu_325_p2[7:0];

assign logical_word_index_fu_325_p2 = (zext_ln776_fu_321_p1 + zext_ln769_reg_812);

assign or_ln1_fu_485_p3 = {{1'd1}, {result_49_fu_466_p3}};

assign or_ln2_fu_567_p3 = {{1'd1}, {result_55_fu_556_p3}};

assign or_ln3_fu_616_p3 = {{1'd1}, {zext_ln746_fu_612_p1}};

assign or_ln9_fu_432_p3 = {{1'd1}, {result_1_fu_419_p4}};

assign or_ln_fu_281_p3 = {{1'd1}, {completed_lines}};

assign result_1_fu_419_p4 = {{close_result_val[34:32]}};

assign result_2_fu_501_p3 = {{profile_output_width_code_val}, {result_50_fu_493_p3}};

assign result_3_fu_458_p3 = {{1'd1}, {result_48_fu_440_p3}};

assign result_48_fu_440_p3 = ((profile_slope_is_rise_val[0:0] == 1'b1) ? or_ln9_fu_432_p3 : zext_ln669_fu_428_p1);

assign result_49_fu_466_p3 = ((tmp_86_fu_451_p3[0:0] == 1'b1) ? result_3_fu_458_p3 : zext_ln669_1_fu_447_p1);

assign result_4_fu_512_p4 = {{close_result_val[52:37]}};

assign result_50_fu_493_p3 = ((tmp_87_fu_478_p3[0:0] == 1'b1) ? or_ln1_fu_485_p3 : zext_ln669_2_fu_474_p1);

assign result_51_fu_534_p4 = {{{profile_serialized_return_slots_val}, {profile_cell_slot_count_val}}, {tmp_61_fu_525_p4}};

assign result_52_fu_269_p3 = {{profile_vsize_lines_val}, {profile_hsize_bytes_val}};

assign result_53_fu_357_p3 = ((tmp_88_fu_350_p3[0:0] == 1'b1) ? or_ln_reg_827 : zext_ln728_reg_822);

assign result_54_fu_549_p3 = {{1'd1}, {result_53_reg_868}};

assign result_55_fu_556_p3 = ((count_mismatch_reg_807[0:0] == 1'b1) ? result_54_fu_549_p3 : zext_ln669_4_fu_546_p1);

assign result_56_fu_575_p3 = ((p_anonymous_namespace_any_shot_line_fault[0:0] == 1'b1) ? or_ln2_fu_567_p3 : zext_ln669_5_fu_563_p1);

assign result_57_fu_586_p3 = {{1'd1}, {result_56_fu_575_p3}};

assign result_58_fu_594_p3 = ((p_anonymous_namespace_any_missing_shot_line[0:0] == 1'b1) ? result_57_fu_586_p3 : zext_ln669_6_fu_582_p1);

assign result_59_fu_624_p3 = ((tmp_89_fu_605_p3[0:0] == 1'b1) ? or_ln3_fu_616_p3 : zext_ln669_7_fu_601_p1);

assign result_61_fu_736_p8 = {{{{{{{frame_end_fu_732_p2}, {line_end_reg_851}}, {line_start_fu_727_p2}}, {profile_hsize_words_val}}, {line_word_index_1_reg_842}}, {2'd2}}, {result_62_fu_684_p21}};

assign result_62_fu_684_p10 = result_4_fu_512_p4;

assign result_62_fu_684_p12 = result_2_fu_501_p3;

assign result_62_fu_684_p14 = close_result_val[31:0];

assign result_62_fu_684_p19 = 'bx;

assign result_62_fu_684_p20 = {{{{{{{{xor_ln779_fu_636_p2}, {and_ln670_fu_641_p2}}, {and_ln670_1_fu_645_p2}}, {and_ln670_2_fu_649_p2}}, {and_ln670_3_fu_653_p2}}, {and_ln670_4_fu_657_p2}}, {and_ln670_5_reg_899}}, {and_ln670_6_fu_661_p2}};

assign result_62_fu_684_p4 = result_59_fu_624_p3;

assign result_62_fu_684_p8 = result_51_fu_534_p4;

assign tmp_61_fu_525_p4 = {{close_result_val[68:53]}};

assign tmp_86_fu_451_p3 = close_result_val[32'd35];

assign tmp_87_fu_478_p3 = close_result_val[32'd36];

assign tmp_88_fu_350_p3 = close_result_val[32'd86];

assign tmp_89_fu_605_p3 = close_result_val[32'd85];

assign tmp_fu_330_p4 = {{logical_word_index_fu_325_p2[9:3]}};

assign xor_ln779_fu_636_p2 = (icmp_ln779_reg_857 ^ 1'd1);

assign zext_ln669_1_fu_447_p1 = result_48_fu_440_p3;

assign zext_ln669_2_fu_474_p1 = result_49_fu_466_p3;

assign zext_ln669_4_fu_546_p1 = result_53_reg_868;

assign zext_ln669_5_fu_563_p1 = result_55_fu_556_p3;

assign zext_ln669_6_fu_582_p1 = result_56_fu_575_p3;

assign zext_ln669_7_fu_601_p1 = result_58_fu_594_p3;

assign zext_ln669_fu_428_p1 = result_1_fu_419_p4;

assign zext_ln728_fu_277_p1 = completed_lines;

assign zext_ln746_fu_612_p1 = result_58_fu_594_p3;

assign zext_ln769_fu_265_p1 = logical_word_offset;

assign zext_ln776_fu_321_p1 = line_word_index_fu_176;

always @ (posedge ap_clk) begin
    zext_ln769_reg_812[9:8] <= 2'b00;
    zext_ln728_reg_822[16] <= 1'b0;
    or_ln_reg_827[16] <= 1'b1;
end

endmodule //gpx_lane_word_formatter_hls_p_anonymous_namespace_emit_footer_line
