#ifndef TEST_XSTATUS_H
#define TEST_XSTATUS_H

#define XST_SUCCESS 0
#define XST_FAILURE 1
#define XST_NO_DATA 13
#define XST_INVALID_PARAM 15
#define XST_NO_FEATURE 19
#define XST_DEVICE_BUSY 21

#endif
